import { type Locale } from "@/lib/i18n/config";

const tr = {
  accountTitle: "Hesabım",
  reservations: "Rezervasyonlarım",
  profile: "Bilgilerim",
  companies: "Şirketlerim",
  loginTitle: "Giriş yap",
  registerTitle: "Kayıt ol",
  forgotTitle: "Şifremi unuttum",
  resetTitle: "Yeni şifre belirle",
  verifyTitle: "E-posta doğrulama",
  email: "E-posta",
  password: "Şifre",
  passwordConfirm: "Şifre tekrar",
  firstName: "Ad",
  lastName: "Soyad",
  phone: "Telefon",
  submitLogin: "Giriş yap",
  submitRegister: "Kayıt ol",
  submitForgot: "Sıfırlama bağlantısı gönder",
  submitReset: "Şifreyi güncelle",
  submitSave: "Kaydet",
  submitVerify: "E-posta adresimi doğrula",
  submitResend: "Doğrulama e-postasını tekrar gönder",
  haveAccount: "Zaten hesabınız var mı?",
  needAccount: "Hesabınız yok mu?",
  registerLink: "Kayıt olun",
  loginLink: "Giriş yap",
  forgotLink: "Şifremi unuttum",
  backToLogin: "Girişe dön",
  closeModal: "Kapat",
  registerSuccessTitle: "Kayıt işleminiz tamamlandı.",
  registerSuccessBody:
    "E-posta adresinize bir doğrulama bağlantısı gönderdik. Hesabınızı etkinleştirmek için lütfen e-postanızı kontrol edin.\n\nE-postayı göremiyorsanız Spam / Gereksiz klasörünüzü de kontrol edin.",
  logout: "Çıkış Yap",
  myAccount: "Hesabım",
  menuLabel: "Hesap menüsü",
  verifyPending:
    "Hesabınızı kullanmadan önce e-posta adresinizi doğrulayın. Gelen kutunuzu kontrol edin.",
  verifyRegistered: "Kayıt tamamlandı. Doğrulama bağlantısı e-posta adresinize gönderildi.",
  verifySuccess: "E-posta adresiniz doğrulandı.",
  verifyInvalid: "Doğrulama bağlantısı geçersiz veya kullanılmış.",
  verifyExpired: "Doğrulama bağlantısının süresi dolmuş.",
  resetSent: "Eğer bu e-posta kayıtlıysa sıfırlama bağlantısı gönderildi.",
  saved: "Bilgileriniz kaydedildi.",
  emailPending: "Yeni e-posta için doğrulama bağlantısı gönderildi. Mevcut e-posta aktif kalır.",
  resent:
    "Doğrulama e-postası tekrar gönderildi.\nLütfen gelen kutunuzu kontrol edin. E-postayı göremiyorsanız Spam / Gereksiz klasörünü de kontrol edin.",
  emptyReservations: "Henüz bir rezervasyonunuz yok.",
  emptyCompanies: "Henüz kayıtlı şirketiniz yok.",
  addCompany: "Şirket ekle",
  editCompany: "Şirketi düzenle",
  deleteCompany: "Sil",
  companyName: "Şirket unvanı",
  country: "Ülke",
  address: "Adres",
  city: "Şehir",
  postalCode: "Posta kodu",
  taxId: "Vergi / Tax ID",
  taxOffice: "Vergi dairesi",
  invoiceEmail: "Fatura e-posta adresi",
  companyPhone: "Telefon (opsiyonel)",
  isDefault: "Varsayılan şirket",
  pickup: "Alış",
  dropoff: "Bırakma",
  total: "Toplam",
  status: "Durum",
  paymentStatus: "Ödeme durumu",
  code: "Kod",
  service: "Hizmet",
  when: "Tarih / saat",
  error_invalid: "E-posta veya şifre hatalı.",
  error_throttled:
    "Çok fazla deneme. Lütfen bir dakika sonra tekrar deneyin.",
  error_invalid_name: "Ad ve soyad gerekli.",
  error_invalid_email: "Geçerli bir e-posta girin.",
  error_invalid_password: "Şifre en az 8 karakter olmalı ve eşleşmeli.",
  error_email_taken: "Bu e-posta ile zaten bir hesap var.",
  error_invalid_phone: "Telefon numarası geçersiz.",
  error_unauthenticated: "Oturum gerekli.",
  error_already_verified: "E-posta zaten doğrulanmış.",
  error_mail_send_failed:
    "Doğrulama e-postası gönderilemedi. Lütfen biraz sonra tekrar deneyin veya giriş yapıp yeniden gönderin.",
  error_expired: "Bağlantının süresi dolmuş.",
  error_invalid_company: "Şirket unvanı gerekli.",
  error_invalid_country: "Ülke seçin.",
  error_invalid_address: "Adres ve şehir gerekli.",
  error_invalid_tr_tax: "Türkiye için vergi kimlik no ve vergi dairesi gerekli.",
  error_not_found: "Kayıt bulunamadı.",
  pendingEmailLabel: "Doğrulama bekleyen e-posta",
  bookReservation: "Rezervasyon Yap",
  detail: "Detay",
  editReservation: "Rezervasyonu Düzenle",
  cancelReservation: "İptal Et",
  editComingSoon: "Rezervasyon düzenleme özelliği hazırlanıyor.",
  cancelComingSoon: "İptal özelliği hazırlanıyor.",
  detailTitle: "Rezervasyon detayı",
  duration: "Süre",
  vehicle: "Araç",
  passengerCount: "Yolcu sayısı",
  passengers: "Yolcular",
  flightCode: "Uçuş kodu",
  meetAndGreet: "Karşılama hizmeti",
  packageInfo: "Tur / paket",
  paymentMethod: "Ödeme yöntemi",
  notes: "Not",
  yes: "Evet",
  no: "Hayır",
  reservationStatusActive: "Aktif",
  reservationStatusCancelled: "İptal edildi",
  paymentStatusPending: "Bekleniyor",
  paymentStatusPaid: "Tahsil edildi",
  paymentStatusFailed: "Başarısız",
  paymentMethodOnline: "Online",
  paymentMethodCash: "Nakit",
  alternatePaymentHint: "Yolcu farklı para birimiyle ödeme yapmak isterse",
  alternatePaymentHintCustomer: "Farklı para birimi ile ödeme yapmak isterseniz",
  selectedPrice: "Seçilen fiyat",
  paymentProvider: "Ödeme sağlayıcısı",
  flightNotProvided: "Belirtilmedi",
  downloadVoucherPdf: "Voucher PDF İndir",
  luggageCount: "Valiz sayısı",
  babySeatCount: "Bebek koltuğu",
  activateReservation: "Aktif Et",
  cancelBlockedSixHours:
    "Rezervasyon başlangıcına 6 saat veya daha az kaldığı için artık değişiklik veya iptal işlemi yapılamaz.",
  reactivateBlockedSixHours:
    "Rezervasyon saatine 6 saat veya daha az kaldığı için rezervasyonunuz yeniden aktif edilemez.",
  reactivateBlockedBosphorusCutoff:
    "Bu tur için hizmet günü saat 19:00’dan sonra rezervasyon yeniden aktif edilemez.",
  cancelConfirmTitle: "Rezervasyonu iptal et",
  cancelConfirm:
    "Rezervasyonunuzu iptal etmek istediğinize emin misiniz?",
  cancelConfirmWithRefund:
    "Rezervasyonunuzu iptal etmek üzeresiniz.\nTahsil edilmiş uygun tutarın %100’ü ödeme yönteminize iade edilecektir.\nİptal işlemini onaylıyor musunuz?",
  cancelConfirmSubmit: "Rezervasyonu İptal Et",
  cancelConfirmDismiss: "Vazgeç",
  cancelRefundFailed:
    "İade işlemi tamamlanamadı. Rezervasyonunuz iptal edilmedi. Lütfen tekrar deneyin veya Tripetica ile iletişime geçin.",
  cancelPendingFailed:
    "Bekleyen ödeme siparişi iptal edilemedi. Rezervasyonunuz henüz iptal edilmedi. Lütfen tekrar deneyin veya Tripetica ile iletişime geçin.",
  statusUpdateFailed: "İşlem tamamlanamadı. Lütfen tekrar deneyin.",
  editBlockedSixHours:
    "Rezervasyon başlangıcına 6 saat veya daha az kaldığı için artık değişiklik veya iptal işlemi yapılamaz.",
  editInfoTitle: "Rezervasyonunuzu düzenlemeye yönlendiriliyorsunuz",
  editInfoBody1:
    "Mevcut rezervasyon bilgileriniz korunarak rezervasyon sürecinin başına döneceksiniz. Oradan istediğiniz bilgileri değiştirerek yeniden ilerleyebilirsiniz.",
  editInfoBody2:
    "Yapacağınız değişikliklere bağlı olarak rezervasyon ücretiniz artabilir veya azalabilir. Oluşabilecek fiyat farkı değişiklikleri onaylamadan önce size gösterilecektir.",
  editInfoContinue: "Düzenlemeye devam et",
  editInfoCancel: "Vazgeç",
  editStartFailed: "Düzenleme başlatılamadı. Lütfen tekrar deneyin.",
  editModeBanner: "Rezervasyon düzenleniyor: {code}",
  editModeAbandon: "Düzenlemeden vazgeç",
  opsEditModeBanner:
    "Operasyon düzenleme modu — {code} rezervasyonu düzenleniyor.",
  opsEditWithinSixHoursWarning:
    "Rezervasyon başlangıcına 6 saatten az kaldı. Operasyon düzenlemesi yapıyorsunuz.",
  financialSummary: "Ödeme özeti",
  financeReservationTotal: "Rezervasyon toplamı",
  financeTotalPaid: "Toplam ödenen",
  financeRefundRequested: "İade talep edilen",
  financeRefunded: "İade edilen",
  financeRefundStatus: "İade durumu",
  financeRefundStatusSubmitted: "İade talep edildi",
  financeRefundStatusCompleted: "İade tamamlandı",
  financeRefundStatusFailed: "İade başarısız",
  financeRefundStatusPartial: "Kısmi iade / müdahale gerekli",
};

const en: typeof tr = {
  accountTitle: "My account",
  reservations: "My reservations",
  profile: "My details",
  companies: "My companies",
  loginTitle: "Sign in",
  registerTitle: "Create account",
  forgotTitle: "Forgot password",
  resetTitle: "Set a new password",
  verifyTitle: "Email verification",
  email: "Email",
  password: "Password",
  passwordConfirm: "Confirm password",
  firstName: "First name",
  lastName: "Last name",
  phone: "Phone",
  submitLogin: "Sign in",
  submitRegister: "Create account",
  submitForgot: "Send reset link",
  submitReset: "Update password",
  submitSave: "Save",
  submitVerify: "Verify my email",
  submitResend: "Resend verification email",
  haveAccount: "Already have an account?",
  needAccount: "Need an account?",
  registerLink: "Create account",
  loginLink: "Sign in",
  forgotLink: "Forgot password",
  backToLogin: "Back to sign in",
  closeModal: "Close",
  registerSuccessTitle: "Your registration is complete.",
  registerSuccessBody:
    "We sent a verification link to your email. Please check your inbox to activate your account.\n\nIf you do not see the email, check your Spam / Junk folder as well.",
  logout: "Sign out",
  myAccount: "My account",
  menuLabel: "Account menu",
  verifyPending:
    "Please verify your email before using your account. Check your inbox.",
  verifyRegistered: "Registration complete. A verification link was sent to your email.",
  verifySuccess: "Your email has been verified.",
  verifyInvalid: "This verification link is invalid or already used.",
  verifyExpired: "This verification link has expired.",
  resetSent: "If that email is registered, a reset link was sent.",
  saved: "Your details were saved.",
  emailPending: "A confirmation link was sent to the new email. Your current email stays active.",
  resent:
    "Verification email resent.\nPlease check your inbox. If you do not see it, check your Spam / Junk folder as well.",
  emptyReservations: "You have no reservations yet.",
  emptyCompanies: "You have no saved companies yet.",
  addCompany: "Add company",
  editCompany: "Edit company",
  deleteCompany: "Delete",
  companyName: "Company name",
  country: "Country",
  address: "Address",
  city: "City",
  postalCode: "Postal code",
  taxId: "Tax / VAT ID",
  taxOffice: "Tax office",
  invoiceEmail: "Invoice email",
  companyPhone: "Phone (optional)",
  isDefault: "Default company",
  pickup: "Pickup",
  dropoff: "Drop-off",
  total: "Total",
  status: "Status",
  paymentStatus: "Payment status",
  code: "Code",
  service: "Service",
  when: "Date / time",
  error_invalid: "Invalid email or password.",
  error_throttled: "Too many attempts. Please try again in a minute.",
  error_invalid_name: "First and last name are required.",
  error_invalid_email: "Enter a valid email.",
  error_invalid_password: "Password must be at least 8 characters and match.",
  error_email_taken: "An account with this email already exists.",
  error_invalid_phone: "Invalid phone number.",
  error_unauthenticated: "Sign in required.",
  error_already_verified: "Email is already verified.",
  error_mail_send_failed:
    "We could not send the verification email. Please try again later, or sign in and resend.",
  error_expired: "This link has expired.",
  error_invalid_company: "Company name is required.",
  error_invalid_country: "Select a country.",
  error_invalid_address: "Address and city are required.",
  error_invalid_tr_tax: "Tax ID and tax office are required for Turkey.",
  error_not_found: "Not found.",
  pendingEmailLabel: "Pending email confirmation",
  bookReservation: "Book a reservation",
  detail: "Details",
  editReservation: "Edit reservation",
  cancelReservation: "Cancel",
  editComingSoon: "Reservation editing is coming soon.",
  cancelComingSoon: "Cancellation is coming soon.",
  detailTitle: "Reservation details",
  duration: "Duration",
  vehicle: "Vehicle",
  passengerCount: "Passengers",
  passengers: "Passengers",
  flightCode: "Flight code",
  meetAndGreet: "Meet and greet",
  packageInfo: "Tour / package",
  paymentMethod: "Payment method",
  notes: "Notes",
  yes: "Yes",
  no: "No",
  reservationStatusActive: "Active",
  reservationStatusCancelled: "Cancelled",
  paymentStatusPending: "Pending",
  paymentStatusPaid: "Collected",
  paymentStatusFailed: "Failed",
  paymentMethodOnline: "Online",
  paymentMethodCash: "Cash",
  alternatePaymentHint: "If the passenger wants to pay in a different currency",
  alternatePaymentHintCustomer: "If you want to pay in a different currency",
  selectedPrice: "Selected price",
  paymentProvider: "Payment provider",
  flightNotProvided: "Not provided",
  downloadVoucherPdf: "Download voucher PDF",
  luggageCount: "Luggage",
  babySeatCount: "Child seats",
  activateReservation: "Reactivate",
  cancelBlockedSixHours:
    "Changes or cancellation are no longer available because 6 hours or less remain before the service start time.",
  reactivateBlockedSixHours:
    "Your reservation cannot be reactivated because 6 hours or less remain before the service time.",
  reactivateBlockedBosphorusCutoff:
    "This tour cannot be reactivated after 19:00 on the service day.",
  cancelConfirmTitle: "Cancel reservation",
  cancelConfirm:
    "Are you sure you want to cancel your reservation?",
  cancelConfirmWithRefund:
    "You are about to cancel your reservation.\n100% of the eligible collected amount will be refunded to your payment method.\nDo you want to continue?",
  cancelConfirmSubmit: "Cancel reservation",
  cancelConfirmDismiss: "Keep reservation",
  cancelRefundFailed:
    "The refund could not be completed. Your reservation was not cancelled. Please try again or contact Tripetica.",
  cancelPendingFailed:
    "A pending payment order could not be cancelled. Your reservation was not cancelled. Please try again or contact Tripetica.",
  statusUpdateFailed: "Could not complete the action. Please try again.",
  editBlockedSixHours:
    "Changes or cancellation are no longer available because 6 hours or less remain before the service start time.",
  editInfoTitle: "You are about to edit your reservation",
  editInfoBody1:
    "Your current reservation details will be kept and you will return to the start of the booking flow. From there you can change what you need and continue.",
  editInfoBody2:
    "Depending on your changes, the reservation price may increase or decrease. Any price difference will be shown to you before you confirm the changes.",
  editInfoContinue: "Continue editing",
  editInfoCancel: "Cancel",
  editStartFailed: "Could not start editing. Please try again.",
  editModeBanner: "Editing reservation: {code}",
  editModeAbandon: "Abandon edit",
  opsEditModeBanner: "Operations edit mode — editing reservation {code}.",
  opsEditWithinSixHoursWarning:
    "Less than 6 hours remain before the service start. You are making an operations edit.",
  financialSummary: "Payment summary",
  financeReservationTotal: "Reservation total",
  financeTotalPaid: "Total paid",
  financeRefundRequested: "Refund requested",
  financeRefunded: "Refunded",
  financeRefundStatus: "Refund status",
  financeRefundStatusSubmitted: "Refund requested",
  financeRefundStatusCompleted: "Refund completed",
  financeRefundStatusFailed: "Refund failed",
  financeRefundStatusPartial: "Partial refund / action required",
};

const ru: typeof tr = {
  accountTitle: "Мой аккаунт",
  reservations: "Мои бронирования",
  profile: "Мои данные",
  companies: "Мои компании",
  loginTitle: "Войти",
  registerTitle: "Регистрация",
  forgotTitle: "Забыли пароль",
  resetTitle: "Новый пароль",
  verifyTitle: "Подтверждение email",
  email: "Эл. почта",
  password: "Пароль",
  passwordConfirm: "Повтор пароля",
  firstName: "Имя",
  lastName: "Фамилия",
  phone: "Телефон",
  submitLogin: "Войти",
  submitRegister: "Зарегистрироваться",
  submitForgot: "Отправить ссылку",
  submitReset: "Обновить пароль",
  submitSave: "Сохранить",
  submitVerify: "Подтвердить email",
  submitResend: "Отправить письмо ещё раз",
  haveAccount: "Уже есть аккаунт?",
  needAccount: "Нет аккаунта?",
  registerLink: "Зарегистрироваться",
  loginLink: "Войти",
  forgotLink: "Забыли пароль",
  backToLogin: "К входу",
  closeModal: "Закрыть",
  registerSuccessTitle: "Регистрация завершена.",
  registerSuccessBody:
    "Мы отправили ссылку для подтверждения на ваш email. Проверьте почту, чтобы активировать аккаунт.\n\nЕсли письма нет, загляните в папку Спам / Junk.",
  logout: "Выйти",
  myAccount: "Мой аккаунт",
  menuLabel: "Меню аккаунта",
  verifyPending:
    "Подтвердите email, прежде чем пользоваться аккаунтом. Проверьте почту.",
  verifyRegistered: "Регистрация завершена. Ссылка для подтверждения отправлена на email.",
  verifySuccess: "Email подтверждён.",
  verifyInvalid: "Ссылка недействительна или уже использована.",
  verifyExpired: "Срок действия ссылки истёк.",
  resetSent: "Если email зарегистрирован, ссылка для сброса отправлена.",
  saved: "Данные сохранены.",
  emailPending: "На новый email отправлена ссылка. Текущий email остаётся активным.",
  resent:
    "Письмо для подтверждения отправлено повторно.\nПроверьте входящие. Если письма нет, загляните в папку Спам / Junk.",
  emptyReservations: "Пока нет бронирований.",
  emptyCompanies: "Пока нет сохранённых компаний.",
  addCompany: "Добавить компанию",
  editCompany: "Изменить компанию",
  deleteCompany: "Удалить",
  companyName: "Название компании",
  country: "Страна",
  address: "Адрес",
  city: "Город",
  postalCode: "Индекс",
  taxId: "ИНН / Tax ID",
  taxOffice: "Налоговая инспекция",
  invoiceEmail: "Email для счетов",
  companyPhone: "Телефон (необязательно)",
  isDefault: "Компания по умолчанию",
  pickup: "Подача",
  dropoff: "Назначение",
  total: "Итого",
  status: "Статус",
  paymentStatus: "Статус оплаты",
  code: "Код",
  service: "Услуга",
  when: "Дата / время",
  error_invalid: "Неверный email или пароль.",
  error_throttled: "Слишком много попыток. Подождите минуту и попробуйте снова.",
  error_invalid_name: "Укажите имя и фамилию.",
  error_invalid_email: "Введите корректный email.",
  error_invalid_password: "Пароль не менее 8 символов и должен совпадать.",
  error_email_taken: "Аккаунт с таким email уже существует.",
  error_invalid_phone: "Некорректный телефон.",
  error_unauthenticated: "Требуется вход.",
  error_already_verified: "Email уже подтверждён.",
  error_mail_send_failed:
    "Не удалось отправить письмо для подтверждения. Попробуйте позже или войдите и отправьте снова.",
  error_expired: "Срок ссылки истёк.",
  error_invalid_company: "Укажите название компании.",
  error_invalid_country: "Выберите страну.",
  error_invalid_address: "Укажите адрес и город.",
  error_invalid_tr_tax: "Для Турции нужны ИНН и налоговая инспекция.",
  error_not_found: "Не найдено.",
  pendingEmailLabel: "Ожидает подтверждения email",
  bookReservation: "Забронировать",
  detail: "Подробнее",
  editReservation: "Изменить бронирование",
  cancelReservation: "Отменить",
  editComingSoon: "Редактирование бронирования скоро будет доступно.",
  cancelComingSoon: "Отмена бронирования скоро будет доступна.",
  detailTitle: "Детали бронирования",
  duration: "Длительность",
  vehicle: "Автомобиль",
  passengerCount: "Количество пассажиров",
  passengers: "Пассажиры",
  flightCode: "Код рейса",
  meetAndGreet: "Встреча с табличкой",
  packageInfo: "Тур / пакет",
  paymentMethod: "Способ оплаты",
  notes: "Заметка",
  yes: "Да",
  no: "Нет",
  reservationStatusActive: "Активно",
  reservationStatusCancelled: "Отменено",
  paymentStatusPending: "Ожидается",
  paymentStatusPaid: "Получено",
  paymentStatusFailed: "Ошибка",
  paymentMethodOnline: "Онлайн",
  paymentMethodCash: "Наличные",
  alternatePaymentHint: "Если пассажир хочет оплатить в другой валюте",
  alternatePaymentHintCustomer: "Если вы хотите оплатить в другой валюте",
  selectedPrice: "Выбранная цена",
  paymentProvider: "Платёжный провайдер",
  flightNotProvided: "Не указан",
  downloadVoucherPdf: "Скачать ваучер PDF",
  luggageCount: "Багаж",
  babySeatCount: "Детские кресла",
  activateReservation: "Активировать",
  cancelBlockedSixHours:
    "Изменения или отмена больше недоступны: до начала услуги осталось 6 часов или меньше.",
  reactivateBlockedSixHours:
    "Бронирование нельзя снова активировать: до начала услуги осталось 6 часов или меньше.",
  reactivateBlockedBosphorusCutoff:
    "Этот тур нельзя снова активировать после 19:00 в день услуги.",
  cancelConfirmTitle: "Отменить бронирование",
  cancelConfirm:
    "Вы уверены, что хотите отменить бронирование?",
  cancelConfirmWithRefund:
    "Вы собираетесь отменить бронирование.\n100% подходящей собранной суммы будет возвращено на ваш способ оплаты.\nПродолжить?",
  cancelConfirmSubmit: "Отменить бронирование",
  cancelConfirmDismiss: "Оставить бронирование",
  cancelRefundFailed:
    "Не удалось выполнить возврат. Бронирование не отменено. Попробуйте ещё раз или свяжитесь с Tripetica.",
  cancelPendingFailed:
    "Не удалось отменить ожидающий платёжный заказ. Бронирование не отменено. Попробуйте ещё раз или свяжитесь с Tripetica.",
  statusUpdateFailed: "Не удалось выполнить действие. Попробуйте ещё раз.",
  editBlockedSixHours:
    "Изменения или отмена больше недоступны: до начала услуги осталось 6 часов или меньше.",
  editInfoTitle: "Вы переходите к изменению бронирования",
  editInfoBody1:
    "Текущие данные бронирования будут сохранены, и вы вернётесь к началу процесса бронирования. Там вы сможете изменить нужные поля и продолжить.",
  editInfoBody2:
    "В зависимости от изменений стоимость может вырасти или снизиться. Возможная разница в цене будет показана до подтверждения изменений.",
  editInfoContinue: "Продолжить изменение",
  editInfoCancel: "Отмена",
  editStartFailed: "Не удалось начать изменение. Попробуйте ещё раз.",
  editModeBanner: "Изменение бронирования: {code}",
  editModeAbandon: "Отменить изменение",
  opsEditModeBanner:
    "Режим редактирования операций — изменяется бронирование {code}.",
  opsEditWithinSixHoursWarning:
    "До начала услуги осталось меньше 6 часов. Вы выполняете операционное изменение.",
  financialSummary: "Сводка оплаты",
  financeReservationTotal: "Сумма бронирования",
  financeTotalPaid: "Всего оплачено",
  financeRefundRequested: "Запрошен возврат",
  financeRefunded: "Возвращено",
  financeRefundStatus: "Статус возврата",
  financeRefundStatusSubmitted: "Возврат запрошен",
  financeRefundStatusCompleted: "Возврат выполнен",
  financeRefundStatusFailed: "Возврат не удался",
  financeRefundStatusPartial: "Частичный возврат / требуется действие",
};

export const accountCopy: Record<Locale, typeof tr> = { tr, en, ru };
export type AccountCopy = (typeof accountCopy)[Locale];

export function accountErrorMessage(copy: AccountCopy, code?: string | null) {
  if (!code) {
    return null;
  }
  const key = `error_${code}` as keyof AccountCopy;
  const value = copy[key];
  return typeof value === "string" ? value : copy.error_invalid;
}
