import { type Locale, type PanelLocale, asPanelLocale } from "@/lib/i18n/config";
import { OPS_MIN_PASSWORD_LENGTH } from "@/lib/ops/constants";
import { type OpsPermission } from "@/lib/ops/permissions";

export const opsCopy = {
  tr: {
    brand: "Tripetica",
    panelName: "Tripetica Operasyon Paneli",
    loginLead: "Yetkili kullanıcı girişi",
    email: "E-posta adresi",
    password: "Şifre",
    signIn: "Giriş Yap",
    signingIn: "Giriş yapılıyor…",
    showPassword: "Şifreyi göster",
    hidePassword: "Şifreyi gizle",
    invalidLogin: "E-posta veya şifre hatalı.",
    throttledLogin: "Çok fazla başarısız deneme. Lütfen daha sonra tekrar deneyin.",
    logout: "Çıkış",
    language: "Dil",
    menu: "Menü",
    closeMenu: "Menüyü kapat",
    reservations: "Rezervasyonlar",
    processes: "Rezervasyon Süreçleri",
    users: "Panel Kullanıcıları",
    myAccount: "Bilgilerim",
    customers: "Müşteriler",
    partners: "Partnerler",
    drivers: "Sürücüler",
    vehicles: "Araçlar",
    partnerCode: "Partner Kodu",
    partnerName: "Partner Adı",
    primaryPartner: "Ana Partner",
    emptyPartners: "Henüz partner yok.",
    partnerSearchPlaceholder: "Kod veya partner adı",
    partnerLegalName: "Partner Adı / Ticari Unvan",
    partnerLevel: "Partner Seviyesi",
    partnerContact: "Yetkili Kişi",
    partnerContactFullName: "Yetkili Kişi Adı Soyadı",
    partnerPhone: "Telefon",
    partnerEmail: "E-posta",
    partnerPriority: "Partner Öncelik Seviyesi",
    partnerPriorityUnset: "Seçilmedi",
    partnerPriority1: "1. Seviye",
    partnerPriority2: "2. Seviye",
    partnerPriority3: "3. Seviye",
    pending: "Onay Bekliyor",
    partnerTabJobs: "İşler",
    partnerTabInfo: "Bilgiler",
    partnerTabDrivers: "Sürücüler",
    partnerTabVehicles: "Araçlar",
    emptyPartnerJobs: "Bu partnerin kabul ettiği iş yok.",
    jobSearchPlaceholder: "İş ara...",
    emptyJobSearch: "Eşleşen iş bulunamadı.",
    partnerJobCode: "Rezervasyon",
    partnerJobWhen: "Tarih & Saat",
    partnerJobService: "Hizmet",
    partnerJobRoute: "Rota",
    partnerJobPayout: "Partner ödemesi",
    partnerJobCollect: "Yolcudan tahsil",
    emptyPartnerDrivers: "Bu partnere kayıtlı sürücü bulunmuyor.",
    emptyPartnerVehicles: "Bu partnere kayıtlı araç bulunmuyor.",
    driverSearchPlaceholder: "Sürücü ara...",
    vehicleSearchPlaceholder: "Araç ara...",
    emptyDriverSearch: "Eşleşen sürücü bulunamadı.",
    emptyVehicleSearch: "Eşleşen araç bulunamadı.",
    emptyDrivers: "Henüz sürücü yok.",
    emptyVehicles: "Henüz araç yok.",
    linkedPartner: "Partner",
    activatePartner: "Aktif Et",
    deactivatePartner: "Pasife Al",
    activatingPartner: "Aktif ediliyor…",
    deactivatingPartner: "Pasife alınıyor…",
    activatePartnerNeedPriority: "Aktif etmek için önce Partner Öncelik Seviyesi seçin ve kaydedin.",
    activatePartnerNeedFields: "Aktif etmek için zorunlu partner bilgilerini tamamlayın.",
    partnerBusinessType: "İşletme Türü",
    partnerIndividual: "Şahıs İşletmesi",
    partnerCompany: "Tüzel Kişi",
    partnerAddress: "Adres",
    partnerCountry: "Ülke",
    partnerTaxOffice: "Vergi Dairesi",
    partnerTaxNumber: "Vergi Numarası",
    partnerAppliedAt: "Başvuru tarihi",
    partnerUpdatedAt: "Son güncelleme",
    partnerSaved: "Partner bilgileri güncellendi.",
    partnerSaveFailed: "Partner bilgileri kaydedilemedi.",
    primaryPartnerTaken: "Sistemde zaten bir Ana Partner var.",
    partnerActivateFailed: "Partner aktif edilemedi.",
    partnerDeactivateFailed: "Partner pasife alınamadı.",
    deletePartner: "Sil",
    deletingPartner: "Siliniyor…",
    deletePartnerConfirm: "Bu partneri tamamen silmek istediğinizden emin misiniz?",
    deletePartnerNo: "Vazgeç",
    deletePartnerYes: "Evet, sil",
    deletePartnerFailed: "Partner silinemedi.",
    driverFullName: "Sürücü Adı Soyadı",
    driverNationalId: "T.C. Kimlik Numarası",
    invalidDriverEmail: "Geçerli bir e-posta adresi girin.",
    duplicateDriverEmail: "Bu e-posta başka bir kayıtlı şoför tarafından kullanılıyor.",
    driverLanguages: "Konuştuğu Diller",
    driverRowIndex: "#",
    languageSearch: "Dil ara",
    languageNoResults: "Eşleşen dil bulunamadı.",
    languageSelected: "Seçili diller",
    invalidNationalId: "T.C. Kimlik Numarası 11 haneli olmalıdır.",
    invalidLanguages: "En az bir konuşulan dil seçin.",
    invalidDriverName: "Ad ve soyadı girin.",
    invalidPhone: "Geçerli bir telefon numarası girin.",
    duplicateNationalId: "Bu T.C. Kimlik Numarası ile kayıtlı bir sürücü zaten var.",
    vehiclePlate: "Plaka",
    vehicleBrand: "Marka",
    vehicleModel: "Model",
    vehicleBrandModel: "Marka / Model",
    invalidPlate: "Geçerli bir plaka girin.",
    invalidBrandModel: "Marka / model girin.",
    vehicleColor: "Renk",
    vehicleFeatures: "Araç özellikleri",
    vehicleModelYear: "Model yılı",
    vehiclePassengers: "Yolcu kapasitesi",
    vehicleLuggage: "Valiz kapasitesi",
    vehiclePassengersShort: "yolcu",
    vehicleBagsShort: "valiz",
    vehicleCapacity: "Kapasite",
    vehicleClass: "Araç sınıfı",
    vehicleClassHint: "Aracınızın Tripetica'daki tahmini hizmet sınıfını seçin.",
    vehicleActive: "Aktif",
    vehicleInactive: "Pasif",
    vehiclePending: "Onay Bekliyor",
    vehicleRejected: "Reddedildi",
    approveVehicle: "Onayla",
    rejectVehicle: "Reddet",
    approvingVehicle: "Onaylanıyor…",
    rejectingVehicle: "Reddediliyor…",
    duplicatePlate: "Bu plaka ile kayıtlı bir araç zaten var.",
    invalidVehicleYear: "Geçerli bir model yılı seçin.",
    searchBrand: "Marka ara",
    searchModel: "Model ara",
    noBrandResults: "Eşleşen marka bulunamadı.",
    noModelResults: "Eşleşen model bulunamadı.",
    featureSearch: "Özellik ara",
    featureSelected: "Seçili özellikler",
    colorBlack: "Siyah",
    colorWhite: "Beyaz",
    colorGray: "Gri",
    colorSilver: "Gümüş",
    colorNavy: "Lacivert",
    colorBlue: "Mavi",
    colorRed: "Kırmızı",
    colorBrown: "Kahverengi",
    colorBeige: "Bej",
    colorOther: "Diğer",
    featureAc: "Klima",
    featureWifi: "Wi-Fi",
    featureLeather: "Deri koltuk",
    featurePartition: "Ara bölme",
    featureStarlight: "Yıldız tavan",
    featureTv: "TV / Multimedya",
    featureFridge: "Buzdolabı",
    featureUsb: "USB şarj",
    featureBabySeat: "Bebek koltuğu",
    featureElectricDoor: "Elektrikli kapı",
    featureOther: "Diğer",
    driverSaved: "Sürücü bilgileri güncellendi.",
    driverSaveFailed: "Sürücü bilgileri kaydedilemedi.",
    driverActivateFailed: "Sürücü aktif edilemedi.",
    driverDeactivateFailed: "Sürücü pasife alınamadı.",
    deleteDriverConfirm: "Bu sürücüyü silmek istediğinizden emin misiniz?",
    deleteDriverFailed: "Sürücü silinemedi.",
    vehicleSaved: "Araç bilgileri güncellendi.",
    vehicleSaveFailed: "Araç bilgileri kaydedilemedi.",
    vehicleActivateFailed: "Araç aktif edilemedi.",
    vehicleDeactivateFailed: "Araç pasife alınamadı.",
    deleteVehicleConfirm: "Bu aracı silmek istediğinizden emin misiniz?",
    deleteVehicleFailed: "Araç silinemedi.",
    fleetInUse: "Bu kayıt ilişkili olduğu için silinemiyor.",
    passwordTooShort: `Şifre en az ${OPS_MIN_PASSWORD_LENGTH} karakter olmalı.`,
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    currentPassword: "Mevcut Şifre",
    newPassword: "Yeni Şifre",
    confirmPassword: "Yeni Şifre Tekrar",
    changePassword: "Şifreyi Değiştir",
    savePassword: "Şifreyi Kaydet",
    savingPassword: "Kaydediliyor…",
    passwordChanged: "Şifreniz güncellendi.",
    currentPasswordInvalid: "Mevcut şifre hatalı.",
    passwordChangeFailed: "Şifre güncellenemedi. Lütfen tekrar deneyin.",
    fullName: "Ad Soyad",
    editField: "Düzenle",
    invalidEmail: "Geçerli bir e-posta girin.",
    invalidName: "Ad ve soyad gerekli.",
    profileSaved: "Bilgileriniz güncellendi.",
    search: "Ara",
    filter: "Filtrele",
    refresh: "Yenile",
    refreshing: "Yenileniyor…",
    emptyReservations: "Henüz rezervasyon yok.",
    emptyProcesses: "Henüz rezervasyon süreci yok.",
    createdDateFilter: "Oluşturulma tarihi",
    dateToday: "Bugün",
    dateYesterday: "Dün",
    dateLast7: "Son 7 Gün",
    dateMonth: "Bu Ay",
    datePast: "Geçmiş",
    dateRange: "Tarih Aralığı",
    transferDateFilter: "Rezervasyon tarihi ve saati",
    dateTomorrow: "Yarın",
    dateNext7: "Sonraki 7 Gün",
    dateNextMonth: "Gelecek Ay",
    datePastMonth: "Geçmiş Ay",
    dateUpcoming: "Gelecek",
    paymentSbpQr: "QR / SBP",
    dateFrom: "Başlangıç tarihi",
    dateTo: "Bitiş tarihi",
    clearFilters: "Filtreleri Temizle",
    selectedCount: "{n} kayıt seçildi",
    pageSelected: "Bu sayfadaki {n} kayıt seçildi.",
    selectAllFiltered: "Filtrelenen tüm {n} kaydı seç",
    allFilteredSelected: "Filtrelenen {n} kaydın tamamı seçildi.",
    clearSelection: "Seçimi Temizle",
    deleteSelected: "Seçilenleri Sil",
    deleteModalTitle: "Rezervasyon süreçlerini sil",
    deleteModalBody:
      "{n} rezervasyon sürecini kalıcı olarak silmek üzeresiniz. Bu işlem geri alınamaz.",
    deleteMixed:
      "{d} kayıt silinecek. {p} kayıt gerçek rezervasyona dönüştüğü için korunacak.",
    deleteProtected: "{n} kayıt gerçek rezervasyona dönüştüğü için silinemez.",
    deleteNothing: "Silinecek uygun kayıt yok.",
    deleteFailed: "Kayıtlar silinemedi. Lütfen tekrar deneyin.",
    cancel: "İptal",
    confirmDelete: "Kalıcı Olarak Sil",
    deleting: "Siliniyor…",
    deleteResult: "{d} kayıt silindi.",
    selectColumn: "Seç",
    emptyUsers: "Henüz panel kullanıcısı yok.",
    emptyCustomers: "Henüz müşteri yok.",
    page: "Sayfa",
    of: "/",
    previous: "Önceki",
    next: "Sonraki",
    back: "Geri",
    details: "Detay",
    yes: "Evet",
    no: "Hayır",
    converted: "Rezervasyona dönüştü",
    notConverted: "Dönüşmedi",
    all: "Tümü",
    active: "Aktif",
    inactive: "Pasif",
    status: "Durum",
    role: "Rol",
    owner: "Owner",
    employee: "Çalışan",
    newUser: "Yeni Panel Kullanıcısı",
    save: "Kaydet",
    saving: "Kaydediliyor…",
    firstName: "Ad",
    lastName: "Soyad",
    permissions: "Yetkiler",
    lastLogin: "Son giriş",
    createdAt: "Oluşturulma",
    verification: "Doğrulama",
    verified: "Doğrulandı",
    unverified: "Doğrulanmadı",
    customerSearchPlaceholder: "Ad, e-posta veya telefon",
    reservationHistory: "Rezervasyon Geçmişi",
    emptyCustomerReservations: "Bu müşteriye ait rezervasyon bulunamadı.",
    passwordOptional: "Şifre (değiştirmek için doldurun)",
    emailTaken: "Bu e-posta zaten kayıtlı.",
    lastOwner: "Sistemde en az bir aktif Owner kalmalıdır.",
    saved: "Kaydedildi.",
    forbidden: "Bu işlem için yetkiniz yok.",
    reservationCode: "Rezervasyon kodu",
    transferAt: "Tarih / Saat",
    pickup: "Alış noktası",
    dropoff: "Bırakma noktası",
    mainPassenger: "Ana yolcu",
    passengerCount: "Yolcu sayısı",
    passengerLuggageBaby: "Yolcu / Valiz / Bebek",
    vehicle: "Araç",
    assignmentSection: "Partner / Operasyon Ataması",
    assignmentPartner: "Partner",
    assignmentDriver: "Şoför",
    assignmentVehicle: "Atanan araç",
    assignmentUnassigned: "—",
    assignmentSelectPartner: "Partner seç",
    assignmentSearchPartner: "Partner ara",
    assignmentEmptyPartners: "Eşleşen aktif partner yok.",
    assignmentClearPartner: "Partner atamasını kaldır",
    assignmentRemovePartnerConfirm:
      "Bu partneri rezervasyondan kaldırmak istediğinize emin misiniz?",
    assignmentRemovePartnerNo: "Hayır, kaldırılmasın",
    assignmentRemovePartnerYes: "Evet, kaldır",
    assignmentSelectDriver: "Şoför ata",
    assignmentSelectVehicle: "Araç ata",
    assignmentSearchDriver: "Şoför ara",
    assignmentSearchVehicle: "Araç ara",
    assignmentEmptyDrivers: "Bu partnere ait aktif şoför yok.",
    assignmentEmptyVehicles: "Bu partnere ait aktif araç yok.",
    assignmentClearDriver: "Şoför atamasını kaldır",
    assignmentClearVehicle: "Araç atamasını kaldır",
    assignmentNeedPartner: "Önce partner seçin",
    assignmentFailed: "Atama kaydedilemedi. Lütfen tekrar deneyin.",
    assignmentForbidden: "Bu işlem için yetkiniz yok.",
    assignmentForeignFleet: "Şoför veya araç seçilen partnere ait değil.",
    assignmentInactivePartner: "Bu partner aktif değil.",
    assignmentNonTrp: "NON TRP",
    assignmentNote: "Açıklama / Not",
    assignmentRegistered: "Kayıtlı",
    assignmentKind: "Kayıt türü",
    passengerNotify: "Yolcu Bilgilendirme",
    passengerNotifySend: "Bilgi gönder",
    passengerNotifyResend: "Bilgiler değişti · Tekrar gönder",
    passengerNotifySent: "Gönderildi",
    passengerNotifyNeedVehicle: "Önce araç atayın",
    passengerNotifyNeedEmail: "Yolcu e-postası yok",
    passengerNotifyLocked: "İptal rezervasyonda gönderilemez",
    passengerNotifyTitle: "Yolcuya bilgi gönder",
    passengerNotifyVehicle: "Araç bilgilerini gönder",
    passengerNotifyDriver: "Şoför bilgilerini de gönder",
    passengerNotifySubmit: "Yolcuya Gönder",
    passengerNotifySending: "Gönderiliyor…",
    passengerNotifyFailed: "Mail gönderilemedi. Lütfen tekrar deneyin.",
    passengerNotifyNoChange: "Bu bilgiler yolcuya zaten gönderildi.",
    passengerNotifyNeedDriver: "Şoför ataması yok",
    passengerNotifyMissingEmail: "Yolcu e-postası bulunamadı.",
    operationStatus: "Operasyon Durumu",
    operationActive: "Aktif",
    operationCompleted: "Tamamlananlar",
    operationCancelled: "İptal Edilenler",
    operationAll: "Tümü",
    driverTask: "Şoför Görevi",
    driverTaskOpen: "Görevi Aç",
    driverTaskCopy: "Linki Kopyala",
    driverTaskCopied: "Link kopyalandı",
    driverTaskShowPrice: "Ücret bilgilerini göster",
    driverTaskShowContact: "Yolcu iletişim bilgilerini göster",
    operationHistory: "Operasyon Geçmişi",
    driverTaskPlanned: "Planlandı",
    driverTaskEnRoute: "Yoldayım",
    driverTaskArrived: "Alış Noktasında",
    driverTaskPickedUp: "Yolcu Alındı",
    driverTaskCompleted: "Tamamlandı",
    driverTaskHistoryEnRoute: "Yoldayım",
    driverTaskHistoryArrived: "Alış noktasına vardı",
    driverTaskHistoryPickedUp: "Yolcular alındı",
    driverTaskHistoryCompleted: "Yolcular bırakıldı",
    total: "Toplam tutar",
    currency: "Para birimi",
    paymentMethod: "Ödeme yöntemi",
    meetAndGreet: "Karşılama hizmeti",
    created: "Oluşturulma tarihi",
    transferInfo: "Hizmet bilgileri",
    customer: "Müşteri",
    contactInfo: "İletişim Bilgileri",
    pricingInfo: "Ücret Bilgileri",
    passengers: "Yolcular",
    payment: "Ödeme",
    system: "Sistem",
    distance: "Mesafe",
    kilometre: "Kilometre",
    flight: "Uçuş kodu",
    luggage: "Bagaj",
    babySeat: "Bebek koltuğu",
    phone: "Telefon",
    fxSnapshot: "FX snapshot",
    reservationId: "Reservation ID",
    sourceSearch: "source_reservation_search_id",
    confirmedAt: "Onay",
    cancelledAt: "İptal",
    updatedAt: "Son güncellenme",
    stage: "Mevcut aşama",
    locale: "Dil",
    selected: "Seçilen",
    applied: "Uygulanan",
    searchTransfer: "Transfer / arama",
    vehiclePrice: "Araç / fiyat",
    technical: "Teknik / analitik",
    conversion: "Rezervasyona dönüştü",
    openProcesses: "Açık süreçler",
    convertedProcesses: "Dönüşen süreçler",
    identity: "Kimlik no",
    gender: "Cinsiyet",
    primary: "Ana yolcu",
    notes: "Notlar",
    passengerNote: "Yolcu Notu",
    noAccess: "Bu bölüme erişim yetkiniz yok.",
    processDetailTitle: "Rezervasyon Süreci Detayı",
    reservationDetailTitle: "Rezervasyon Detayı",
    processPdfTitle: "Rezervasyon Süreci Özeti",
    reservationPdfTitle: "Rezervasyon Özeti",
    opsRecordSummary: "Tripetica Operasyon Kayıt Özeti",
    downloadPdf: "PDF İndir",
    opsPdf: "Operasyon PDF",
    voucherPdf: "Voucher PDF",
    showContact: "İletişim bilgilerini göster",
    hideContact: "İletişim bilgilerini gizle",
    showPricing: "Ücret bilgilerini göster",
    hidePricing: "Ücret bilgilerini gizle",
    contactHidden: "Gizli",
    loadingDetail: "Detay yükleniyor…",
    detailError: "Kayıt detayı yüklenemedi.",
    close: "Kapat",
    edit: "Düzenle",
    delete: "Sil",
    deleteReservationConfirm: "Bu rezervasyonu silmek istediğinize emin misiniz?",
    deleteReservationNo: "Hayır, silme",
    deleteReservationYes: "Evet, sil",
    deleteReservationError: "Rezervasyon silinemedi. Lütfen tekrar deneyin.",
    cancelEdit: "İptal",
    saveChanges: "Değişiklikleri Kaydet",
    savingChanges: "Kaydediliyor…",
    editSaveError: "Değişiklikler kaydedilemedi. Lütfen alanları kontrol edin.",
    editPrice: "Fiyatı Düzenle",
    editPriceTitle: "Fiyat düzenleme",
    recalcOtherCurrencies: "Diğer para birimlerini yeniden hesapla",
    pickupAddress: "Alış adresi",
    dropoffAddress: "Bırakma adresi",
    pickupDate: "Tarih",
    pickupTime: "Saat",
    passengerInfo: "Yolcu Bilgileri",
    noPassengers: "Yolcu bilgisi henüz girilmemiş.",
    serviceType: "Hizmet türü",
    durationHours: "Süre",
    packageCoverage: "Paket kapsamı",
    vehicleCode: "Araç kodu",
    appliedPrice: "Uygulanan fiyat",
    selectedPrice: "Seçilen Fiyat",
    otherCurrencies: "Diğer Para Birimleri",
    alternatePaymentHint: "Yolcu farklı para birimiyle ödeme yapmak isterse",
    nationality: "Ülke / uyruk",
    quoteOpening: "Açılış ücreti",
    quoteDistance: "Mesafe ücreti",
    quoteLocation: "Bölge / ilçe ücreti",
    quoteTime: "Saat dilimi ücreti",
    quoteBase: "Transfer taban ücreti",
    pricingVersion: "Fiyat kuralı sürümü",
    fxBase: "FX baz para birimi",
    fxCaptured: "FX kayıt zamanı",
    fxTotalEur: "EUR toplam",
    techDevice: "Cihaz türü",
    techOs: "İşletim sistemi",
    techBrowser: "Tarayıcı",
    techViewport: "Viewport",
    techScreen: "Ekran",
    techBrowserLanguage: "Tarayıcı dili",
    techClientTimezone: "İstemci saat dilimi",
    statusDraft: "Taslak",
    statusCompleted: "Tamamlandı",
    statusExpired: "Süresi doldu",
    statusConfirmed: "Onaylandı",
    statusCancelled: "İptal",
    stageVehicleSelection: "Araç seçimi",
    stageCheckout: "Checkout",
    serviceTransfer: "Özel Transfer & Taksi",
    serviceHourly: "Saatlik Şoförlü Araç",
    serviceTour: "Turlar & Rotalar",
    paymentCash: "Nakit",
    paymentSbp: "SBP",
    paymentOnlineSbp: "Online",
    paymentProvider: "Ödeme sağlayıcı",
    paymentStatus: "Ödeme durumu",
    paymentStatusPending: "Bekleniyor",
    paymentStatusPaid: "Tahsil edildi",
    paymentStatusFailed: "Başarısız",
    refundStatus: "İade durumu",
    refundStatusNone: "—",
    refundStatusSubmitted: "İade talep edildi",
    refundStatusCompleted: "İade gerçekleşti",
    refundStatusFailed: "İade başarısız",
    refundAmount: "İade tutarı",
    refundCurrency: "İade para birimi",
    refundRequestedAt: "İade talep tarihi",
    refundCompletedAt: "İade tamamlanma tarihi",
    refundProviderId: "Turinvoice iade ID",
    refundOverrideNote: "İade notu",
    refundOverrideApplied: "İade süresi dışında yönetici onayıyla yapıldı",
    refundAction: "Para İadesi Yap",
    refundActionCashDisabled: "Nakit ödeme için online para iadesi uygulanamaz.",
    refundNotCancelledTitle: "Rezervasyon henüz iptal edilmedi",
    refundNotCancelledBody:
      "Para iadesi yapılabilmesi için önce rezervasyonun iptal edilmesi gerekir.",
    refundNotPaidTitle: "Para iadesi yapılamaz",
    refundNotPaidBody:
      "Bu rezervasyon için doğrulanmış bir online ödeme bulunmadığından para iadesi yapılamaz.",
    refundAlreadyTitle: "Para iadesi zaten gönderildi",
    refundAlreadyBody: "Bu tahsilat için iade talebi zaten oluşturulmuş.",
    refundCashTitle: "Online para iadesi yapılamaz",
    refundCashBody: "Nakit ödeme için online para iadesi uygulanamaz.",
    refundConfirmTitle: "Para iadesini onaylayın",
    refundConfirmBody:
      "Bu işlem müşteriye {amount} tutarında tam ücret iadesi gönderecektir.\n\nPara iadesini gerçekleştirmek istediğinizden emin misiniz?",
    refundOverrideTitle: "İade süresi dışında işlem",
    refundOverrideBody:
      "Bu rezervasyon normal iade süresinin dışında iptal edilmiştir.\n\nBuna rağmen müşteriye {amount} tutarında tam ücret iadesi yapmak istediğinizden emin misiniz?",
    refundConfirmNo: "Hayır",
    refundConfirmYes: "Evet, Para İadesi Yap",
    refundOverrideYes: "Evet, Yine de İade Et",
    refundOk: "Tamam",
    refunding: "İade gönderiliyor…",
    refundError: "Para iadesi gönderilemedi. Lütfen tekrar deneyin.",
    paymentHistoryTitle: "Ödeme Geçmişi",
    paymentHistoryEmpty: "Bu rezervasyon için Turinvoice ödeme hareketi yok.",
    paymentHistoryDate: "Tarih / Saat",
    paymentHistoryOrderId: "Turinvoice Sipariş ID",
    paymentHistoryAmount: "Tutar",
    paymentHistoryCurrency: "Para Birimi",
    paymentHistoryStatus: "Durum",
    paymentHistoryAction: "İşlem",
    paymentHistorySummaryTitle: "Özet",
    paymentHistoryReservationTotal: "Güncel rezervasyon toplamı",
    paymentHistoryGrossPaid: "Toplam başarılı tahsilat",
    paymentHistoryCompletedRefunds: "Toplam tamamlanmış iade",
    paymentHistoryNetCollected: "Net tahsilat",
    paymentHistoryRemainingDue: "Kalan ödeme",
    paymentMovementPending: "Bekleniyor",
    paymentMovementPaid: "Tahsil edildi",
    paymentMovementCancelled: "İptal edildi",
    paymentMovementFailed: "Başarısız",
    paymentMovementPartialRefund: "Kısmi iade",
    paymentMovementRefunded: "İade edildi",
    paymentMovementPendingShort: "Bekliyor",
    paymentMovementPaidShort: "Tahsil",
    paymentMovementCancelledShort: "İptal",
    paymentMovementFailedShort: "Başarısız",
    paymentMovementPartialRefundShort: "Kısmi iade",
    paymentMovementRefundedShort: "İade",
    paymentMovementsColumn: "Ödeme hareketleri",
    paymentMovementsMore: "+{n} hareket",
    paymentMovementsNone: "—",
    paymentCancelOrder: "Siparişi İptal Et",
    paymentCancelOrderUnsupported:
      "Turinvoice entegrasyonunda bekleyen sipariş iptali henüz desteklenmiyor.",
    paymentCancelConfirmTitle: "Siparişi iptal et",
    paymentCancelConfirmBody:
      "Bu bekleyen Turinvoice siparişi iptal edilecek. Devam etmek istiyor musunuz?",
    paymentCancelConfirmSubmit: "Siparişi İptal Et",
    paymentCancelConfirmDismiss: "Vazgeç",
    paymentCancelSubmitting: "İptal ediliyor…",
    paymentCancelFailed:
      "Sipariş iptal edilemedi. Turinvoice tarafında işlem başarısız oldu.",
    paymentRefundAction: "İade Et",
    paymentRefundModalTitle: "İade işlemi",
    paymentRefundCollected: "Tahsil edilen",
    paymentRefundAlready: "Daha önce iade edilen",
    paymentRefundMax: "Maksimum iade edilebilir",
    paymentRefundAmount: "İade edilecek tutar",
    paymentRefundFull: "Tam tutarı iade et",
    paymentRefundSubmit: "İade Talimatını Gönder",
    paymentRefundCancel: "Vazgeç",
    paymentRefundInvalidAmount: "Geçerli bir iade tutarı girin.",
    paymentRefundExceedsMax: "Tutar, maksimum iade edilebilir tutarı aşamaz.",
    paymentRefundSubmitting: "İade gönderiliyor…",
    paymentRefundFailed: "İade gönderilemedi. Lütfen tekrar deneyin.",
    fxRatesProviderLabel: "ExchangeRate-API",
    fxRatesLastFetch: "Son çekim",
    fxRatesNextRefresh: "Sonraki güncelleme",
    fxRatesTitle: "Döviz kuru özeti (Tripetica son çekim + ExchangeRate-API sonraki güncelleme)",
    fxRatesUnavailable: "Kur bilgisi yok",
    genderFemale: "Kadın",
    genderMale: "Erkek",
    localeTr: "Türkçe",
    localeEn: "İngilizce",
    localeRu: "Rusça",
    reservationStatusActive: "Aktif",
    reservationStatusCancelled: "İptal edildi",
    reservationStatusPaymentPending: "Ödeme bekleniyor",
    cancelReservation: "İptal Et",
    activateReservation: "Aktif Et",
    cancelReservationTitle: "Rezervasyonu iptal et",
    cancelReservationBody: "Bu rezervasyonu iptal etmek istediğinize emin misiniz?",
    cancelReservationWithinBody:
      "Bu rezervasyonu iptal etmek istediğinizden emin misiniz?\n\nRezervasyon normal iade süresi içerisindedir. İptal işleminden sonra isterseniz ayrıca para iadesi yapabilirsiniz.",
    cancelReservationOutsideTitle: "İade süresi geçmiş",
    cancelReservationOutsideBody:
      "Bu rezervasyona 6 saatten az kaldığı için normal koşullarda ücret iadesi hakkı bulunmamaktadır.\n\nBuna rağmen rezervasyonu iptal etmek istediğinizden emin misiniz?",
    cancelReservationLateTitle: "Rezervasyonu iptal et",
    cancelReservationLateBody:
      "Bu rezervasyonun başlangıcına 6 saat veya daha az kaldı. Rezervasyonu iptal etmek istediğinizden emin misiniz?",
    cancelReservationLateYes: "Evet, İptal Et",
    cancelReservationYes: "Rezervasyonu İptal Et",
    cancelReservationOutsideYes: "Yine de İptal Et",
    cancelReservationNo: "Vazgeç",
    cancelReservationError: "Rezervasyon iptal edilemedi. Lütfen tekrar deneyin.",
    editReservationLateTitle: "Rezervasyonu düzenle",
    editReservationLateBody:
      "Bu rezervasyonun başlangıcına 6 saat veya daha az kaldı. Rezervasyonda değişiklik yapmaya devam etmek istiyor musunuz?",
    editReservationLateYes: "Düzenlemeye Devam Et",
    editReservationLateNo: "Vazgeç",
    activateReservationTitle: "Rezervasyonu aktif et",
    activateReservationBody:
      "Bu rezervasyonu tekrar aktif hale getirmek istediğinize emin misiniz?",
    activateReservationYes: "Evet, aktif et",
    activateReservationNo: "Vazgeç",
    activateReservationError: "Rezervasyon aktif edilemedi. Lütfen tekrar deneyin.",
    cancelling: "İptal ediliyor…",
    activating: "Aktif ediliyor…",
    pushEnable: "Bildirimleri Aç",
    pushEnabled: "Bildirimler açık",
    pushDisabled: "Bildirimler kapalı",
    pushUnsupported: "Cihaz/tarayıcı desteklemiyor",
    pushIosInstall:
      "iPhone veya iPad’de bildirim almak için Tripetica’yı Ana Ekrana ekleyin, uygulamayı açın ve Bildirimleri Aç’a dokunun.",
    pushBusy: "Kaydediliyor…",
    permissionLabels: {
      "reservations.view": "Rezervasyonları görüntüleme",
      "reservations.manage": "Rezervasyonları yönetme",
      "records.edit": "Kayıt düzenleme",
      "processes.view": "Rezervasyon süreçlerini görüntüleme",
      "processes.delete": "Rezervasyon süreçlerini silme",
      "customers.view": "Müşterileri görüntüleme",
      "partners.view": "Partnerleri görüntüleme",
      "partners.manage": "Partnerleri yönetme",
      "users.view": "Panel kullanıcılarını görüntüleme",
      "users.manage": "Panel kullanıcılarını yönetme",
    } satisfies Record<OpsPermission, string>,
  },
  en: {
    brand: "Tripetica",
    panelName: "Tripetica Operations Panel",
    loginLead: "Authorized user access",
    email: "Email address",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    invalidLogin: "Invalid email or password.",
    throttledLogin: "Too many failed attempts. Please try again later.",
    logout: "Log out",
    language: "Language",
    menu: "Menu",
    closeMenu: "Close menu",
    reservations: "Reservations",
    processes: "Reservation processes",
    users: "Panel Users",
    myAccount: "My account",
    customers: "Customers",
    partners: "Partners",
    drivers: "Drivers",
    vehicles: "Vehicles",
    partnerCode: "Partner code",
    partnerName: "Partner name",
    primaryPartner: "Primary partner",
    emptyPartners: "No partners yet.",
    partnerSearchPlaceholder: "Code or partner name",
    partnerLegalName: "Partner name / legal title",
    partnerLevel: "Partner level",
    partnerContact: "Authorized person",
    partnerContactFullName: "Authorized person full name",
    partnerPhone: "Phone",
    partnerEmail: "Email",
    partnerPriority: "Partner priority level",
    partnerPriorityUnset: "Not set",
    partnerPriority1: "Level 1",
    partnerPriority2: "Level 2",
    partnerPriority3: "Level 3",
    pending: "Pending approval",
    partnerTabJobs: "Jobs",
    partnerTabInfo: "Details",
    partnerTabDrivers: "Drivers",
    partnerTabVehicles: "Vehicles",
    emptyPartnerJobs: "This partner has not accepted any jobs.",
    jobSearchPlaceholder: "Search jobs...",
    emptyJobSearch: "No matching jobs.",
    partnerJobCode: "Reservation",
    partnerJobWhen: "Date & time",
    partnerJobService: "Service",
    partnerJobRoute: "Route",
    partnerJobPayout: "Partner payout",
    partnerJobCollect: "Collect from passenger",
    emptyPartnerDrivers: "No drivers are registered for this partner.",
    emptyPartnerVehicles: "No vehicles are registered for this partner.",
    driverSearchPlaceholder: "Search drivers...",
    vehicleSearchPlaceholder: "Search vehicles...",
    emptyDriverSearch: "No matching drivers.",
    emptyVehicleSearch: "No matching vehicles.",
    emptyDrivers: "No drivers yet.",
    emptyVehicles: "No vehicles yet.",
    linkedPartner: "Partner",
    activatePartner: "Activate",
    deactivatePartner: "Deactivate",
    activatingPartner: "Activating…",
    deactivatingPartner: "Deactivating…",
    activatePartnerNeedPriority: "Select and save a partner priority level before activating.",
    activatePartnerNeedFields: "Complete the required partner details before activating.",
    partnerBusinessType: "Business type",
    partnerIndividual: "Sole proprietorship",
    partnerCompany: "Legal entity",
    partnerAddress: "Address",
    partnerCountry: "Country",
    partnerTaxOffice: "Tax office",
    partnerTaxNumber: "Tax number",
    partnerAppliedAt: "Application date",
    partnerUpdatedAt: "Last updated",
    partnerSaved: "Partner details updated.",
    partnerSaveFailed: "Partner details could not be saved.",
    primaryPartnerTaken: "A primary partner is already assigned.",
    partnerActivateFailed: "The partner could not be activated.",
    partnerDeactivateFailed: "The partner could not be deactivated.",
    deletePartner: "Delete",
    deletingPartner: "Deleting…",
    deletePartnerConfirm: "Are you sure you want to delete this partner permanently?",
    deletePartnerNo: "Cancel",
    deletePartnerYes: "Yes, delete",
    deletePartnerFailed: "The partner could not be deleted.",
    driverFullName: "Driver full name",
    driverNationalId: "National ID number",
    invalidDriverEmail: "Enter a valid email address.",
    duplicateDriverEmail: "This email is already used by another registered driver.",
    driverLanguages: "Spoken languages",
    driverRowIndex: "#",
    languageSearch: "Search languages",
    languageNoResults: "No matching languages.",
    languageSelected: "Selected languages",
    invalidNationalId: "The national ID number must be 11 digits.",
    invalidLanguages: "Select at least one spoken language.",
    invalidDriverName: "Enter first and last name.",
    invalidPhone: "Enter a valid phone number.",
    duplicateNationalId: "A driver with this national ID is already registered.",
    vehiclePlate: "Plate",
    vehicleBrand: "Brand",
    vehicleModel: "Model",
    vehicleBrandModel: "Brand / model",
    invalidPlate: "Enter a valid plate.",
    invalidBrandModel: "Enter make / model.",
    vehicleColor: "Color",
    vehicleFeatures: "Vehicle features",
    vehicleModelYear: "Model year",
    vehiclePassengers: "Passenger capacity",
    vehicleLuggage: "Luggage capacity",
    vehiclePassengersShort: "passengers",
    vehicleBagsShort: "bags",
    vehicleCapacity: "Capacity",
    vehicleClass: "Vehicle class",
    vehicleClassHint: "Select the vehicle’s estimated Tripetica service class.",
    vehicleActive: "Active",
    vehicleInactive: "Inactive",
    vehiclePending: "Pending approval",
    vehicleRejected: "Rejected",
    approveVehicle: "Approve",
    rejectVehicle: "Reject",
    approvingVehicle: "Approving…",
    rejectingVehicle: "Rejecting…",
    duplicatePlate: "A vehicle with this plate is already registered.",
    invalidVehicleYear: "Select a valid model year.",
    searchBrand: "Search makes",
    searchModel: "Search models",
    noBrandResults: "No matching makes.",
    noModelResults: "No matching models.",
    featureSearch: "Search features",
    featureSelected: "Selected features",
    colorBlack: "Black",
    colorWhite: "White",
    colorGray: "Gray",
    colorSilver: "Silver",
    colorNavy: "Navy",
    colorBlue: "Blue",
    colorRed: "Red",
    colorBrown: "Brown",
    colorBeige: "Beige",
    colorOther: "Other",
    featureAc: "Air conditioning",
    featureWifi: "Wi-Fi",
    featureLeather: "Leather seats",
    featurePartition: "Partition",
    featureStarlight: "Starlight roof",
    featureTv: "TV / multimedia",
    featureFridge: "Refrigerator",
    featureUsb: "USB charging",
    featureBabySeat: "Baby seat",
    featureElectricDoor: "Power sliding door",
    featureOther: "Other",
    driverSaved: "Driver details updated.",
    driverSaveFailed: "Driver details could not be saved.",
    driverActivateFailed: "The driver could not be activated.",
    driverDeactivateFailed: "The driver could not be deactivated.",
    deleteDriverConfirm: "Are you sure you want to delete this driver?",
    deleteDriverFailed: "The driver could not be deleted.",
    vehicleSaved: "Vehicle details updated.",
    vehicleSaveFailed: "Vehicle details could not be saved.",
    vehicleActivateFailed: "The vehicle could not be activated.",
    vehicleDeactivateFailed: "The vehicle could not be deactivated.",
    deleteVehicleConfirm: "Are you sure you want to delete this vehicle?",
    deleteVehicleFailed: "The vehicle could not be deleted.",
    fleetInUse: "This record cannot be deleted because it is still in use.",
    passwordTooShort: `Password must be at least ${OPS_MIN_PASSWORD_LENGTH} characters.`,
    passwordMismatch: "New passwords do not match.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    changePassword: "Change password",
    savePassword: "Save password",
    savingPassword: "Saving…",
    passwordChanged: "Your password has been updated.",
    currentPasswordInvalid: "Current password is incorrect.",
    passwordChangeFailed: "The password could not be updated. Please try again.",
    fullName: "Full name",
    editField: "Edit",
    invalidEmail: "Enter a valid email address.",
    invalidName: "First and last name are required.",
    profileSaved: "Your details have been updated.",
    search: "Search",
    filter: "Filter",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    emptyReservations: "No reservations yet.",
    emptyProcesses: "No reservation processes yet.",
    createdDateFilter: "Created date",
    dateToday: "Today",
    dateYesterday: "Yesterday",
    dateLast7: "Last 7 days",
    dateMonth: "This month",
    datePast: "Past",
    dateRange: "Date range",
    transferDateFilter: "Reservation date and time",
    dateTomorrow: "Tomorrow",
    dateNext7: "Next 7 days",
    dateNextMonth: "Next month",
    datePastMonth: "Previous month",
    dateUpcoming: "Upcoming",
    paymentSbpQr: "QR / SBP",
    dateFrom: "Start date",
    dateTo: "End date",
    clearFilters: "Clear filters",
    selectedCount: "{n} records selected",
    pageSelected: "{n} records on this page selected.",
    selectAllFiltered: "Select all {n} filtered records",
    allFilteredSelected: "All {n} filtered records selected.",
    clearSelection: "Clear selection",
    deleteSelected: "Delete selected",
    deleteModalTitle: "Delete reservation processes",
    deleteModalBody:
      "You are about to permanently delete {n} reservation processes. This cannot be undone.",
    deleteMixed:
      "{d} records will be deleted. {p} records will be kept because they converted to real reservations.",
    deleteProtected: "{n} records cannot be deleted because they converted to real reservations.",
    deleteNothing: "No eligible records to delete.",
    deleteFailed: "Records could not be deleted. Please try again.",
    cancel: "Cancel",
    confirmDelete: "Delete permanently",
    deleting: "Deleting…",
    deleteResult: "{d} records deleted.",
    selectColumn: "Select",
    emptyUsers: "No panel users yet.",
    emptyCustomers: "No customers yet.",
    page: "Page",
    of: "of",
    previous: "Previous",
    next: "Next",
    back: "Back",
    details: "Details",
    yes: "Yes",
    no: "No",
    converted: "Converted to reservation",
    notConverted: "Not converted",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    status: "Status",
    role: "Role",
    owner: "Owner",
    employee: "Employee",
    newUser: "New Panel User",
    save: "Save",
    saving: "Saving…",
    firstName: "First name",
    lastName: "Last name",
    permissions: "Permissions",
    lastLogin: "Last login",
    createdAt: "Created",
    verification: "Verification",
    verified: "Verified",
    unverified: "Unverified",
    customerSearchPlaceholder: "Name, email, or phone",
    reservationHistory: "Reservation History",
    emptyCustomerReservations: "No reservations found for this customer.",
    passwordOptional: "Password (fill to change)",
    emailTaken: "This email is already registered.",
    lastOwner: "At least one active Owner must remain.",
    saved: "Saved.",
    forbidden: "You do not have permission for this action.",
    reservationCode: "Reservation code",
    transferAt: "Date / Time",
    pickup: "Pickup",
    dropoff: "Drop-off",
    mainPassenger: "Lead passenger",
    passengerCount: "Passenger count",
    passengerLuggageBaby: "Passengers / Luggage / Baby seats",
    vehicle: "Vehicle",
    assignmentSection: "Partner / operations assignment",
    assignmentPartner: "Partner",
    assignmentDriver: "Driver",
    assignmentVehicle: "Assigned vehicle",
    assignmentUnassigned: "—",
    assignmentSelectPartner: "Select partner",
    assignmentSearchPartner: "Search partners",
    assignmentEmptyPartners: "No matching active partners.",
    assignmentClearPartner: "Remove partner assignment",
    assignmentRemovePartnerConfirm:
      "Are you sure you want to remove this partner from the reservation?",
    assignmentRemovePartnerNo: "No, keep it",
    assignmentRemovePartnerYes: "Yes, remove",
    assignmentSelectDriver: "Assign driver",
    assignmentSelectVehicle: "Assign vehicle",
    assignmentSearchDriver: "Search drivers",
    assignmentSearchVehicle: "Search vehicles",
    assignmentEmptyDrivers: "No active drivers for this partner.",
    assignmentEmptyVehicles: "No active vehicles for this partner.",
    assignmentClearDriver: "Remove driver assignment",
    assignmentClearVehicle: "Remove vehicle assignment",
    assignmentNeedPartner: "Select a partner first",
    assignmentFailed: "Assignment could not be saved. Please try again.",
    assignmentForbidden: "You do not have permission for this action.",
    assignmentForeignFleet: "That driver or vehicle does not belong to the selected partner.",
    assignmentInactivePartner: "This partner is not active.",
    assignmentNonTrp: "NON TRP",
    assignmentNote: "Notes",
    assignmentRegistered: "Registered",
    assignmentKind: "Record type",
    passengerNotify: "Passenger notice",
    passengerNotifySend: "Send details",
    passengerNotifyResend: "Details changed · Send again",
    passengerNotifySent: "Sent",
    passengerNotifyNeedVehicle: "Assign a vehicle first",
    passengerNotifyNeedEmail: "No passenger email",
    passengerNotifyLocked: "Cannot send on a cancelled reservation",
    passengerNotifyTitle: "Send passenger details",
    passengerNotifyVehicle: "Send vehicle details",
    passengerNotifyDriver: "Also send driver details",
    passengerNotifySubmit: "Send to passenger",
    passengerNotifySending: "Sending…",
    passengerNotifyFailed: "The email could not be sent. Please try again.",
    passengerNotifyNoChange: "These details were already sent to the passenger.",
    passengerNotifyNeedDriver: "No driver assigned",
    passengerNotifyMissingEmail: "Passenger email is missing.",
    operationStatus: "Operation status",
    operationActive: "Active",
    operationCompleted: "Completed",
    operationCancelled: "Cancelled",
    operationAll: "All",
    driverTask: "Driver task",
    driverTaskOpen: "Open task",
    driverTaskCopy: "Copy link",
    driverTaskCopied: "Link copied",
    driverTaskShowPrice: "Show fare details",
    driverTaskShowContact: "Show passenger contact details",
    operationHistory: "Operation history",
    driverTaskPlanned: "Planned",
    driverTaskEnRoute: "On the way",
    driverTaskArrived: "At pickup",
    driverTaskPickedUp: "Passengers picked up",
    driverTaskCompleted: "Completed",
    driverTaskHistoryEnRoute: "On the way",
    driverTaskHistoryArrived: "Arrived at pickup",
    driverTaskHistoryPickedUp: "Passengers picked up",
    driverTaskHistoryCompleted: "Passengers dropped off",
    total: "Total",
    currency: "Currency",
    paymentMethod: "Payment method",
    meetAndGreet: "Meet and greet",
    created: "Created",
    transferInfo: "Service details",
    customer: "Customer",
    contactInfo: "Contact details",
    pricingInfo: "Price details",
    passengers: "Passengers",
    payment: "Payment",
    system: "System",
    distance: "Distance",
    kilometre: "Kilometres",
    flight: "Flight number",
    luggage: "Luggage",
    babySeat: "Baby seat",
    phone: "Phone",
    fxSnapshot: "FX snapshot",
    reservationId: "Reservation ID",
    sourceSearch: "source_reservation_search_id",
    confirmedAt: "Confirmed",
    cancelledAt: "Cancelled",
    updatedAt: "Last updated",
    stage: "Current stage",
    locale: "Language",
    selected: "Selected",
    applied: "Applied",
    searchTransfer: "Transfer / search",
    vehiclePrice: "Vehicle / price",
    technical: "Technical / analytics",
    conversion: "Converted to reservation",
    openProcesses: "Open processes",
    convertedProcesses: "Converted processes",
    identity: "ID number",
    gender: "Gender",
    primary: "Lead passenger",
    notes: "Notes",
    passengerNote: "Passenger Note",
    noAccess: "You do not have access to this section.",
    processDetailTitle: "Reservation process detail",
    reservationDetailTitle: "Reservation detail",
    processPdfTitle: "Reservation process summary",
    reservationPdfTitle: "Reservation summary",
    opsRecordSummary: "Tripetica operations record summary",
    downloadPdf: "Download PDF",
    opsPdf: "Operations PDF",
    voucherPdf: "Voucher PDF",
    showContact: "Show contact details",
    hideContact: "Hide contact details",
    showPricing: "Show price details",
    hidePricing: "Hide price details",
    contactHidden: "Hidden",
    loadingDetail: "Loading detail…",
    detailError: "Could not load record detail.",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    deleteReservationConfirm: "Are you sure you want to delete this reservation?",
    deleteReservationNo: "No, keep it",
    deleteReservationYes: "Yes, delete",
    deleteReservationError: "Could not delete the reservation. Please try again.",
    cancelEdit: "Cancel",
    saveChanges: "Save changes",
    savingChanges: "Saving…",
    editSaveError: "Could not save changes. Please check the fields.",
    editPrice: "Edit price",
    editPriceTitle: "Edit price",
    recalcOtherCurrencies: "Recalculate other currencies",
    pickupAddress: "Pickup address",
    dropoffAddress: "Drop-off address",
    pickupDate: "Date",
    pickupTime: "Time",
    passengerInfo: "Passenger information",
    noPassengers: "No passenger details have been entered yet.",
    serviceType: "Service type",
    durationHours: "Duration",
    packageCoverage: "Package coverage",
    vehicleCode: "Vehicle code",
    appliedPrice: "Applied price",
    selectedPrice: "Selected price",
    otherCurrencies: "Other currencies",
    alternatePaymentHint: "If the passenger wants to pay in a different currency",
    nationality: "Country / nationality",
    quoteOpening: "Opening fee",
    quoteDistance: "Distance fee",
    quoteLocation: "Region / district fee",
    quoteTime: "Time-of-day fee",
    quoteBase: "Base transfer fee",
    pricingVersion: "Pricing rule version",
    fxBase: "FX base currency",
    fxCaptured: "FX captured at",
    fxTotalEur: "EUR total",
    techDevice: "Device type",
    techOs: "Operating system",
    techBrowser: "Browser",
    techViewport: "Viewport",
    techScreen: "Screen",
    techBrowserLanguage: "Browser language",
    techClientTimezone: "Client time zone",
    statusDraft: "Draft",
    statusCompleted: "Completed",
    statusExpired: "Expired",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    stageVehicleSelection: "Vehicle selection",
    stageCheckout: "Checkout",
    serviceTransfer: "Private Transfer & Taxi",
    serviceHourly: "Hourly Chauffeur Service",
    serviceTour: "Tours & Routes",
    paymentCash: "Cash",
    paymentSbp: "SBP",
    paymentOnlineSbp: "Online",
    paymentProvider: "Payment provider",
    paymentStatus: "Payment status",
    paymentStatusPending: "Pending",
    paymentStatusPaid: "Collected",
    paymentStatusFailed: "Failed",
    refundStatus: "Refund status",
    refundStatusNone: "—",
    refundStatusSubmitted: "Refund requested",
    refundStatusCompleted: "Refund completed",
    refundStatusFailed: "Refund failed",
    refundAmount: "Refund amount",
    refundCurrency: "Refund currency",
    refundRequestedAt: "Refund requested at",
    refundCompletedAt: "Refund completed at",
    refundProviderId: "Turinvoice refund ID",
    refundOverrideNote: "Refund note",
    refundOverrideApplied: "Issued with admin approval outside the normal refund window",
    refundAction: "Issue refund",
    refundActionCashDisabled: "Online refund is not available for cash payments.",
    refundNotCancelledTitle: "Reservation is not cancelled yet",
    refundNotCancelledBody:
      "The reservation must be cancelled before a refund can be issued.",
    refundNotPaidTitle: "Refund unavailable",
    refundNotPaidBody:
      "This reservation has no verified online payment, so a refund cannot be issued.",
    refundAlreadyTitle: "Refund already submitted",
    refundAlreadyBody: "A refund request has already been created for this payment.",
    refundCashTitle: "Online refund unavailable",
    refundCashBody: "Online refund is not available for cash payments.",
    refundConfirmTitle: "Confirm refund",
    refundConfirmBody:
      "This will send a full refund of {amount} to the customer.\n\nAre you sure you want to issue the refund?",
    refundOverrideTitle: "Outside normal refund window",
    refundOverrideBody:
      "This reservation was cancelled outside the normal refund window.\n\nDo you still want to issue a full refund of {amount} to the customer?",
    refundConfirmNo: "No",
    refundConfirmYes: "Yes, issue refund",
    refundOverrideYes: "Yes, refund anyway",
    refundOk: "OK",
    refunding: "Submitting refund…",
    refundError: "Could not submit the refund. Please try again.",
    paymentHistoryTitle: "Payment history",
    paymentHistoryEmpty: "No Turinvoice payment movements for this reservation.",
    paymentHistoryDate: "Date / time",
    paymentHistoryOrderId: "Turinvoice order ID",
    paymentHistoryAmount: "Amount",
    paymentHistoryCurrency: "Currency",
    paymentHistoryStatus: "Status",
    paymentHistoryAction: "Action",
    paymentHistorySummaryTitle: "Summary",
    paymentHistoryReservationTotal: "Current reservation total",
    paymentHistoryGrossPaid: "Total successful collections",
    paymentHistoryCompletedRefunds: "Total completed refunds",
    paymentHistoryNetCollected: "Net collected",
    paymentHistoryRemainingDue: "Amount still due",
    paymentMovementPending: "Pending",
    paymentMovementPaid: "Collected",
    paymentMovementCancelled: "Cancelled",
    paymentMovementFailed: "Failed",
    paymentMovementPartialRefund: "Partially refunded",
    paymentMovementRefunded: "Refunded",
    paymentMovementPendingShort: "Pending",
    paymentMovementPaidShort: "Collected",
    paymentMovementCancelledShort: "Cancelled",
    paymentMovementFailedShort: "Failed",
    paymentMovementPartialRefundShort: "Partial",
    paymentMovementRefundedShort: "Refunded",
    paymentMovementsColumn: "Payment movements",
    paymentMovementsMore: "+{n} more",
    paymentMovementsNone: "—",
    paymentCancelOrder: "Cancel order",
    paymentCancelOrderUnsupported:
      "Cancelling unpaid Turinvoice orders is not supported in the current integration.",
    paymentCancelConfirmTitle: "Cancel order",
    paymentCancelConfirmBody:
      "This pending Turinvoice order will be cancelled. Do you want to continue?",
    paymentCancelConfirmSubmit: "Cancel order",
    paymentCancelConfirmDismiss: "Back",
    paymentCancelSubmitting: "Cancelling…",
    paymentCancelFailed:
      "The order could not be cancelled. Turinvoice rejected the request.",
    paymentRefundAction: "Refund",
    paymentRefundModalTitle: "Refund",
    paymentRefundCollected: "Collected",
    paymentRefundAlready: "Already refunded",
    paymentRefundMax: "Maximum refundable",
    paymentRefundAmount: "Refund amount",
    paymentRefundFull: "Refund full remaining amount",
    paymentRefundSubmit: "Submit refund",
    paymentRefundCancel: "Cancel",
    paymentRefundInvalidAmount: "Enter a valid refund amount.",
    paymentRefundExceedsMax: "Amount cannot exceed the maximum refundable balance.",
    paymentRefundSubmitting: "Submitting refund…",
    paymentRefundFailed: "Could not submit the refund. Please try again.",
    fxRatesProviderLabel: "ExchangeRate-API",
    fxRatesLastFetch: "Last fetch",
    fxRatesNextRefresh: "Next refresh",
    fxRatesTitle: "FX summary (Tripetica last fetch + ExchangeRate-API next update)",
    fxRatesUnavailable: "FX rates unavailable",
    genderFemale: "Female",
    genderMale: "Male",
    localeTr: "Turkish",
    localeEn: "English",
    localeRu: "Russian",
    reservationStatusActive: "Active",
    reservationStatusCancelled: "Cancelled",
    reservationStatusPaymentPending: "Payment pending",
    cancelReservation: "Cancel",
    activateReservation: "Reactivate",
    cancelReservationTitle: "Cancel reservation",
    cancelReservationBody: "Are you sure you want to cancel this reservation?",
    cancelReservationWithinBody:
      "Are you sure you want to cancel this reservation?\n\nIt is still within the normal refund window. After cancelling, you can issue a refund separately if needed.",
    cancelReservationOutsideTitle: "Refund window expired",
    cancelReservationOutsideBody:
      "Less than 6 hours remain before this service, so there is normally no refund entitlement.\n\nDo you still want to cancel the reservation?",
    cancelReservationLateTitle: "Cancel reservation",
    cancelReservationLateBody:
      "6 hours or less remain before this reservation starts. Are you sure you want to cancel it?",
    cancelReservationLateYes: "Yes, cancel",
    cancelReservationYes: "Cancel reservation",
    cancelReservationOutsideYes: "Cancel anyway",
    cancelReservationNo: "Go back",
    cancelReservationError: "Could not cancel the reservation. Please try again.",
    editReservationLateTitle: "Edit reservation",
    editReservationLateBody:
      "6 hours or less remain before this reservation starts. Do you want to continue editing?",
    editReservationLateYes: "Continue editing",
    editReservationLateNo: "Go back",
    activateReservationTitle: "Reactivate reservation",
    activateReservationBody: "Are you sure you want to reactivate this reservation?",
    activateReservationYes: "Yes, reactivate",
    activateReservationNo: "Go back",
    activateReservationError: "Could not reactivate the reservation. Please try again.",
    cancelling: "Cancelling…",
    activating: "Reactivating…",
    pushEnable: "Enable notifications",
    pushEnabled: "Notifications are on",
    pushDisabled: "Notifications are off",
    pushUnsupported: "This device or browser does not support notifications",
    pushIosInstall:
      "On iPhone or iPad, add Tripetica to the Home Screen, open the app, then tap Enable notifications.",
    pushBusy: "Saving…",
    permissionLabels: {
      "reservations.view": "View reservations",
      "reservations.manage": "Manage reservations",
      "records.edit": "Edit records",
      "processes.view": "View reservation processes",
      "processes.delete": "Delete reservation processes",
      "customers.view": "View customers",
      "partners.view": "View partners",
      "partners.manage": "Manage partners",
      "users.view": "View panel users",
      "users.manage": "Manage panel users",
    } satisfies Record<OpsPermission, string>,
  },
  ru: {
    brand: "Tripetica",
    panelName: "Операционная панель Tripetica",
    loginLead: "Доступ только для уполномоченных пользователей",
    email: "Адрес электронной почты",
    password: "Пароль",
    signIn: "Войти",
    signingIn: "Вход…",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
    invalidLogin: "Неверный адрес электронной почты или пароль.",
    throttledLogin: "Слишком много неудачных попыток. Повторите позже.",
    logout: "Выйти",
    language: "Язык",
    menu: "Меню",
    closeMenu: "Закрыть меню",
    reservations: "Бронирования",
    processes: "Процессы бронирования",
    users: "Пользователи панели",
    myAccount: "Мои данные",
    customers: "Клиенты",
    partners: "Партнёры",
    drivers: "Водители",
    vehicles: "Автомобили",
    partnerCode: "Код партнёра",
    partnerName: "Название партнёра",
    primaryPartner: "Основной партнёр",
    emptyPartners: "Партнёров пока нет.",
    partnerSearchPlaceholder: "Код или название партнёра",
    partnerLegalName: "Название / юридическое имя",
    partnerLevel: "Уровень партнёра",
    partnerContact: "Уполномоченное лицо",
    partnerContactFullName: "Имя и фамилия уполномоченного лица",
    partnerPhone: "Телефон",
    partnerEmail: "Эл. почта",
    partnerPriority: "Уровень приоритета партнёра",
    partnerPriorityUnset: "Не выбран",
    partnerPriority1: "1-й уровень",
    partnerPriority2: "2-й уровень",
    partnerPriority3: "3-й уровень",
    pending: "Ожидает одобрения",
    partnerTabJobs: "Заказы",
    partnerTabInfo: "Данные",
    partnerTabDrivers: "Водители",
    partnerTabVehicles: "Автомобили",
    emptyPartnerJobs: "Этот партнёр ещё не принял заказы.",
    jobSearchPlaceholder: "Поиск заказа...",
    emptyJobSearch: "Заказы не найдены.",
    partnerJobCode: "Бронь",
    partnerJobWhen: "Дата и время",
    partnerJobService: "Услуга",
    partnerJobRoute: "Маршрут",
    partnerJobPayout: "Выплата партнёру",
    partnerJobCollect: "С пассажира",
    emptyPartnerDrivers: "У этого партнёра нет зарегистрированных водителей.",
    emptyPartnerVehicles: "У этого партнёра нет зарегистрированных автомобилей.",
    driverSearchPlaceholder: "Поиск водителя...",
    vehicleSearchPlaceholder: "Поиск автомобиля...",
    emptyDriverSearch: "Водители не найдены.",
    emptyVehicleSearch: "Автомобили не найдены.",
    emptyDrivers: "Водителей пока нет.",
    emptyVehicles: "Автомобилей пока нет.",
    linkedPartner: "Партнёр",
    activatePartner: "Активировать",
    deactivatePartner: "Деактивировать",
    activatingPartner: "Активация…",
    deactivatingPartner: "Деактивация…",
    activatePartnerNeedPriority: "Перед активацией выберите и сохраните уровень приоритета.",
    activatePartnerNeedFields: "Перед активацией заполните обязательные данные партнёра.",
    partnerBusinessType: "Тип предприятия",
    partnerIndividual: "Индивидуальное предприятие",
    partnerCompany: "Юридическое лицо",
    partnerAddress: "Адрес",
    partnerCountry: "Страна",
    partnerTaxOffice: "Налоговая инспекция",
    partnerTaxNumber: "Налоговый номер",
    partnerAppliedAt: "Дата заявки",
    partnerUpdatedAt: "Последнее обновление",
    partnerSaved: "Данные партнёра обновлены.",
    partnerSaveFailed: "Не удалось сохранить данные партнёра.",
    primaryPartnerTaken: "Основной партнёр уже назначен.",
    partnerActivateFailed: "Не удалось активировать партнёра.",
    partnerDeactivateFailed: "Не удалось деактивировать партнёра.",
    deletePartner: "Удалить",
    deletingPartner: "Удаление…",
    deletePartnerConfirm: "Вы уверены, что хотите полностью удалить этого партнёра?",
    deletePartnerNo: "Отмена",
    deletePartnerYes: "Да, удалить",
    deletePartnerFailed: "Не удалось удалить партнёра.",
    driverFullName: "Имя и фамилия водителя",
    driverNationalId: "Номер удостоверения личности",
    invalidDriverEmail: "Введите действительный адрес электронной почты.",
    duplicateDriverEmail: "Этот адрес уже используется другим зарегистрированным водителем.",
    driverLanguages: "Языки",
    driverRowIndex: "#",
    languageSearch: "Поиск языка",
    languageNoResults: "Совпадений нет.",
    languageSelected: "Выбранные языки",
    invalidNationalId: "Номер удостоверения личности должен содержать 11 цифр.",
    invalidLanguages: "Выберите хотя бы один язык.",
    invalidDriverName: "Укажите имя и фамилию.",
    invalidPhone: "Введите действительный номер телефона.",
    duplicateNationalId: "Водитель с этим номером уже зарегистрирован.",
    vehiclePlate: "Номер",
    vehicleBrand: "Марка",
    vehicleModel: "Модель",
    vehicleBrandModel: "Марка / модель",
    invalidPlate: "Введите действительный номер.",
    invalidBrandModel: "Введите марку / модель.",
    vehicleColor: "Цвет",
    vehicleFeatures: "Характеристики автомобиля",
    vehicleModelYear: "Год выпуска",
    vehiclePassengers: "Пассажировместимость",
    vehicleLuggage: "Вместимость багажа",
    vehiclePassengersShort: "пассажиров",
    vehicleBagsShort: "чемоданов",
    vehicleCapacity: "Вместимость",
    vehicleClass: "Класс автомобиля",
    vehicleClassHint: "Выберите предполагаемый класс обслуживания Tripetica.",
    vehicleActive: "Активен",
    vehicleInactive: "Неактивен",
    vehiclePending: "Ожидает одобрения",
    vehicleRejected: "Отклонён",
    approveVehicle: "Одобрить",
    rejectVehicle: "Отклонить",
    approvingVehicle: "Одобрение…",
    rejectingVehicle: "Отклонение…",
    duplicatePlate: "Автомобиль с этим номером уже зарегистрирован.",
    invalidVehicleYear: "Выберите действительный год выпуска.",
    searchBrand: "Поиск марки",
    searchModel: "Поиск модели",
    noBrandResults: "Совпадений нет.",
    noModelResults: "Совпадений нет.",
    featureSearch: "Поиск опций",
    featureSelected: "Выбранные опции",
    colorBlack: "Чёрный",
    colorWhite: "Белый",
    colorGray: "Серый",
    colorSilver: "Серебристый",
    colorNavy: "Тёмно-синий",
    colorBlue: "Синий",
    colorRed: "Красный",
    colorBrown: "Коричневый",
    colorBeige: "Бежевый",
    colorOther: "Другой",
    featureAc: "Кондиционер",
    featureWifi: "Wi-Fi",
    featureLeather: "Кожаные сиденья",
    featurePartition: "Перегородка",
    featureStarlight: "Звёздный потолок",
    featureTv: "ТВ / мультимедиа",
    featureFridge: "Холодильник",
    featureUsb: "USB-зарядка",
    featureBabySeat: "Детское кресло",
    featureElectricDoor: "Электропривод дверей",
    featureOther: "Другое",
    driverSaved: "Данные водителя обновлены.",
    driverSaveFailed: "Не удалось сохранить данные водителя.",
    driverActivateFailed: "Не удалось активировать водителя.",
    driverDeactivateFailed: "Не удалось деактивировать водителя.",
    deleteDriverConfirm: "Вы уверены, что хотите удалить этого водителя?",
    deleteDriverFailed: "Не удалось удалить водителя.",
    vehicleSaved: "Данные автомобиля обновлены.",
    vehicleSaveFailed: "Не удалось сохранить данные автомобиля.",
    vehicleActivateFailed: "Не удалось активировать автомобиль.",
    vehicleDeactivateFailed: "Не удалось деактивировать автомобиль.",
    deleteVehicleConfirm: "Вы уверены, что хотите удалить этот автомобиль?",
    deleteVehicleFailed: "Не удалось удалить автомобиль.",
    fleetInUse: "Эта запись не может быть удалена, потому что она ещё используется.",
    passwordTooShort: `Пароль должен содержать не менее ${OPS_MIN_PASSWORD_LENGTH} символов.`,
    passwordMismatch: "Новые пароли не совпадают.",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Повторите новый пароль",
    changePassword: "Сменить пароль",
    savePassword: "Сохранить пароль",
    savingPassword: "Сохранение…",
    passwordChanged: "Пароль обновлён.",
    currentPasswordInvalid: "Неверный текущий пароль.",
    passwordChangeFailed: "Не удалось обновить пароль. Попробуйте ещё раз.",
    fullName: "Имя и фамилия",
    editField: "Изменить",
    invalidEmail: "Введите корректный адрес электронной почты.",
    invalidName: "Укажите имя и фамилию.",
    profileSaved: "Данные обновлены.",
    search: "Поиск",
    filter: "Фильтр",
    refresh: "Обновить",
    refreshing: "Обновление…",
    emptyReservations: "Бронирований пока нет.",
    emptyProcesses: "Процессов бронирования пока нет.",
    createdDateFilter: "Дата создания",
    dateToday: "Сегодня",
    dateYesterday: "Вчера",
    dateLast7: "Последние 7 дней",
    dateMonth: "Этот месяц",
    datePast: "Прошлое",
    dateRange: "Диапазон дат",
    transferDateFilter: "Дата и время бронирования",
    dateTomorrow: "Завтра",
    dateNext7: "Следующие 7 дней",
    dateNextMonth: "Следующий месяц",
    datePastMonth: "Прошлый месяц",
    dateUpcoming: "Предстоящие",
    paymentSbpQr: "QR / СБП",
    dateFrom: "Дата начала",
    dateTo: "Дата окончания",
    clearFilters: "Сбросить фильтры",
    selectedCount: "Выбрано записей: {n}",
    pageSelected: "Выбрано записей на этой странице: {n}.",
    selectAllFiltered: "Выбрать все {n} отфильтрованных записей",
    allFilteredSelected: "Выбраны все {n} отфильтрованных записей.",
    clearSelection: "Снять выделение",
    deleteSelected: "Удалить выбранные",
    deleteModalTitle: "Удалить процессы бронирования",
    deleteModalBody:
      "Вы собираетесь безвозвратно удалить {n} процессов бронирования. Это действие нельзя отменить.",
    deleteMixed:
      "Будет удалено записей: {d}. {p} записей будут сохранены, потому что они преобразованы в реальные бронирования.",
    deleteProtected: "{n} записей нельзя удалить, потому что они преобразованы в реальные бронирования.",
    deleteNothing: "Нет записей, которые можно удалить.",
    deleteFailed: "Не удалось удалить записи. Попробуйте ещё раз.",
    cancel: "Отмена",
    confirmDelete: "Удалить безвозвратно",
    deleting: "Удаление…",
    deleteResult: "Удалено записей: {d}.",
    selectColumn: "Выбор",
    emptyUsers: "Пользователей панели пока нет.",
    emptyCustomers: "Клиентов пока нет.",
    page: "Страница",
    of: "из",
    previous: "Назад",
    next: "Далее",
    back: "Назад",
    details: "Подробнее",
    yes: "Да",
    no: "Нет",
    converted: "Преобразовано в бронирование",
    notConverted: "Не преобразовано",
    all: "Все",
    active: "Активен",
    inactive: "Неактивен",
    status: "Статус",
    role: "Роль",
    owner: "Owner",
    employee: "Сотрудник",
    newUser: "Новый пользователь панели",
    save: "Сохранить",
    saving: "Сохранение…",
    firstName: "Имя",
    lastName: "Фамилия",
    permissions: "Права",
    lastLogin: "Последний вход",
    createdAt: "Создан",
    verification: "Подтверждение",
    verified: "Подтверждён",
    unverified: "Не подтверждён",
    customerSearchPlaceholder: "Имя, эл. почта или телефон",
    reservationHistory: "История бронирований",
    emptyCustomerReservations: "У этого клиента нет бронирований.",
    passwordOptional: "Пароль (заполните, чтобы сменить)",
    emailTaken: "Этот адрес электронной почты уже зарегистрирован.",
    lastOwner: "В системе должен остаться хотя бы один активный Owner.",
    saved: "Сохранено.",
    forbidden: "Недостаточно прав для этого действия.",
    reservationCode: "Код бронирования",
    transferAt: "Дата / время",
    pickup: "Место подачи",
    dropoff: "Место высадки",
    mainPassenger: "Основной пассажир",
    passengerCount: "Число пассажиров",
    passengerLuggageBaby: "Пассажиры / Багаж / Детское кресло",
    vehicle: "Автомобиль",
    assignmentSection: "Партнёр / операционное назначение",
    assignmentPartner: "Партнёр",
    assignmentDriver: "Водитель",
    assignmentVehicle: "Назначенный автомобиль",
    assignmentUnassigned: "—",
    assignmentSelectPartner: "Выберите партнёра",
    assignmentSearchPartner: "Поиск партнёра",
    assignmentEmptyPartners: "Нет подходящих активных партнёров.",
    assignmentClearPartner: "Снять назначение партнёра",
    assignmentRemovePartnerConfirm:
      "Вы уверены, что хотите снять этого партнёра с бронирования?",
    assignmentRemovePartnerNo: "Нет, оставить",
    assignmentRemovePartnerYes: "Да, снять",
    assignmentSelectDriver: "Назначить водителя",
    assignmentSelectVehicle: "Назначить автомобиль",
    assignmentSearchDriver: "Поиск водителя",
    assignmentSearchVehicle: "Поиск автомобиля",
    assignmentEmptyDrivers: "У этого партнёра нет активных водителей.",
    assignmentEmptyVehicles: "У этого партнёра нет активных автомобилей.",
    assignmentClearDriver: "Снять назначение водителя",
    assignmentClearVehicle: "Снять назначение автомобиля",
    assignmentNeedPartner: "Сначала выберите партнёра",
    assignmentFailed: "Не удалось сохранить назначение. Попробуйте ещё раз.",
    assignmentForbidden: "Недостаточно прав для этого действия.",
    assignmentForeignFleet: "Водитель или автомобиль не принадлежит выбранному партнёру.",
    assignmentInactivePartner: "Этот партнёр не активен.",
    assignmentNonTrp: "NON TRP",
    assignmentNote: "Примечание",
    assignmentRegistered: "Зарегистрирован",
    assignmentKind: "Тип записи",
    passengerNotify: "Уведомление пассажира",
    passengerNotifySend: "Отправить данные",
    passengerNotifyResend: "Данные изменились · Отправить снова",
    passengerNotifySent: "Отправлено",
    passengerNotifyNeedVehicle: "Сначала назначьте автомобиль",
    passengerNotifyNeedEmail: "Нет email пассажира",
    passengerNotifyLocked: "Нельзя отправить по отменённому бронированию",
    passengerNotifyTitle: "Отправить данные пассажиру",
    passengerNotifyVehicle: "Отправить данные автомобиля",
    passengerNotifyDriver: "Также отправить данные водителя",
    passengerNotifySubmit: "Отправить пассажиру",
    passengerNotifySending: "Отправка…",
    passengerNotifyFailed: "Не удалось отправить письмо. Попробуйте ещё раз.",
    passengerNotifyNoChange: "Эти данные уже отправлены пассажиру.",
    passengerNotifyNeedDriver: "Водитель не назначен",
    passengerNotifyMissingEmail: "Email пассажира не найден.",
    operationStatus: "Статус операции",
    operationActive: "Активные",
    operationCompleted: "Завершённые",
    operationCancelled: "Отменённые",
    operationAll: "Все",
    driverTask: "Задание водителя",
    driverTaskOpen: "Открыть задание",
    driverTaskCopy: "Копировать ссылку",
    driverTaskCopied: "Ссылка скопирована",
    driverTaskShowPrice: "Показать стоимость",
    driverTaskShowContact: "Показать контакты пассажира",
    operationHistory: "История операции",
    driverTaskPlanned: "Запланировано",
    driverTaskEnRoute: "В пути",
    driverTaskArrived: "На подаче",
    driverTaskPickedUp: "Пассажиры посажены",
    driverTaskCompleted: "Завершено",
    driverTaskHistoryEnRoute: "В пути",
    driverTaskHistoryArrived: "Прибыл на подачу",
    driverTaskHistoryPickedUp: "Пассажиры посажены",
    driverTaskHistoryCompleted: "Пассажиры высажены",
    total: "Итого",
    currency: "Валюта",
    paymentMethod: "Способ оплаты",
    meetAndGreet: "Встреча",
    created: "Создано",
    transferInfo: "Данные услуги",
    customer: "Клиент",
    contactInfo: "Контактные данные",
    pricingInfo: "Данные о стоимости",
    passengers: "Пассажиры",
    payment: "Оплата",
    system: "Система",
    distance: "Расстояние",
    kilometre: "Километры",
    flight: "Номер рейса",
    luggage: "Багаж",
    babySeat: "Детское кресло",
    phone: "Телефон",
    fxSnapshot: "FX snapshot",
    reservationId: "Reservation ID",
    sourceSearch: "source_reservation_search_id",
    confirmedAt: "Подтверждено",
    cancelledAt: "Отменено",
    updatedAt: "Обновлено",
    stage: "Текущий этап",
    locale: "Язык",
    selected: "Выбрано",
    applied: "Применено",
    searchTransfer: "Трансфер / поиск",
    vehiclePrice: "Автомобиль / цена",
    technical: "Технические / аналитика",
    conversion: "Преобразовано в бронирование",
    openProcesses: "Открытые процессы",
    convertedProcesses: "Преобразованные процессы",
    identity: "Документ",
    gender: "Пол",
    primary: "Основной пассажир",
    notes: "Заметки",
    passengerNote: "Заметка пассажира",
    noAccess: "Нет доступа к этому разделу.",
    processDetailTitle: "Детали процесса бронирования",
    reservationDetailTitle: "Детали бронирования",
    processPdfTitle: "Сводка процесса бронирования",
    reservationPdfTitle: "Сводка бронирования",
    opsRecordSummary: "Операционная сводка Tripetica",
    downloadPdf: "Скачать PDF",
    opsPdf: "Операционный PDF",
    voucherPdf: "Ваучер PDF",
    showContact: "Показать контактные данные",
    hideContact: "Скрыть контактные данные",
    showPricing: "Показать данные о стоимости",
    hidePricing: "Скрыть данные о стоимости",
    contactHidden: "Скрыто",
    loadingDetail: "Загрузка деталей…",
    detailError: "Не удалось загрузить детали записи.",
    close: "Закрыть",
    edit: "Редактировать",
    delete: "Удалить",
    deleteReservationConfirm: "Вы уверены, что хотите удалить это бронирование?",
    deleteReservationNo: "Нет, не удалять",
    deleteReservationYes: "Да, удалить",
    deleteReservationError: "Не удалось удалить бронирование. Попробуйте ещё раз.",
    cancelEdit: "Отмена",
    saveChanges: "Сохранить изменения",
    savingChanges: "Сохранение…",
    editSaveError: "Не удалось сохранить изменения. Проверьте поля.",
    editPrice: "Изменить цену",
    editPriceTitle: "Редактирование цены",
    recalcOtherCurrencies: "Пересчитать другие валюты",
    pickupAddress: "Адрес подачи",
    dropoffAddress: "Адрес высадки",
    pickupDate: "Дата",
    pickupTime: "Время",
    passengerInfo: "Данные пассажиров",
    noPassengers: "Данные пассажиров ещё не введены.",
    serviceType: "Тип услуги",
    durationHours: "Продолжительность",
    packageCoverage: "Пакет включает",
    vehicleCode: "Код автомобиля",
    appliedPrice: "Применённая цена",
    selectedPrice: "Выбранная цена",
    otherCurrencies: "Другие валюты",
    alternatePaymentHint: "Если пассажир хочет оплатить в другой валюте",
    nationality: "Страна / гражданство",
    quoteOpening: "Сбор за подачу",
    quoteDistance: "Плата за расстояние",
    quoteLocation: "Региональный / районный сбор",
    quoteTime: "Надбавка за время суток",
    quoteBase: "Базовая стоимость трансфера",
    pricingVersion: "Версия правил тарифа",
    fxBase: "Базовая валюта FX",
    fxCaptured: "FX зафиксирован",
    fxTotalEur: "Итого EUR",
    techDevice: "Тип устройства",
    techOs: "Операционная система",
    techBrowser: "Браузер",
    techViewport: "Viewport",
    techScreen: "Экран",
    techBrowserLanguage: "Язык браузера",
    techClientTimezone: "Часовой пояс клиента",
    statusDraft: "Черновик",
    statusCompleted: "Завершён",
    statusExpired: "Истёк",
    statusConfirmed: "Подтверждено",
    statusCancelled: "Отменено",
    stageVehicleSelection: "Выбор автомобиля",
    stageCheckout: "Оформление",
    serviceTransfer: "Частный трансфер & Такси",
    serviceHourly: "Почасовой автомобиль с водителем",
    serviceTour: "Туры & Маршруты",
    paymentCash: "Наличные",
    paymentSbp: "СБП",
    paymentOnlineSbp: "Онлайн",
    paymentProvider: "Платёжный провайдер",
    paymentStatus: "Статус оплаты",
    paymentStatusPending: "Ожидается",
    paymentStatusPaid: "Получено",
    paymentStatusFailed: "Ошибка",
    refundStatus: "Статус возврата",
    refundStatusNone: "—",
    refundStatusSubmitted: "Возврат запрошен",
    refundStatusCompleted: "Возврат выполнен",
    refundStatusFailed: "Возврат не выполнен",
    refundAmount: "Сумма возврата",
    refundCurrency: "Валюта возврата",
    refundRequestedAt: "Дата запроса возврата",
    refundCompletedAt: "Дата завершения возврата",
    refundProviderId: "ID возврата Turinvoice",
    refundOverrideNote: "Примечание о возврате",
    refundOverrideApplied: "Выполнено с одобрения администратора вне обычного срока возврата",
    refundAction: "Сделать возврат",
    refundActionCashDisabled: "Онлайн-возврат недоступен для оплаты наличными.",
    refundNotCancelledTitle: "Бронирование ещё не отменено",
    refundNotCancelledBody:
      "Чтобы сделать возврат, сначала нужно отменить бронирование.",
    refundNotPaidTitle: "Возврат недоступен",
    refundNotPaidBody:
      "У этого бронирования нет подтверждённой онлайн-оплаты, поэтому возврат невозможен.",
    refundAlreadyTitle: "Возврат уже отправлен",
    refundAlreadyBody: "Запрос на возврат по этому платежу уже создан.",
    refundCashTitle: "Онлайн-возврат недоступен",
    refundCashBody: "Онлайн-возврат недоступен для оплаты наличными.",
    refundConfirmTitle: "Подтвердите возврат",
    refundConfirmBody:
      "Клиенту будет отправлен полный возврат на сумму {amount}.\n\nВы уверены, что хотите выполнить возврат?",
    refundOverrideTitle: "Вне обычного срока возврата",
    refundOverrideBody:
      "Это бронирование было отменено вне обычного срока возврата.\n\nВсё равно отправить клиенту полный возврат на сумму {amount}?",
    refundConfirmNo: "Нет",
    refundConfirmYes: "Да, сделать возврат",
    refundOverrideYes: "Да, всё равно вернуть",
    refundOk: "ОК",
    refunding: "Отправляем возврат…",
    refundError: "Не удалось отправить возврат. Попробуйте ещё раз.",
    paymentHistoryTitle: "История платежей",
    paymentHistoryEmpty: "Для этого бронирования нет платежей Turinvoice.",
    paymentHistoryDate: "Дата / время",
    paymentHistoryOrderId: "ID заказа Turinvoice",
    paymentHistoryAmount: "Сумма",
    paymentHistoryCurrency: "Валюта",
    paymentHistoryStatus: "Статус",
    paymentHistoryAction: "Действие",
    paymentHistorySummaryTitle: "Сводка",
    paymentHistoryReservationTotal: "Текущая сумма бронирования",
    paymentHistoryGrossPaid: "Всего успешно получено",
    paymentHistoryCompletedRefunds: "Всего завершённых возвратов",
    paymentHistoryNetCollected: "Чистая сумма",
    paymentHistoryRemainingDue: "Остаток к оплате",
    paymentMovementPending: "Ожидается",
    paymentMovementPaid: "Получено",
    paymentMovementCancelled: "Отменён",
    paymentMovementFailed: "Ошибка",
    paymentMovementPartialRefund: "Частичный возврат",
    paymentMovementRefunded: "Возвращён",
    paymentMovementPendingShort: "Ожидает",
    paymentMovementPaidShort: "Получено",
    paymentMovementCancelledShort: "Отменён",
    paymentMovementFailedShort: "Ошибка",
    paymentMovementPartialRefundShort: "Частично",
    paymentMovementRefundedShort: "Возврат",
    paymentMovementsColumn: "Платежи",
    paymentMovementsMore: "+{n} ещё",
    paymentMovementsNone: "—",
    paymentCancelOrder: "Отменить заказ",
    paymentCancelOrderUnsupported:
      "Отмена неоплаченных заказов Turinvoice пока не поддерживается в интеграции.",
    paymentCancelConfirmTitle: "Отменить заказ",
    paymentCancelConfirmBody:
      "Этот ожидающий заказ Turinvoice будет отменён. Продолжить?",
    paymentCancelConfirmSubmit: "Отменить заказ",
    paymentCancelConfirmDismiss: "Назад",
    paymentCancelSubmitting: "Отмена…",
    paymentCancelFailed:
      "Не удалось отменить заказ. Turinvoice отклонил запрос.",
    paymentRefundAction: "Вернуть",
    paymentRefundModalTitle: "Возврат",
    paymentRefundCollected: "Получено",
    paymentRefundAlready: "Уже возвращено",
    paymentRefundMax: "Максимум к возврату",
    paymentRefundAmount: "Сумма возврата",
    paymentRefundFull: "Вернуть весь остаток",
    paymentRefundSubmit: "Отправить возврат",
    paymentRefundCancel: "Отмена",
    paymentRefundInvalidAmount: "Введите корректную сумму возврата.",
    paymentRefundExceedsMax: "Сумма не может превышать максимальный остаток к возврату.",
    paymentRefundSubmitting: "Отправка возврата…",
    paymentRefundFailed: "Не удалось отправить возврат. Попробуйте ещё раз.",
    fxRatesProviderLabel: "ExchangeRate-API",
    fxRatesLastFetch: "Последняя загрузка",
    fxRatesNextRefresh: "Следующее обновление",
    fxRatesTitle: "Сводка курсов (последняя загрузка Tripetica + следующее обновление ExchangeRate-API)",
    fxRatesUnavailable: "Курсы недоступны",
    genderFemale: "Женский",
    genderMale: "Мужской",
    localeTr: "Турецкий",
    localeEn: "Английский",
    localeRu: "Русский",
    reservationStatusActive: "Активно",
    reservationStatusCancelled: "Отменено",
    reservationStatusPaymentPending: "Ожидание оплаты",
    cancelReservation: "Отменить",
    activateReservation: "Активировать",
    cancelReservationTitle: "Отменить бронирование",
    cancelReservationBody: "Вы уверены, что хотите отменить это бронирование?",
    cancelReservationWithinBody:
      "Вы уверены, что хотите отменить это бронирование?\n\nОно всё ещё в обычном сроке возврата. После отмены при необходимости можно отдельно сделать возврат.",
    cancelReservationOutsideTitle: "Срок возврата истёк",
    cancelReservationOutsideBody:
      "До начала услуги осталось меньше 6 часов, поэтому обычно право на возврат отсутствует.\n\nВсё равно отменить бронирование?",
    cancelReservationLateTitle: "Отменить бронирование",
    cancelReservationLateBody:
      "До начала бронирования осталось 6 часов или меньше. Вы уверены, что хотите отменить его?",
    cancelReservationLateYes: "Да, отменить",
    cancelReservationYes: "Отменить бронирование",
    cancelReservationOutsideYes: "Всё равно отменить",
    cancelReservationNo: "Назад",
    cancelReservationError: "Не удалось отменить бронирование. Попробуйте ещё раз.",
    editReservationLateTitle: "Изменить бронирование",
    editReservationLateBody:
      "До начала бронирования осталось 6 часов или меньше. Продолжить изменение?",
    editReservationLateYes: "Продолжить изменение",
    editReservationLateNo: "Назад",
    activateReservationTitle: "Активировать бронирование",
    activateReservationBody: "Вы уверены, что хотите снова активировать это бронирование?",
    activateReservationYes: "Да, активировать",
    activateReservationNo: "Назад",
    activateReservationError: "Не удалось активировать бронирование. Попробуйте ещё раз.",
    cancelling: "Отмена…",
    activating: "Активация…",
    pushEnable: "Включить уведомления",
    pushEnabled: "Уведомления включены",
    pushDisabled: "Уведомления выключены",
    pushUnsupported: "Это устройство или браузер не поддерживает уведомления",
    pushIosInstall:
      "На iPhone или iPad добавьте Tripetica на экран Домой, откройте приложение и нажмите «Включить уведомления».",
    pushBusy: "Сохранение…",
    permissionLabels: {
      "reservations.view": "Просмотр бронирований",
      "reservations.manage": "Управление бронированиями",
      "records.edit": "Редактирование записей",
      "processes.view": "Просмотр процессов бронирования",
      "processes.delete": "Удаление процессов бронирования",
      "customers.view": "Просмотр клиентов",
      "partners.view": "Просмотр партнёров",
      "partners.manage": "Управление партнёрами",
      "users.view": "Просмотр пользователей панели",
      "users.manage": "Управление пользователями панели",
    } satisfies Record<OpsPermission, string>,
  },
} as const satisfies Record<PanelLocale, unknown>;

export type OpsCopy = (typeof opsCopy)[PanelLocale];

export function opsCopyFor(locale: Locale): OpsCopy {
  return opsCopy[asPanelLocale(locale)];
}
