export type ReservationListItem = {
  id: string;
  reservationCode: string;
  pickupAt: string | null;
  serviceType: string | null;
  tourCode: string | null;
  durationHours: string | null;
  pickupName: string | null;
  dropoffName: string | null;
  flightCode: string | null;
  customerName: string;
  customerEmail: string | null;
  customerPhone: string | null;
  passengerCount: number | null;
  vehicleLabel: string | null;
  totalPrice: string | null;
  currency: string | null;
  paymentMethod: string | null;
  paymentProvider: string | null;
  paymentStatus: string | null;
  refundStatus: string | null;
  paymentMovements: import("@/lib/ops/payment-history").OpsPaymentMovementCompactLine[];
  meetAndGreet: boolean | null;
  status: string;
  driverTaskStage: import("@/lib/ops/driver-task-stages").DriverTaskStage;
  createdAt: string;
  acceptedPartnerId: string | null;
  acceptedPartnerName: string | null;
  assignmentLocked: boolean;
  acceptedPartnerCode: string | null;
  acceptedPartnerIsPrimary: boolean;
  acceptedPartnerPriorityLevel: number | null;
  driverAssignment: import("@/lib/partner/job-assignment-view").JobDriverAssignmentView;
  vehicleAssignment: import("@/lib/partner/job-assignment-view").JobVehicleAssignmentView;
  lastAssignmentCustomerNotification: import("@/lib/ops/assignment-customer-notification-view").AssignmentCustomerNotificationSent | null;
};
