import { type Locale, type PanelLocale, asPanelLocale } from "@/lib/i18n/config";
import { PARTNER_MIN_PASSWORD_LENGTH } from "@/lib/partner/constants";

export type PartnerCopy = (typeof partnerCopy)[PanelLocale];

export const partnerCopy = {
  tr: {
    brand: "Tripetica",
    panelName: "Tripetica Partner Portal",
    loginLead: "İş ortağı girişi",
    applyPrompt: "Hesabınız yok mu?",
    applyCta: "Partner olarak başvurun",
    registerTitle: "Partner Başvurusu",
    registerLead: "Tripetica operasyon ekibinin onayından sonra hesabınız aktif hale gelecektir.",
    registerSubmit: "Başvuruyu Gönder",
    registering: "Gönderiliyor…",
    registerSuccess:
      "Başvurunuz alınmıştır. Tripetica operasyon ekibinin onayından sonra hesabınız aktif hale gelecektir.",
    backToLogin: "Giriş ekranına dön",
    confirmPasswordPlain: "Şifre tekrar",
    phone: "Telefon",
    contactFirstName: "Yetkili kişi adı",
    contactLastName: "Yetkili kişi soyadı",
    contactFullName: "Yetkili Kişi Adı Soyadı",
    businessType: "İşletme türü",
    businessIndividual: "Şahıs İşletmesi",
    businessCompany: "Tüzel Kişi",
    legalNameIndividual: "İşletme Sahibinin Adı Soyadı",
    legalNameCompany: "Tam Ticari Unvan",
    address: "Adres",
    country: "Ülke",
    taxOffice: "Vergi dairesi",
    taxNumber: "Vergi numarası",
    registerTaxNumber: "Vergi Numarası",
    registerNationalId: "T.C. Kimlik Numarası",
    invalidRegisterNationalId: "Geçerli bir T.C. kimlik numarası girin.",
    countryLockedHint: "Partner başvurusunda ülke Türkiye olarak sabittir.",
    invalidEmail: "Geçerli bir e-posta adresi girin.",
    invalidPhone: "Geçerli bir telefon numarası girin.",
    invalidName: "Unvan / işletme adı gerekli.",
    invalidContact: "Yetkili kişi adı ve soyadı gerekli.",
    invalidBusinessType: "İşletme türünü seçin.",
    invalidAddress: "Adres gerekli.",
    invalidCountry: "Ülke gerekli.",
    invalidTaxOffice: "Vergi dairesi gerekli.",
    invalidTaxNumber: "Geçerli bir vergi numarası girin.",
    duplicateApplication: "Bu e-posta ile aktif veya bekleyen bir partner kaydı zaten var.",
    registerFailed: "Başvuru gönderilemedi. Lütfen tekrar deneyin.",
    email: "E-posta",
    password: "Şifre",
    signIn: "Giriş Yap",
    signingIn: "Giriş yapılıyor…",
    showPassword: "Şifreyi göster",
    hidePassword: "Şifreyi gizle",
    invalidLogin: "E-posta veya şifre hatalı.",
    pendingLogin:
      "Hesabınız henüz aktif edilmemiştir. Destek departmanımızdan bilgi alabilirsiniz.",
    inactiveLogin:
      "Hesabınız şu anda pasif durumdadır. Destek departmanımızdan bilgi alabilirsiniz.",
    whatsappSupport: "WhatsApp",
    throttledLogin: "Çok fazla başarısız deneme. Lütfen daha sonra tekrar deneyin.",
    logout: "Çıkış",
    language: "Dil",
    menu: "Menü",
    closeMenu: "Menüyü kapat",
    jobs: "Açık İşler",
    accepted: "İşlerim",
    drivers: "Sürücülerim",
    vehicles: "Araçlarım",
    profile: "Bilgilerim",
    employerBilling: "İşveren Fatura Bilgileri",
    employerBillingLead:
      "Tripetica tarafından tarafınıza yönlendirilen hizmetlere ilişkin faturalarınızı aşağıdaki bilgilerle düzenleyebilirsiniz.",
    billingLegalName: "Ticari Unvan",
    billingTaxOffice: "Vergi Dairesi",
    billingTaxNumber: "Vergi No",
    billingAddress: "Adres",
    billingEmail: "E-posta",
    billingPhone: "Telefon",
    billingAuthorizedPerson: "Yetkili Kişi",
    billingUnavailable: "İşveren fatura bilgileri şu anda görüntülenemiyor.",
    comingSoon: "Yakında",
    comingSoonLead: "Bu bölüm henüz kullanıma açılmadı.",
    changePassword: "Şifre Değiştir",
    setNewPassword: "Yeni Şifre Belirle",
    setNewPasswordLead: "Devam etmek için yeni bir şifre belirleyin.",
    currentPassword: "Mevcut şifre",
    newPassword: "Yeni şifre",
    confirmPassword: "Yeni şifre tekrar",
    savePassword: "Şifreyi Kaydet",
    savingPassword: "Kaydediliyor…",
    passwordChanged: "Şifreniz güncellendi.",
    passwordTooShort: `Şifre en az ${PARTNER_MIN_PASSWORD_LENGTH} karakter olmalı.`,
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    passwordSameAsOld: "Yeni şifre mevcut şifreden farklı olmalı.",
    currentPasswordInvalid: "Mevcut şifre hatalı.",
    passwordChangeFailed: "Şifre güncellenemedi. Lütfen tekrar deneyin.",
    changePasswordSubmit: "Şifreyi Değiştir",
    saveProfile: "Değişiklikleri Kaydet",
    savingProfile: "Kaydediliyor…",
    profileSaved: "Bilgileriniz güncellendi.",
    profileSaveFailed: "Bilgiler kaydedilemedi. Lütfen tekrar deneyin.",
    securityTitle: "Güvenlik",
    currentEmail: "Mevcut e-posta",
    newEmail: "Yeni e-posta",
    confirmNewEmail: "Yeni e-posta tekrar",
    sendVerificationCode: "Doğrulama Kodu Gönder",
    sendingCode: "Kod gönderiliyor…",
    verificationCode: "Doğrulama Kodu",
    verifyCode: "Kodu Doğrula",
    verifyingCode: "Doğrulanıyor…",
    emailVerified: "E-posta doğrulandı.",
    emailVerifiedBadge: "Doğrulandı",
    emailChanged: "E-posta adresiniz güncellendi.",
    emailConfirmMismatch: "Yeni e-posta adresleri eşleşmiyor.",
    emailUnchanged: "Yeni e-posta mevcut adresten farklı olmalı.",
    verificationCodeSent: "Doğrulama kodu gönderildi.",
    verificationInvalid: "Doğrulama kodu hatalı.",
    verificationExpired: "Doğrulama kodunun süresi doldu.",
    verificationUsed: "Bu doğrulama kodu kullanılamaz.",
    verificationLocked: "Çok fazla hatalı deneme. Yeni kod isteyin.",
    verificationThrottled: "Yeni kod için biraz bekleyin.",
    verificationMailFailed: "Doğrulama e-postası gönderilemedi.",
    verificationFailed: "Doğrulama tamamlanamadı. Lütfen tekrar deneyin.",
    unverifiedEmail: "Başvuruyu göndermeden önce e-posta adresinizi doğrulayın.",
    emailTaken: "Bu e-posta başka bir hesap tarafından kullanılıyor.",
    emailAddress: "E-posta Adresi",
    phoneNumber: "Telefon Numarası",
    editField: "Düzenle",
    cancelEdit: "Vazgeç",
    close: "Kapat",
    closeDriver: "Kapat",
    addDriver: "+ Sürücü Ekle",
    driverEmpty: "Henüz kayıtlı sürücünüz bulunmuyor.",
    driverSearchPlaceholder: "Sürücü ara...",
    driverSearchEmpty: "Eşleşen sürücü bulunamadı.",
    driverAdded: "Sürücü başarıyla eklendi.",
    driverFullName: "Ad Soyad",
    driverNationalId: "T.C. Kimlik Numarası",
    driverEmail: "E-posta",
    invalidDriverEmail: "Geçerli bir e-posta adresi girin.",
    duplicateDriverEmail: "Bu e-posta başka bir kayıtlı şoför tarafından kullanılıyor.",
    driverLanguages: "Konuştuğu Diller",
    driverStatus: "Durum",
    driverDetail: "Detay",
    driverSave: "Kaydet",
    driverSaved: "Sürücü bilgileri güncellendi.",
    driverSaveFailed: "Sürücü kaydedilemedi. Lütfen tekrar deneyin.",
    invalidDriverName: "Ad ve soyadı girin.",
    invalidNationalId: "T.C. Kimlik Numarası 11 haneli olmalıdır.",
    invalidDriverLanguages: "En az bir konuşulan dil seçin.",
    duplicateNationalId: "Bu T.C. Kimlik Numarası ile kayıtlı bir sürücü zaten var.",
    driverActive: "Aktif",
    driverInactive: "Pasif",
    activateDriver: "Aktif Et",
    deactivateDriver: "Pasife Al",
    deleteDriver: "Sil",
    deleteDriverConfirm: "Bu sürücüyü silmek istediğinize emin misiniz?",
    deleteDriverYes: "Evet, sil",
    deleteDriverFailed: "Sürücü silinemedi.",
    languageSearch: "Dil ara",
    languageNoResults: "Eşleşen dil bulunamadı.",
    languageSelected: "Seçili diller",
    addVehicle: "+ Araç Ekle",
    addVehicleTitle: "Araç Ekle",
    vehicleEmpty: "Henüz kayıtlı aracınız bulunmuyor.",
    vehicleSearchPlaceholder: "Araç ara...",
    vehicleSearchEmpty: "Eşleşen araç bulunamadı.",
    vehicleAdded: "Araç başarıyla eklendi.",
    vehiclePlate: "Plaka",
    vehicleBrand: "Marka",
    vehicleModel: "Model",
    vehicleBrandModel: "Marka / Model",
    vehicleModelYear: "Model Yılı",
    vehicleColor: "Renk",
    vehiclePassengers: "Yolcu Kapasitesi",
    vehicleLuggage: "Valiz Kapasitesi",
    vehiclePassengersShort: "yolcu",
    vehicleBagsShort: "valiz",
    vehicleCapacity: "Kapasite",
    vehicleClass: "Araç Sınıfı",
    vehicleClassHint: "Aracınızın Tripetica'daki tahmini hizmet sınıfını seçin.",
    vehicleFeatures: "Araç Özellikleri",
    vehicleStatus: "Durum",
    vehicleDetail: "Detay",
    vehicleSave: "Kaydet",
    vehicleSaved: "Araç bilgileri güncellendi.",
    vehicleSaveFailed: "Araç kaydedilemedi. Lütfen tekrar deneyin.",
    vehicleActive: "Aktif",
    vehicleInactive: "Pasif",
    vehiclePending: "Onay Bekliyor",
    vehicleRejected: "Reddedildi",
    activateVehicle: "Aktif Et",
    deactivateVehicle: "Pasife Al",
    deleteVehicle: "Sil",
    deleteVehicleConfirm: "Bu aracı silmek istediğinize emin misiniz?",
    deleteVehicleYes: "Evet, sil",
    deleteVehicleFailed: "Araç silinemedi.",
    closeVehicle: "Kapat",
    invalidPlate: "Geçerli bir plaka girin.",
    invalidBrand: "Marka seçin.",
    invalidBrandModel: "Marka / model girin.",
    invalidModel: "Model seçin.",
    invalidYear: "Geçerli bir model yılı seçin.",
    invalidColor: "Renk seçin.",
    invalidPassengers: "Yolcu kapasitesi seçin.",
    invalidLuggage: "Valiz kapasitesi seçin.",
    invalidClass: "Araç sınıfı seçin.",
    invalidFeatures: "Özellik için kısa bir açıklama girin.",
    duplicatePlate: "Bu plaka ile kayıtlı bir araç zaten var.",
    vehicleNeedsApproval: "Bu sınıf için operasyon onayı gerekir.",
    searchBrand: "Marka ara",
    searchModel: "Model ara",
    noBrandResults: "Eşleşen marka bulunamadı.",
    noModelResults: "Eşleşen model bulunamadı.",
    featureSearch: "Özellik ara",
    featureSelected: "Seçili özellikler",
    colorBlack: "Siyah",
    colorWhite: "Beyaz",
    colorGray: "Gri",
    colorSilver: "Gümüş",
    colorNavy: "Lacivert",
    colorBlue: "Mavi",
    colorRed: "Kırmızı",
    colorBrown: "Kahverengi",
    colorBeige: "Bej",
    colorOther: "Diğer",
    featureAc: "Klima",
    featureWifi: "Wi-Fi",
    featureLeather: "Deri koltuk",
    featurePartition: "Ara bölme",
    featureStarlight: "Yıldız tavan",
    featureTv: "TV / Multimedya",
    featureFridge: "Buzdolabı",
    featureUsb: "USB şarj",
    featureBabySeat: "Bebek koltuğu",
    featureElectricDoor: "Elektrikli kapı",
    featureOther: "Diğer",
    jobSearchPlaceholder: "İş ara...",
    jobSortByService: "Hizmet Tarihine Göre",
    jobSortByNewest: "En Yeni İşler",
    jobRefresh: "Yenile",
    jobRefreshing: "Yenileniyor…",
    jobSearchEmpty: "Eşleşen açık iş bulunamadı.",
    jobEmpty: "Şu anda görünen açık iş yok.",
    jobAcceptedEmpty: "Henüz kabul ettiğiniz bir iş yok.",
    jobAcceptedSearchEmpty: "Eşleşen iş bulunamadı.",
    jobAcceptedCompletedEmpty: "Tamamlanan iş bulunamadı.",
    jobAcceptedFilterEmpty: "Seçilen filtrelere uyan iş bulunamadı.",
    jobAcceptedOk: "İş kabul edildi.",
    jobDateFilter: "Rezervasyon tarihi ve saati",
    jobOperationStatus: "Operasyon Durumu",
    jobOperationCompleted: "Tamamlananlar",
    jobFilter: "Filtrele",
    jobClearFilters: "Filtreleri Temizle",
    dateToday: "Bugün",
    dateYesterday: "Dün",
    dateTomorrow: "Yarın",
    dateNext7: "Sonraki 7 Gün",
    dateMonth: "Bu Ay",
    dateNextMonth: "Gelecek Ay",
    datePastMonth: "Geçmiş Ay",
    dateUpcoming: "Gelecek",
    datePast: "Geçmiş",
    dateRange: "Tarih Aralığı",
    dateFrom: "Başlangıç tarihi",
    dateTo: "Bitiş tarihi",
    jobDateTime: "Tarih & Saat",
    jobService: "Hizmet",
    jobServiceType: "Hizmet Türü",
    jobTourName: "Tur",
    jobPickup: "Alış Yeri",
    jobDropoff: "Bırakma Yeri",
    jobOccupancy: "Yolcu / Valiz / Bebek",
    jobDuration: "Süre",
    jobPayout: "Size Ödenecek Tutar",
    jobPayoutFull: "Size Ödenecek Tutar",
    jobAccept: "Kabul Et",
    jobDetail: "Detay",
    jobAcceptConfirm: "Bu işi kabul etmek istediğinizden emin misiniz?",
    jobAcceptYes: "Evet, kabul et",
    jobAccepting: "Kabul ediliyor…",
    jobAcceptFailed: "İş kabul edilemedi. Lütfen tekrar deneyin.",
    jobAlreadyTaken: "Bu iş başka bir partner tarafından kabul edildi.",
    jobNotVisible: "Bu iş artık açık işlerinizde görünmüyor.",
    jobClose: "Kapat",
    jobPassengerUnit: "Yolcu",
    jobBagUnit: "Valiz",
    jobBabySeatUnit: "Bebek Koltuğu",
    jobPassengers: "Yolcu Sayısı",
    jobBags: "Valiz Sayısı",
    jobBabySeats: "Bebek Koltuğu Sayısı",
    jobBabySeatRequired: "Bebek Koltuğu",
    jobYes: "Evet",
    jobNote: "Yolcu Notu",
    jobNotePresent: "Not var",
    jobFlightCode: "Uçuş Kodu",
    jobGreeter: "Karşılamacı",
    jobGreeterYes: "Var",
    jobGreeterNo: "Yok",
    jobCollectFromPassenger: "Yolcudan Nakit Tahsilat",
    jobReservationCode: "Rezervasyon Kodu",
    jobPassengerSection: "Yolcu Bilgileri",
    jobPassengerBlock: "Yolcu {n}",
    jobPassengerPrimary: "Ana yolcu",
    jobPassengerName: "Ad Soyad",
    jobPassengerFirstName: "Ad",
    jobPassengerLastName: "Soyad",
    jobPassengerGender: "Cinsiyet",
    jobPassengerGenderMale: "Erkek",
    jobPassengerGenderFemale: "Kadın",
    jobPassengerPhone: "Telefon",
    jobPassengerEmail: "E-posta",
    jobPassengerNationality: "Ülke / Uyruk",
    jobPassengerCountry: "Ülke",
    jobPassengerPassport: "Pasaport Numarası",
    jobPassengerNationalId: "T.C. Kimlik Numarası",
    jobPassengerIdentity: "Pasaport / T.C. Kimlik No",
    jobPassengerId: "Kimlik / Pasaport",
    jobAssignmentSection: "Operasyon Ataması",
    jobAssignDriver: "Şoför Ata",
    jobAssignVehicle: "Araç Ata",
    jobAssignedDriver: "Şoför",
    jobAssignedVehicle: "Araç",
    jobUnassigned: "Atanmadı",
    jobNonTrp: "NON TRP",
    jobSelectDriver: "Şoför seçin",
    jobSelectVehicle: "Araç seçin",
    jobAssignmentNote: "Açıklama / Not",
    jobAssignmentSave: "Kaydet",
    jobAssignmentSaved: "Atama kaydedildi.",
    jobAssignmentFailed: "Atama kaydedilemedi. Lütfen tekrar deneyin.",
    jobAssignmentLocked: "Bu rezervasyon için atama değiştirilemez.",
    jobAssignmentForbidden: "Bu atama bu partner için izinli değil.",
    jobAssignmentNotAccepted: "Bu iş sizin tarafınızdan kabul edilmemiş.",
    jobNoAssignableDrivers: "Aktif kayıtlı şoför bulunmuyor.",
    jobNoAssignableVehicles: "Aktif kayıtlı araç bulunmuyor.",
    jobClearDriver: "Şoför atamasını kaldır",
    jobClearVehicle: "Araç atamasını kaldır",
    jobHours: "{n} Saat",
    pushEnable: "Bildirimleri Aç",
    pushEnabled: "Bildirimler Açık",
    pushDenied: "Bildirim izni reddedildi",
    pushUnsupported: "Cihaz veya tarayıcı bildirimleri desteklemiyor",
    pushIosInstall:
      "iPhone veya iPad’de bildirim almak için Tripetica’yı Ana Ekrana ekleyin, uygulamayı açın ve Bildirimleri Aç’a dokunun.",
    pushBusy: "Kaydediliyor…",
    pushJobTitle: "Yeni İş Var",
  },
  en: {
    brand: "Tripetica",
    panelName: "Tripetica Partner Portal",
    loginLead: "Partner sign-in",
    applyPrompt: "Don't have an account?",
    applyCta: "Apply as a partner",
    registerTitle: "Partner application",
    registerLead: "Your account will become active after Tripetica operations approves it.",
    registerSubmit: "Submit application",
    registering: "Submitting…",
    registerSuccess:
      "Your application has been received. Your account will become active after approval by the Tripetica operations team.",
    backToLogin: "Back to sign in",
    confirmPasswordPlain: "Confirm password",
    phone: "Phone",
    contactFirstName: "Authorized person first name",
    contactLastName: "Authorized person last name",
    contactFullName: "Authorized person full name",
    businessType: "Business type",
    businessIndividual: "Sole proprietorship",
    businessCompany: "Legal entity",
    legalNameIndividual: "Business owner's full name",
    legalNameCompany: "Full legal name",
    address: "Address",
    country: "Country",
    taxOffice: "Tax office",
    taxNumber: "Tax number",
    registerTaxNumber: "Tax number",
    registerNationalId: "National ID number",
    invalidRegisterNationalId: "Enter a valid national ID number.",
    countryLockedHint: "Country is fixed to Turkey on partner applications.",
    invalidEmail: "Enter a valid email address.",
    invalidPhone: "Enter a valid phone number.",
    invalidName: "Business / legal name is required.",
    invalidContact: "Authorized person first and last name are required.",
    invalidBusinessType: "Select a business type.",
    invalidAddress: "Address is required.",
    invalidCountry: "Country is required.",
    invalidTaxOffice: "Tax office is required.",
    invalidTaxNumber: "Enter a valid tax number.",
    duplicateApplication: "An active or pending partner account already exists for this email.",
    registerFailed: "The application could not be submitted. Please try again.",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    invalidLogin: "Invalid email or password.",
    pendingLogin:
      "Your account has not been activated yet. Please contact our support team.",
    inactiveLogin:
      "Your account is currently inactive. Please contact our support team.",
    whatsappSupport: "WhatsApp",
    throttledLogin: "Too many failed attempts. Please try again later.",
    logout: "Log out",
    language: "Language",
    menu: "Menu",
    closeMenu: "Close menu",
    jobs: "Open jobs",
    accepted: "My jobs",
    drivers: "My drivers",
    vehicles: "My vehicles",
    profile: "My details",
    employerBilling: "Employer billing details",
    employerBillingLead:
      "Use the details below when invoicing Tripetica for the jobs assigned to you.",
    billingLegalName: "Legal name",
    billingTaxOffice: "Tax office",
    billingTaxNumber: "Tax number",
    billingAddress: "Address",
    billingEmail: "Email",
    billingPhone: "Phone",
    billingAuthorizedPerson: "Authorized person",
    billingUnavailable: "Employer billing details are unavailable right now.",
    comingSoon: "Coming soon",
    comingSoonLead: "This section is not available yet.",
    changePassword: "Change password",
    setNewPassword: "Set a new password",
    setNewPasswordLead: "Choose a new password to continue.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    savePassword: "Save password",
    savingPassword: "Saving…",
    passwordChanged: "Your password has been updated.",
    passwordTooShort: `Password must be at least ${PARTNER_MIN_PASSWORD_LENGTH} characters.`,
    passwordMismatch: "New passwords do not match.",
    passwordSameAsOld: "New password must be different from the current password.",
    currentPasswordInvalid: "Current password is incorrect.",
    passwordChangeFailed: "Password could not be updated. Please try again.",
    changePasswordSubmit: "Change password",
    saveProfile: "Save changes",
    savingProfile: "Saving…",
    profileSaved: "Your details have been updated.",
    profileSaveFailed: "Your details could not be saved. Please try again.",
    securityTitle: "Security",
    currentEmail: "Current email",
    newEmail: "New email",
    confirmNewEmail: "Confirm new email",
    sendVerificationCode: "Send verification code",
    sendingCode: "Sending code…",
    verificationCode: "Verification code",
    verifyCode: "Verify code",
    verifyingCode: "Verifying…",
    emailVerified: "Email verified.",
    emailVerifiedBadge: "Verified",
    emailChanged: "Your email address has been updated.",
    emailConfirmMismatch: "New email addresses do not match.",
    emailUnchanged: "The new email must be different from the current address.",
    verificationCodeSent: "A verification code has been sent.",
    verificationInvalid: "The verification code is incorrect.",
    verificationExpired: "The verification code has expired.",
    verificationUsed: "This verification code cannot be used.",
    verificationLocked: "Too many incorrect attempts. Request a new code.",
    verificationThrottled: "Please wait before requesting another code.",
    verificationMailFailed: "The verification email could not be sent.",
    verificationFailed: "Verification could not be completed. Please try again.",
    unverifiedEmail: "Verify your email address before submitting the application.",
    emailTaken: "This email is already used by another account.",
    emailAddress: "Email address",
    phoneNumber: "Phone number",
    editField: "Edit",
    cancelEdit: "Cancel",
    close: "Close",
    closeDriver: "Close",
    addDriver: "+ Add driver",
    driverEmpty: "You do not have any registered drivers yet.",
    driverSearchPlaceholder: "Search drivers...",
    driverSearchEmpty: "No matching drivers.",
    driverAdded: "Driver added successfully.",
    driverFullName: "Full name",
    driverNationalId: "National ID number",
    driverEmail: "Email",
    invalidDriverEmail: "Enter a valid email address.",
    duplicateDriverEmail: "This email is already used by another registered driver.",
    driverLanguages: "Spoken languages",
    driverStatus: "Status",
    driverDetail: "Details",
    driverSave: "Save",
    driverSaved: "Driver details have been updated.",
    driverSaveFailed: "The driver could not be saved. Please try again.",
    invalidDriverName: "Enter first and last name.",
    invalidNationalId: "The national ID number must be 11 digits.",
    invalidDriverLanguages: "Select at least one spoken language.",
    duplicateNationalId: "A driver with this national ID is already registered.",
    driverActive: "Active",
    driverInactive: "Inactive",
    activateDriver: "Activate",
    deactivateDriver: "Deactivate",
    deleteDriver: "Delete",
    deleteDriverConfirm: "Are you sure you want to delete this driver?",
    deleteDriverYes: "Yes, delete",
    deleteDriverFailed: "The driver could not be deleted.",
    languageSearch: "Search languages",
    languageNoResults: "No matching languages.",
    languageSelected: "Selected languages",
    addVehicle: "+ Add Vehicle",
    addVehicleTitle: "Add Vehicle",
    vehicleEmpty: "You do not have any vehicles yet.",
    vehicleSearchPlaceholder: "Search vehicles...",
    vehicleSearchEmpty: "No matching vehicles.",
    vehicleAdded: "Vehicle added successfully.",
    vehiclePlate: "Plate",
    vehicleBrand: "Make",
    vehicleModel: "Model",
    vehicleBrandModel: "Make / Model",
    vehicleModelYear: "Model year",
    vehicleColor: "Color",
    vehiclePassengers: "Passenger capacity",
    vehicleLuggage: "Luggage capacity",
    vehiclePassengersShort: "passengers",
    vehicleBagsShort: "bags",
    vehicleCapacity: "Capacity",
    vehicleClass: "Vehicle class",
    vehicleClassHint: "Select your vehicle’s estimated Tripetica service class.",
    vehicleFeatures: "Vehicle features",
    vehicleStatus: "Status",
    vehicleDetail: "Details",
    vehicleSave: "Save",
    vehicleSaved: "Vehicle details were updated.",
    vehicleSaveFailed: "The vehicle could not be saved. Please try again.",
    vehicleActive: "Active",
    vehicleInactive: "Inactive",
    vehiclePending: "Pending approval",
    vehicleRejected: "Rejected",
    activateVehicle: "Activate",
    deactivateVehicle: "Deactivate",
    deleteVehicle: "Delete",
    deleteVehicleConfirm: "Are you sure you want to delete this vehicle?",
    deleteVehicleYes: "Yes, delete",
    deleteVehicleFailed: "The vehicle could not be deleted.",
    closeVehicle: "Close",
    invalidPlate: "Enter a valid plate.",
    invalidBrand: "Select a make.",
    invalidBrandModel: "Enter make / model.",
    invalidModel: "Select a model.",
    invalidYear: "Select a valid model year.",
    invalidColor: "Select a color.",
    invalidPassengers: "Select passenger capacity.",
    invalidLuggage: "Select luggage capacity.",
    invalidClass: "Select a vehicle class.",
    invalidFeatures: "Enter a short description for the extra feature.",
    duplicatePlate: "A vehicle with this plate is already registered.",
    vehicleNeedsApproval: "This class requires operations approval.",
    searchBrand: "Search makes",
    searchModel: "Search models",
    noBrandResults: "No matching makes.",
    noModelResults: "No matching models.",
    featureSearch: "Search features",
    featureSelected: "Selected features",
    colorBlack: "Black",
    colorWhite: "White",
    colorGray: "Gray",
    colorSilver: "Silver",
    colorNavy: "Navy",
    colorBlue: "Blue",
    colorRed: "Red",
    colorBrown: "Brown",
    colorBeige: "Beige",
    colorOther: "Other",
    featureAc: "Air conditioning",
    featureWifi: "Wi-Fi",
    featureLeather: "Leather seats",
    featurePartition: "Partition",
    featureStarlight: "Starlight roof",
    featureTv: "TV / multimedia",
    featureFridge: "Refrigerator",
    featureUsb: "USB charging",
    featureBabySeat: "Baby seat",
    featureElectricDoor: "Power sliding door",
    featureOther: "Other",
    jobSearchPlaceholder: "Search jobs...",
    jobSortByService: "By service time",
    jobSortByNewest: "Newest jobs",
    jobRefresh: "Refresh",
    jobRefreshing: "Refreshing…",
    jobSearchEmpty: "No matching open jobs.",
    jobEmpty: "There are no open jobs visible right now.",
    jobAcceptedEmpty: "You have not accepted any jobs yet.",
    jobAcceptedSearchEmpty: "No matching jobs.",
    jobAcceptedCompletedEmpty: "No completed jobs found.",
    jobAcceptedFilterEmpty: "No jobs match the selected filters.",
    jobAcceptedOk: "Job accepted.",
    jobDateFilter: "Reservation date and time",
    jobOperationStatus: "Operation status",
    jobOperationCompleted: "Completed",
    jobFilter: "Filter",
    jobClearFilters: "Clear filters",
    dateToday: "Today",
    dateYesterday: "Yesterday",
    dateTomorrow: "Tomorrow",
    dateNext7: "Next 7 days",
    dateMonth: "This month",
    dateNextMonth: "Next month",
    datePastMonth: "Previous month",
    dateUpcoming: "Upcoming",
    datePast: "Past",
    dateRange: "Date range",
    dateFrom: "Start date",
    dateTo: "End date",
    jobDateTime: "Date & time",
    jobService: "Service",
    jobServiceType: "Service type",
    jobTourName: "Tour",
    jobPickup: "Pickup",
    jobDropoff: "Drop-off",
    jobOccupancy: "Passengers / Luggage / Baby seats",
    jobDuration: "Duration",
    jobPayout: "Amount payable to you",
    jobPayoutFull: "Amount payable to you",
    jobAccept: "Accept",
    jobDetail: "Details",
    jobAcceptConfirm: "Are you sure you want to accept this job?",
    jobAcceptYes: "Yes, accept",
    jobAccepting: "Accepting…",
    jobAcceptFailed: "The job could not be accepted. Please try again.",
    jobAlreadyTaken: "This job was accepted by another partner.",
    jobNotVisible: "This job is no longer in your open jobs.",
    jobClose: "Close",
    jobPassengerUnit: "Passengers",
    jobBagUnit: "Bags",
    jobBabySeatUnit: "Baby seats",
    jobPassengers: "Passenger count",
    jobBags: "Luggage count",
    jobBabySeats: "Baby seat count",
    jobBabySeatRequired: "Baby seat",
    jobYes: "Yes",
    jobNote: "Passenger note",
    jobNotePresent: "Note added",
    jobFlightCode: "Flight code",
    jobGreeter: "Greeter",
    jobGreeterYes: "Yes",
    jobGreeterNo: "No",
    jobCollectFromPassenger: "Cash to collect from passenger",
    jobReservationCode: "Reservation code",
    jobPassengerSection: "Passenger details",
    jobPassengerBlock: "Passenger {n}",
    jobPassengerPrimary: "Primary passenger",
    jobPassengerName: "Full name",
    jobPassengerFirstName: "First name",
    jobPassengerLastName: "Last name",
    jobPassengerGender: "Gender",
    jobPassengerGenderMale: "Male",
    jobPassengerGenderFemale: "Female",
    jobPassengerPhone: "Phone",
    jobPassengerEmail: "Email",
    jobPassengerNationality: "Country / nationality",
    jobPassengerCountry: "Country",
    jobPassengerPassport: "Passport number",
    jobPassengerNationalId: "Turkish national ID",
    jobPassengerIdentity: "Passport / national ID",
    jobPassengerId: "ID / passport",
    jobAssignmentSection: "Operations assignment",
    jobAssignDriver: "Assign driver",
    jobAssignVehicle: "Assign vehicle",
    jobAssignedDriver: "Driver",
    jobAssignedVehicle: "Vehicle",
    jobUnassigned: "Unassigned",
    jobNonTrp: "NON TRP",
    jobSelectDriver: "Select a driver",
    jobSelectVehicle: "Select a vehicle",
    jobAssignmentNote: "Notes",
    jobAssignmentSave: "Save",
    jobAssignmentSaved: "Assignment saved.",
    jobAssignmentFailed: "Could not save the assignment. Please try again.",
    jobAssignmentLocked: "This reservation can no longer be reassigned.",
    jobAssignmentForbidden: "This assignment is not allowed for this partner.",
    jobAssignmentNotAccepted: "This job was not accepted by your partner account.",
    jobNoAssignableDrivers: "No active registered drivers.",
    jobNoAssignableVehicles: "No active registered vehicles.",
    jobClearDriver: "Remove driver assignment",
    jobClearVehicle: "Remove vehicle assignment",
    jobHours: "{n} hours",
    pushEnable: "Enable notifications",
    pushEnabled: "Notifications are on",
    pushDenied: "Notification permission was denied",
    pushUnsupported: "This device or browser does not support notifications",
    pushIosInstall:
      "On iPhone or iPad, add Tripetica to the Home Screen, open the app, then tap Enable notifications.",
    pushBusy: "Saving…",
    pushJobTitle: "New Job Available",
  },
  ru: {
    brand: "Tripetica",
    panelName: "Tripetica Partner Portal",
    loginLead: "Вход для партнёров",
    applyPrompt: "Нет аккаунта?",
    applyCta: "Подайте заявку как партнёр",
    registerTitle: "Заявка партнёра",
    registerLead: "Аккаунт станет активным после одобрения операционной командой Tripetica.",
    registerSubmit: "Отправить заявку",
    registering: "Отправка…",
    registerSuccess:
      "Ваша заявка получена. Аккаунт станет активным после одобрения операционной командой Tripetica.",
    backToLogin: "Вернуться ко входу",
    confirmPasswordPlain: "Повторите пароль",
    phone: "Телефон",
    contactFirstName: "Имя уполномоченного лица",
    contactLastName: "Фамилия уполномоченного лица",
    contactFullName: "Имя и фамилия уполномоченного лица",
    businessType: "Тип предприятия",
    businessIndividual: "Индивидуальное предприятие",
    businessCompany: "Юридическое лицо",
    legalNameIndividual: "Имя и фамилия владельца",
    legalNameCompany: "Полное юридическое название",
    address: "Адрес",
    country: "Страна",
    taxOffice: "Налоговая инспекция",
    taxNumber: "Налоговый номер",
    registerTaxNumber: "Налоговый номер",
    registerNationalId: "Номер удостоверения личности",
    invalidRegisterNationalId: "Введите действительный номер удостоверения личности.",
    countryLockedHint: "В заявке партнёра страна зафиксирована как Турция.",
    invalidEmail: "Введите действительный адрес электронной почты.",
    invalidPhone: "Введите действительный номер телефона.",
    invalidName: "Укажите название предприятия.",
    invalidContact: "Укажите имя и фамилию уполномоченного лица.",
    invalidBusinessType: "Выберите тип предприятия.",
    invalidAddress: "Адрес обязателен.",
    invalidCountry: "Страна обязательна.",
    invalidTaxOffice: "Налоговая инспекция обязательна.",
    invalidTaxNumber: "Введите действительный налоговый номер.",
    duplicateApplication: "Для этого адреса уже есть активная или ожидающая заявка партнёра.",
    registerFailed: "Не удалось отправить заявку. Попробуйте ещё раз.",
    email: "Эл. почта",
    password: "Пароль",
    signIn: "Войти",
    signingIn: "Вход…",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
    invalidLogin: "Неверный адрес электронной почты или пароль.",
    pendingLogin:
      "Ваш аккаунт ещё не активирован. Обратитесь в службу поддержки.",
    inactiveLogin:
      "Ваш аккаунт сейчас неактивен. Обратитесь в службу поддержки.",
    whatsappSupport: "WhatsApp",
    throttledLogin: "Слишком много неудачных попыток. Повторите позже.",
    logout: "Выйти",
    language: "Язык",
    menu: "Меню",
    closeMenu: "Закрыть меню",
    jobs: "Открытые заказы",
    accepted: "Мои заказы",
    drivers: "Мои водители",
    vehicles: "Мои автомобили",
    profile: "Мои данные",
    employerBilling: "Реквизиты заказчика",
    employerBillingLead:
      "Используйте указанные ниже реквизиты для счетов по заказам, направленным вам компанией Tripetica.",
    billingLegalName: "Юридическое название",
    billingTaxOffice: "Налоговая инспекция",
    billingTaxNumber: "Налоговый номер",
    billingAddress: "Адрес",
    billingEmail: "Эл. почта",
    billingPhone: "Телефон",
    billingAuthorizedPerson: "Уполномоченное лицо",
    billingUnavailable: "Реквизиты заказчика сейчас недоступны.",
    comingSoon: "Скоро",
    comingSoonLead: "Этот раздел пока недоступен.",
    changePassword: "Сменить пароль",
    setNewPassword: "Задать новый пароль",
    setNewPasswordLead: "Чтобы продолжить, задайте новый пароль.",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Повторите новый пароль",
    savePassword: "Сохранить пароль",
    savingPassword: "Сохранение…",
    passwordChanged: "Пароль обновлён.",
    passwordTooShort: `Пароль должен содержать не менее ${PARTNER_MIN_PASSWORD_LENGTH} символов.`,
    passwordMismatch: "Новые пароли не совпадают.",
    passwordSameAsOld: "Новый пароль должен отличаться от текущего.",
    currentPasswordInvalid: "Неверный текущий пароль.",
    passwordChangeFailed: "Не удалось обновить пароль. Попробуйте ещё раз.",
    changePasswordSubmit: "Сменить пароль",
    saveProfile: "Сохранить изменения",
    savingProfile: "Сохранение…",
    profileSaved: "Данные обновлены.",
    profileSaveFailed: "Не удалось сохранить данные. Попробуйте ещё раз.",
    securityTitle: "Безопасность",
    currentEmail: "Текущий email",
    newEmail: "Новый email",
    confirmNewEmail: "Повторите новый email",
    sendVerificationCode: "Отправить код подтверждения",
    sendingCode: "Отправка кода…",
    verificationCode: "Код подтверждения",
    verifyCode: "Подтвердить код",
    verifyingCode: "Проверка…",
    emailVerified: "Email подтверждён.",
    emailVerifiedBadge: "Подтверждено",
    emailChanged: "Адрес электронной почты обновлён.",
    emailConfirmMismatch: "Новые адреса электронной почты не совпадают.",
    emailUnchanged: "Новый адрес должен отличаться от текущего.",
    verificationCodeSent: "Код подтверждения отправлен.",
    verificationInvalid: "Неверный код подтверждения.",
    verificationExpired: "Срок действия кода истёк.",
    verificationUsed: "Этот код подтверждения нельзя использовать.",
    verificationLocked: "Слишком много неверных попыток. Запросите новый код.",
    verificationThrottled: "Подождите, прежде чем запрашивать новый код.",
    verificationMailFailed: "Не удалось отправить письмо с кодом.",
    verificationFailed: "Не удалось завершить подтверждение. Попробуйте ещё раз.",
    unverifiedEmail: "Подтвердите адрес электронной почты перед отправкой заявки.",
    emailTaken: "Этот адрес уже используется другим аккаунтом.",
    emailAddress: "Адрес электронной почты",
    phoneNumber: "Номер телефона",
    editField: "Изменить",
    cancelEdit: "Отмена",
    close: "Закрыть",
    closeDriver: "Закрыть",
    addDriver: "+ Добавить водителя",
    driverEmpty: "У вас пока нет зарегистрированных водителей.",
    driverSearchPlaceholder: "Поиск водителя...",
    driverSearchEmpty: "Водители не найдены.",
    driverAdded: "Водитель успешно добавлен.",
    driverFullName: "Имя и фамилия",
    driverNationalId: "Номер удостоверения личности",
    driverEmail: "Эл. почта",
    invalidDriverEmail: "Введите действительный адрес электронной почты.",
    duplicateDriverEmail: "Этот адрес уже используется другим зарегистрированным водителем.",
    driverLanguages: "Языки",
    driverStatus: "Статус",
    driverDetail: "Подробнее",
    driverSave: "Сохранить",
    driverSaved: "Данные водителя обновлены.",
    driverSaveFailed: "Не удалось сохранить водителя. Попробуйте ещё раз.",
    invalidDriverName: "Укажите имя и фамилию.",
    invalidNationalId: "Номер удостоверения личности должен содержать 11 цифр.",
    invalidDriverLanguages: "Выберите хотя бы один язык.",
    duplicateNationalId: "Водитель с этим номером уже зарегистрирован.",
    driverActive: "Активен",
    driverInactive: "Неактивен",
    activateDriver: "Активировать",
    deactivateDriver: "Деактивировать",
    deleteDriver: "Удалить",
    deleteDriverConfirm: "Вы уверены, что хотите удалить этого водителя?",
    deleteDriverYes: "Да, удалить",
    deleteDriverFailed: "Не удалось удалить водителя.",
    languageSearch: "Поиск языка",
    languageNoResults: "Совпадений нет.",
    languageSelected: "Выбранные языки",
    addVehicle: "+ Добавить автомобиль",
    addVehicleTitle: "Добавить автомобиль",
    vehicleEmpty: "У вас пока нет автомобилей.",
    vehicleSearchPlaceholder: "Поиск автомобиля...",
    vehicleSearchEmpty: "Совпадений нет.",
    vehicleAdded: "Автомобиль успешно добавлен.",
    vehiclePlate: "Номер",
    vehicleBrand: "Марка",
    vehicleModel: "Модель",
    vehicleBrandModel: "Марка / модель",
    vehicleModelYear: "Год выпуска",
    vehicleColor: "Цвет",
    vehiclePassengers: "Пассажировместимость",
    vehicleLuggage: "Вместимость багажа",
    vehiclePassengersShort: "пассажиров",
    vehicleBagsShort: "чемоданов",
    vehicleCapacity: "Вместимость",
    vehicleClass: "Класс автомобиля",
    vehicleClassHint: "Выберите предполагаемый класс обслуживания Tripetica для этого автомобиля.",
    vehicleFeatures: "Оснащение",
    vehicleStatus: "Статус",
    vehicleDetail: "Детали",
    vehicleSave: "Сохранить",
    vehicleSaved: "Данные автомобиля обновлены.",
    vehicleSaveFailed: "Не удалось сохранить автомобиль. Попробуйте ещё раз.",
    vehicleActive: "Активен",
    vehicleInactive: "Неактивен",
    vehiclePending: "Ожидает одобрения",
    vehicleRejected: "Отклонён",
    activateVehicle: "Активировать",
    deactivateVehicle: "Деактивировать",
    deleteVehicle: "Удалить",
    deleteVehicleConfirm: "Вы уверены, что хотите удалить этот автомобиль?",
    deleteVehicleYes: "Да, удалить",
    deleteVehicleFailed: "Не удалось удалить автомобиль.",
    closeVehicle: "Закрыть",
    invalidPlate: "Введите действительный номер.",
    invalidBrand: "Выберите марку.",
    invalidBrandModel: "Введите марку / модель.",
    invalidModel: "Выберите модель.",
    invalidYear: "Выберите действительный год выпуска.",
    invalidColor: "Выберите цвет.",
    invalidPassengers: "Выберите пассажировместимость.",
    invalidLuggage: "Выберите вместимость багажа.",
    invalidClass: "Выберите класс автомобиля.",
    invalidFeatures: "Кратко опишите дополнительную опцию.",
    duplicatePlate: "Автомобиль с этим номером уже зарегистрирован.",
    vehicleNeedsApproval: "Этот класс требует одобрения операторов.",
    searchBrand: "Поиск марки",
    searchModel: "Поиск модели",
    noBrandResults: "Совпадений нет.",
    noModelResults: "Совпадений нет.",
    featureSearch: "Поиск опций",
    featureSelected: "Выбранные опции",
    colorBlack: "Чёрный",
    colorWhite: "Белый",
    colorGray: "Серый",
    colorSilver: "Серебристый",
    colorNavy: "Тёмно-синий",
    colorBlue: "Синий",
    colorRed: "Красный",
    colorBrown: "Коричневый",
    colorBeige: "Бежевый",
    colorOther: "Другой",
    featureAc: "Кондиционер",
    featureWifi: "Wi-Fi",
    featureLeather: "Кожаные сиденья",
    featurePartition: "Перегородка",
    featureStarlight: "Звёздный потолок",
    featureTv: "ТВ / мультимедиа",
    featureFridge: "Холодильник",
    featureUsb: "USB-зарядка",
    featureBabySeat: "Детское кресло",
    featureElectricDoor: "Электропривод дверей",
    featureOther: "Другое",
    jobSearchPlaceholder: "Поиск заказа...",
    jobSortByService: "По времени услуги",
    jobSortByNewest: "Новые заказы",
    jobRefresh: "Обновить",
    jobRefreshing: "Обновление…",
    jobSearchEmpty: "Подходящих открытых заказов нет.",
    jobEmpty: "Сейчас нет видимых открытых заказов.",
    jobAcceptedEmpty: "Вы ещё не приняли ни одного заказа.",
    jobAcceptedSearchEmpty: "Совпадений нет.",
    jobAcceptedCompletedEmpty: "Завершённых заказов нет.",
    jobAcceptedFilterEmpty: "Нет заказов, соответствующих выбранным фильтрам.",
    jobAcceptedOk: "Заказ принят.",
    jobDateFilter: "Дата и время бронирования",
    jobOperationStatus: "Статус операции",
    jobOperationCompleted: "Завершённые",
    jobFilter: "Фильтр",
    jobClearFilters: "Сбросить фильтры",
    dateToday: "Сегодня",
    dateYesterday: "Вчера",
    dateTomorrow: "Завтра",
    dateNext7: "Следующие 7 дней",
    dateMonth: "Этот месяц",
    dateNextMonth: "Следующий месяц",
    datePastMonth: "Прошлый месяц",
    dateUpcoming: "Предстоящие",
    datePast: "Прошлое",
    dateRange: "Диапазон дат",
    dateFrom: "Дата начала",
    dateTo: "Дата окончания",
    jobDateTime: "Дата и время",
    jobService: "Услуга",
    jobServiceType: "Тип услуги",
    jobTourName: "Тур",
    jobPickup: "Место посадки",
    jobDropoff: "Место высадки",
    jobOccupancy: "Пассажиры / Багаж / Детское кресло",
    jobDuration: "Длительность",
    jobPayout: "Сумма к выплате вам",
    jobPayoutFull: "Сумма к выплате вам",
    jobAccept: "Принять",
    jobDetail: "Детали",
    jobAcceptConfirm: "Вы уверены, что хотите принять этот заказ?",
    jobAcceptYes: "Да, принять",
    jobAccepting: "Принятие…",
    jobAcceptFailed: "Не удалось принять заказ. Попробуйте ещё раз.",
    jobAlreadyTaken: "Этот заказ уже принял другой партнёр.",
    jobNotVisible: "Этого заказа больше нет в ваших открытых заказах.",
    jobClose: "Закрыть",
    jobPassengerUnit: "пассажиров",
    jobBagUnit: "чемоданов",
    jobBabySeatUnit: "детских кресел",
    jobPassengers: "Количество пассажиров",
    jobBags: "Количество багажа",
    jobBabySeats: "Количество детских кресел",
    jobBabySeatRequired: "Детское кресло",
    jobYes: "Да",
    jobNote: "Заметка пассажира",
    jobNotePresent: "Есть заметка",
    jobFlightCode: "Код рейса",
    jobGreeter: "Встречающий",
    jobGreeterYes: "Да",
    jobGreeterNo: "Нет",
    jobCollectFromPassenger: "Наличные с пассажира",
    jobReservationCode: "Код бронирования",
    jobPassengerSection: "Данные пассажиров",
    jobPassengerBlock: "Пассажир {n}",
    jobPassengerPrimary: "Основной пассажир",
    jobPassengerName: "Имя и фамилия",
    jobPassengerFirstName: "Имя",
    jobPassengerLastName: "Фамилия",
    jobPassengerGender: "Пол",
    jobPassengerGenderMale: "Мужской",
    jobPassengerGenderFemale: "Женский",
    jobPassengerPhone: "Телефон",
    jobPassengerEmail: "Эл. почта",
    jobPassengerNationality: "Страна / гражданство",
    jobPassengerCountry: "Страна",
    jobPassengerPassport: "Номер паспорта",
    jobPassengerNationalId: "Турецкий идентификационный номер",
    jobPassengerIdentity: "Паспорт / удостоверение",
    jobPassengerId: "Документ / паспорт",
    jobAssignmentSection: "Операционное назначение",
    jobAssignDriver: "Назначить водителя",
    jobAssignVehicle: "Назначить автомобиль",
    jobAssignedDriver: "Водитель",
    jobAssignedVehicle: "Автомобиль",
    jobUnassigned: "Не назначен",
    jobNonTrp: "NON TRP",
    jobSelectDriver: "Выберите водителя",
    jobSelectVehicle: "Выберите автомобиль",
    jobAssignmentNote: "Примечание",
    jobAssignmentSave: "Сохранить",
    jobAssignmentSaved: "Назначение сохранено.",
    jobAssignmentFailed: "Не удалось сохранить назначение. Попробуйте ещё раз.",
    jobAssignmentLocked: "Это бронирование больше нельзя переназначить.",
    jobAssignmentForbidden: "Это назначение недоступно для данного партнёра.",
    jobAssignmentNotAccepted: "Эта заявка не принята вашим партнёрским аккаунтом.",
    jobNoAssignableDrivers: "Нет активных зарегистрированных водителей.",
    jobNoAssignableVehicles: "Нет активных зарегистрированных автомобилей.",
    jobClearDriver: "Снять назначение водителя",
    jobClearVehicle: "Снять назначение автомобиля",
    jobHours: "{n} ч",
    pushEnable: "Включить уведомления",
    pushEnabled: "Уведомления включены",
    pushDenied: "Разрешение на уведомления отклонено",
    pushUnsupported: "Это устройство или браузер не поддерживает уведомления",
    pushIosInstall:
      "На iPhone или iPad добавьте Tripetica на домашний экран, откройте приложение и нажмите «Включить уведомления».",
    pushBusy: "Сохранение…",
    pushJobTitle: "Новый заказ",
  },
} as const satisfies Record<PanelLocale, unknown>;

export function partnerCopyFor(locale: Locale): PartnerCopy {
  return partnerCopy[asPanelLocale(locale)];
}
