export const driverPortalCopy = {
  brand: "TRIPETICA",
  loginTitle: "ŞOFÖR GİRİŞİ",
  jobsTitle: "ŞOFÖR PORTALI",
  email: "E-posta",
  sendCode: "Kod Gönder",
  sendingCode: "Kod gönderiliyor…",
  code: "Doğrulama Kodu",
  signIn: "Giriş Yap",
  signingIn: "Giriş yapılıyor…",
  logout: "Çıkış",
  back: "Kapat",
  jobsNav: "İşlerim",
  upcoming: "Yaklaşan İşler",
  completed: "Tamamlanan İşler",
  detail: "Detay",
  emptyJobs: "Size atanmış iş bulunmuyor.",
  statusPrefix: "Durum",
  invalidEmail: "Geçerli bir e-posta adresi girin.",
  notFound: "Sistemde bu e-posta adresiyle kayıtlı bir şoför bulunamadı.",
  throttled: "Yeni kod için biraz bekleyin.",
  mailFailed: "Kod gönderilemedi. Lütfen tekrar deneyin.",
  sendFailed: "Kod gönderilemedi. Lütfen tekrar deneyin.",
  invalidCode: "Doğrulama kodu hatalı.",
  expiredCode: "Doğrulama kodunun süresi doldu. Yeni kod isteyin.",
  usedCode: "Bu doğrulama kodu kullanılamaz. Yeni kod isteyin.",
  lockedCode: "Çok fazla hatalı deneme. Yeni kod isteyin.",
  verifyFailed: "Giriş yapılamadı. Lütfen tekrar deneyin.",
} as const;
