/** Static ISO 3166-1 catalog. Generated from CLDR names (i18n-iso-countries) and E.164 dial codes (annexare/Countries). */
export type CountryNames = {
  tr: string;
  en: string;
  ru: string;
  ar: string;
};

export type CountryRecord = {
  iso2: string;
  dialCode: string;
  names: CountryNames;
  aliases?: Partial<Record<keyof CountryNames, readonly string[]>>;
};

export const COUNTRY_RECORDS: readonly CountryRecord[] = [
  { iso2: "AD", dialCode: "376", names: { ar: "أندورا", tr: "Andorra", en: "Andorra", ru: "Андорра" } },
  { iso2: "AE", dialCode: "971", names: { ar: "الإمارات العربية المتحدة", tr: "Birleşik Arap Emirlikleri", en: "United Arab Emirates", ru: "ОАЭ" }, aliases: { tr: [], en: ["UAE"], ru: [] } },
  { iso2: "AF", dialCode: "93", names: { ar: "أفغانستان", tr: "Afganistan", en: "Afghanistan", ru: "Афганистан" } },
  { iso2: "AG", dialCode: "1268", names: { ar: "أنتيغوا وبربودا", tr: "Antigua ve Barbuda", en: "Antigua and Barbuda", ru: "Антигуа и Барбуда" } },
  { iso2: "AI", dialCode: "1264", names: { ar: "أنغويلا", tr: "Anguilla", en: "Anguilla", ru: "Ангилья" } },
  { iso2: "AL", dialCode: "355", names: { ar: "ألبانيا", tr: "Arnavutluk", en: "Albania", ru: "Албания" } },
  { iso2: "AM", dialCode: "374", names: { ar: "أرمينيا", tr: "Ermenistan", en: "Armenia", ru: "Армения" } },
  { iso2: "AO", dialCode: "244", names: { ar: "أنغولا", tr: "Angola", en: "Angola", ru: "Ангола" } },
  { iso2: "AQ", dialCode: "672", names: { ar: "أنتاركتيكا", tr: "Antarktika", en: "Antarctica", ru: "Антарктида" } },
  { iso2: "AR", dialCode: "54", names: { ar: "الأرجنتين", tr: "Arjantin", en: "Argentina", ru: "Аргентина" } },
  { iso2: "AS", dialCode: "1684", names: { ar: "ساموا الأمريكية", tr: "Amerikan Samoası", en: "American Samoa", ru: "Американское Самоа" } },
  { iso2: "AT", dialCode: "43", names: { ar: "النمسا", tr: "Avusturya", en: "Austria", ru: "Австрия" } },
  { iso2: "AU", dialCode: "61", names: { ar: "أستراليا", tr: "Avustralya", en: "Australia", ru: "Австралия" } },
  { iso2: "AW", dialCode: "297", names: { ar: "أروبا", tr: "Aruba", en: "Aruba", ru: "Аруба" } },
  { iso2: "AX", dialCode: "358", names: { ar: "جزر آلاند", tr: "Åland Adaları", en: "Åland Islands", ru: "Аландские острова" }, aliases: { tr: [], en: ["Aland", "Aland Islands"], ru: [] } },
  { iso2: "AZ", dialCode: "994", names: { ar: "أذربيجان", tr: "Azerbaycan", en: "Azerbaijan", ru: "Азербайджан" } },
  { iso2: "BA", dialCode: "387", names: { ar: "البوسنة والهرسك", tr: "Bosna Hersek", en: "Bosnia and Herzegovina", ru: "Босния и Герцеговина" } },
  { iso2: "BB", dialCode: "1246", names: { ar: "بربادوس", tr: "Barbados", en: "Barbados", ru: "Барбадос" } },
  { iso2: "BD", dialCode: "880", names: { ar: "بنغلاديش", tr: "Bangladeş", en: "Bangladesh", ru: "Бангладеш" } },
  { iso2: "BE", dialCode: "32", names: { ar: "بلجيكا", tr: "Belçika", en: "Belgium", ru: "Бельгия" } },
  { iso2: "BF", dialCode: "226", names: { ar: "بوركينا فاسو", tr: "Burkina Faso", en: "Burkina Faso", ru: "Буркина-Фасо" } },
  { iso2: "BG", dialCode: "359", names: { ar: "بلغاريا", tr: "Bulgaristan", en: "Bulgaria", ru: "Болгария" } },
  { iso2: "BH", dialCode: "973", names: { ar: "البحرين", tr: "Bahreyn", en: "Bahrain", ru: "Бахрейн" } },
  { iso2: "BI", dialCode: "257", names: { ar: "بوروندي", tr: "Burundi", en: "Burundi", ru: "Бурунди" } },
  { iso2: "BJ", dialCode: "229", names: { ar: "بنين", tr: "Benin", en: "Benin", ru: "Бенин" } },
  { iso2: "BL", dialCode: "590", names: { ar: "سان بارتليمي", tr: "Saint Barthelemy", en: "Saint Barthélemy", ru: "Сен-Бартелеми" }, aliases: { tr: [], en: ["Saint Barthelemy"], ru: [] } },
  { iso2: "BM", dialCode: "1441", names: { ar: "برمودا", tr: "Bermuda", en: "Bermuda", ru: "Бермуды" } },
  { iso2: "BN", dialCode: "673", names: { ar: "بروناي", tr: "Brunei", en: "Brunei Darussalam", ru: "Бруней" }, aliases: { tr: [], en: ["Brunei"], ru: [] } },
  { iso2: "BO", dialCode: "591", names: { ar: "بوليفيا", tr: "Bolivya", en: "Bolivia", ru: "Боливия" } },
  { iso2: "BQ", dialCode: "5997", names: { ar: "هولندا الكاريبية", tr: "Karayip Hollanda", en: "Bonaire, Sint Eustatius and Saba", ru: "Бонэйр, Синт-Эстатиус и Саба" }, aliases: { tr: [], en: ["Bonaire"], ru: [] } },
  { iso2: "BR", dialCode: "55", names: { ar: "البرازيل", tr: "Brezilya", en: "Brazil", ru: "Бразилия" } },
  { iso2: "BS", dialCode: "1242", names: { ar: "جزر البهاما", tr: "Bahamalar", en: "Bahamas", ru: "Багамы" } },
  { iso2: "BT", dialCode: "975", names: { ar: "بوتان", tr: "Butan", en: "Bhutan", ru: "Бутан" } },
  { iso2: "BV", dialCode: "47", names: { ar: "جزيرة بوفيه", tr: "Bouvet Adası", en: "Bouvet Island", ru: "Остров Буве" } },
  { iso2: "BW", dialCode: "267", names: { ar: "بوتسوانا", tr: "Botsvana", en: "Botswana", ru: "Ботсвана" } },
  { iso2: "BY", dialCode: "375", names: { ar: "بيلاروس", tr: "Belarus", en: "Belarus", ru: "Беларусь" }, aliases: { tr: ["Beyaz Rusya"], en: [], ru: [] } },
  { iso2: "BZ", dialCode: "501", names: { ar: "بليز", tr: "Belize", en: "Belize", ru: "Белиз" } },
  { iso2: "CA", dialCode: "1", names: { ar: "كندا", tr: "Kanada", en: "Canada", ru: "Канада" } },
  { iso2: "CC", dialCode: "61", names: { ar: "جزر كوكوس (كيلينغ)", tr: "Cocos (Keeling) Adaları", en: "Cocos (Keeling) Islands", ru: "Кокосовые острова" } },
  { iso2: "CD", dialCode: "243", names: { ar: "الكونغو - كينشاسا", tr: "Kongo Demokratik Cumhuriyeti", en: "DR Congo", ru: "ДР Конго" }, aliases: { tr: ["Kongo - Kinşasa"], en: ["Congo", "Democratic Republic of the Congo"], ru: ["Демократическая Республика Конго"] } },
  { iso2: "CF", dialCode: "236", names: { ar: "جمهورية أفريقيا الوسطى", tr: "Orta Afrika Cumhuriyeti", en: "Central African Republic", ru: "ЦАР" } },
  { iso2: "CG", dialCode: "242", names: { ar: "الكونغو - برازافيل", tr: "Kongo Cumhuriyeti", en: "Republic of the Congo", ru: "Республика Конго" }, aliases: { tr: ["Kongo - Brazavil"], en: ["Congo"], ru: [] } },
  { iso2: "CH", dialCode: "41", names: { ar: "سويسرا", tr: "İsviçre", en: "Switzerland", ru: "Швейцария" } },
  { iso2: "CI", dialCode: "225", names: { ar: "ساحل العاج", tr: "Fildişi Sahili", en: "Côte d’Ivoire", ru: "Кот-д’Ивуар" }, aliases: { tr: [], en: ["Cote d'Ivoire", "Côte d'Ivoire", "Ivory Coast"], ru: [] } },
  { iso2: "CK", dialCode: "682", names: { ar: "جزر كوك", tr: "Cook Adaları", en: "Cook Islands", ru: "Острова Кука" } },
  { iso2: "CL", dialCode: "56", names: { ar: "تشيلي", tr: "Şili", en: "Chile", ru: "Чили" } },
  { iso2: "CM", dialCode: "237", names: { ar: "الكاميرون", tr: "Kamerun", en: "Cameroon", ru: "Камерун" } },
  { iso2: "CN", dialCode: "86", names: { ar: "الصين", tr: "Çin", en: "China", ru: "Китай" }, aliases: { tr: [], en: ["People's Republic of China"], ru: ["КНР (Китайская Народная Республика)"] } },
  { iso2: "CO", dialCode: "57", names: { ar: "كولومبيا", tr: "Kolombiya", en: "Colombia", ru: "Колумбия" } },
  { iso2: "CR", dialCode: "506", names: { ar: "كوستاريكا", tr: "Kosta Rika", en: "Costa Rica", ru: "Коста-Рика" } },
  { iso2: "CU", dialCode: "53", names: { ar: "كوبا", tr: "Küba", en: "Cuba", ru: "Куба" } },
  { iso2: "CV", dialCode: "238", names: { ar: "الرأس الأخضر", tr: "Cape Verde", en: "Cape Verde", ru: "Кабо-Верде" }, aliases: { tr: [], en: ["Cabo Verde"], ru: [] } },
  { iso2: "CW", dialCode: "5999", names: { ar: "كوراساو", tr: "Curaçao", en: "Curaçao", ru: "Кюрасао" }, aliases: { tr: [], en: ["Curacao"], ru: [] } },
  { iso2: "CX", dialCode: "61", names: { ar: "جزيرة كريسماس", tr: "Christmas Adası", en: "Christmas Island", ru: "Остров Рождества" } },
  { iso2: "CY", dialCode: "357", names: { ar: "قبرص", tr: "Güney Kıbrıs Rum Kesimi", en: "Cyprus", ru: "Кипр" } },
  { iso2: "CZ", dialCode: "420", names: { ar: "التشيك", tr: "Çekya", en: "Czechia", ru: "Чехия" }, aliases: { tr: ["Çek Cumhuriyeti"], en: ["Czech Republic"], ru: [] } },
  { iso2: "DE", dialCode: "49", names: { ar: "ألمانيا", tr: "Almanya", en: "Germany", ru: "Германия" } },
  { iso2: "DJ", dialCode: "253", names: { ar: "جيبوتي", tr: "Cibuti", en: "Djibouti", ru: "Джибути" } },
  { iso2: "DK", dialCode: "45", names: { ar: "الدانمرك", tr: "Danimarka", en: "Denmark", ru: "Дания" } },
  { iso2: "DM", dialCode: "1767", names: { ar: "دومينيكا", tr: "Dominika", en: "Dominica", ru: "Доминика" } },
  { iso2: "DO", dialCode: "1809", names: { ar: "جمهورية الدومينيكان", tr: "Dominik Cumhuriyeti", en: "Dominican Republic", ru: "Доминиканская Республика" } },
  { iso2: "DZ", dialCode: "213", names: { ar: "الجزائر", tr: "Cezayir", en: "Algeria", ru: "Алжир" } },
  { iso2: "EC", dialCode: "593", names: { ar: "الإكوادور", tr: "Ekvador", en: "Ecuador", ru: "Эквадор" } },
  { iso2: "EE", dialCode: "372", names: { ar: "إستونيا", tr: "Estonya", en: "Estonia", ru: "Эстония" } },
  { iso2: "EG", dialCode: "20", names: { ar: "مصر", tr: "Mısır", en: "Egypt", ru: "Египет" } },
  { iso2: "EH", dialCode: "212", names: { ar: "الصحراء الغربية", tr: "Batı Sahara", en: "Western Sahara", ru: "САДР" } },
  { iso2: "ER", dialCode: "291", names: { ar: "إريتريا", tr: "Eritre", en: "Eritrea", ru: "Эритрея" } },
  { iso2: "ES", dialCode: "34", names: { ar: "إسبانيا", tr: "İspanya", en: "Spain", ru: "Испания" } },
  { iso2: "ET", dialCode: "251", names: { ar: "إثيوبيا", tr: "Etiyopya", en: "Ethiopia", ru: "Эфиопия" } },
  { iso2: "FI", dialCode: "358", names: { ar: "فنلندا", tr: "Finlandiya", en: "Finland", ru: "Финляндия" } },
  { iso2: "FJ", dialCode: "679", names: { ar: "فيجي", tr: "Fiji", en: "Fiji", ru: "Фиджи" } },
  { iso2: "FK", dialCode: "500", names: { ar: "جزر فوكلاند", tr: "Falkland Adaları", en: "Falkland Islands (Malvinas)", ru: "Фолклендские острова" }, aliases: { tr: [], en: ["Falkland Islands"], ru: [] } },
  { iso2: "FM", dialCode: "691", names: { ar: "ميكرونيزيا", tr: "Mikronezya", en: "Micronesia, Federated States of", ru: "Микронезия" }, aliases: { tr: [], en: ["Micronesia"], ru: [] } },
  { iso2: "FO", dialCode: "298", names: { ar: "جزر فارو", tr: "Faroe Adaları", en: "Faroe Islands", ru: "Фареры" } },
  { iso2: "FR", dialCode: "33", names: { ar: "فرنسا", tr: "Fransa", en: "France", ru: "Франция" } },
  { iso2: "GA", dialCode: "241", names: { ar: "الغابون", tr: "Gabon", en: "Gabon", ru: "Габон" } },
  { iso2: "GB", dialCode: "44", names: { ar: "المملكة المتحدة", tr: "Birleşik Krallık", en: "United Kingdom", ru: "Великобритания" }, aliases: { tr: [], en: ["Great Britain", "UK"], ru: [] } },
  { iso2: "GD", dialCode: "1473", names: { ar: "غرينادا", tr: "Grenada", en: "Grenada", ru: "Гренада" } },
  { iso2: "GE", dialCode: "995", names: { ar: "جورجيا", tr: "Gürcistan", en: "Georgia", ru: "Грузия" } },
  { iso2: "GF", dialCode: "594", names: { ar: "غويانا الفرنسية", tr: "Fransız Guyanası", en: "French Guiana", ru: "Гвиана" } },
  { iso2: "GG", dialCode: "44", names: { ar: "غيرنزي", tr: "Guernsey", en: "Guernsey", ru: "Гернси" } },
  { iso2: "GH", dialCode: "233", names: { ar: "غانا", tr: "Gana", en: "Ghana", ru: "Гана" } },
  { iso2: "GI", dialCode: "350", names: { ar: "جبل طارق", tr: "Cebelitarık", en: "Gibraltar", ru: "Гибралтар" } },
  { iso2: "GL", dialCode: "299", names: { ar: "غرينلاند", tr: "Grönland", en: "Greenland", ru: "Гренландия" } },
  { iso2: "GM", dialCode: "220", names: { ar: "غامبيا", tr: "Gambiya", en: "Gambia", ru: "Гамбия" }, aliases: { tr: [], en: ["Republic of The Gambia", "The Gambia"], ru: [] } },
  { iso2: "GN", dialCode: "224", names: { ar: "غينيا", tr: "Gine", en: "Guinea", ru: "Гвинея" } },
  { iso2: "GP", dialCode: "590", names: { ar: "غوادلوب", tr: "Guadalupe", en: "Guadeloupe", ru: "Гваделупа" } },
  { iso2: "GQ", dialCode: "240", names: { ar: "غينيا الاستوائية", tr: "Ekvator Ginesi", en: "Equatorial Guinea", ru: "Экваториальная Гвинея" } },
  { iso2: "GR", dialCode: "30", names: { ar: "اليونان", tr: "Yunanistan", en: "Greece", ru: "Греция" } },
  { iso2: "GS", dialCode: "500", names: { ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", tr: "Güney Georgia ve Güney Sandwich Adaları", en: "South Georgia and the South Sandwich Islands", ru: "Южная Георгия и Южные Сандвичевы Острова" } },
  { iso2: "GT", dialCode: "502", names: { ar: "غواتيمالا", tr: "Guatemala", en: "Guatemala", ru: "Гватемала" } },
  { iso2: "GU", dialCode: "1671", names: { ar: "غوام", tr: "Guam", en: "Guam", ru: "Гуам" } },
  { iso2: "GW", dialCode: "245", names: { ar: "غينيا بيساو", tr: "Gine-Bissau", en: "Guinea-Bissau", ru: "Гвинея-Бисау" } },
  { iso2: "GY", dialCode: "592", names: { ar: "غيانا", tr: "Guyana", en: "Guyana", ru: "Гайана" } },
  { iso2: "HK", dialCode: "852", names: { ar: "هونغ كونغ الصينية (منطقة إدارية خاصة)", tr: "Çin Hong Kong ÖYB", en: "Hong Kong", ru: "Гонконг" } },
  { iso2: "HM", dialCode: "61", names: { ar: "جزيرة هيرد وجزر ماكدونالد", tr: "Heard Adası ve McDonald Adaları", en: "Heard Island and McDonald Islands", ru: "Херд и Макдональд" } },
  { iso2: "HN", dialCode: "504", names: { ar: "هندوراس", tr: "Honduras", en: "Honduras", ru: "Гондурас" } },
  { iso2: "HR", dialCode: "385", names: { ar: "كرواتيا", tr: "Hırvatistan", en: "Croatia", ru: "Хорватия" } },
  { iso2: "HT", dialCode: "509", names: { ar: "هايتي", tr: "Haiti", en: "Haiti", ru: "Гаити" } },
  { iso2: "HU", dialCode: "36", names: { ar: "هنغاريا", tr: "Macaristan", en: "Hungary", ru: "Венгрия" } },
  { iso2: "ID", dialCode: "62", names: { ar: "إندونيسيا", tr: "Endonezya", en: "Indonesia", ru: "Индонезия" } },
  { iso2: "IE", dialCode: "353", names: { ar: "أيرلندا", tr: "İrlanda", en: "Ireland", ru: "Ирландия" } },
  { iso2: "IL", dialCode: "972", names: { ar: "إسرائيل", tr: "İsrail", en: "Israel", ru: "Израиль" } },
  { iso2: "IM", dialCode: "44", names: { ar: "جزيرة مان", tr: "Man Adası", en: "Isle of Man", ru: "Остров Мэн" } },
  { iso2: "IN", dialCode: "91", names: { ar: "الهند", tr: "Hindistan", en: "India", ru: "Индия" } },
  { iso2: "IO", dialCode: "246", names: { ar: "الإقليم البريطاني في المحيط الهندي", tr: "Britanya Hint Okyanusu Toprakları", en: "British Indian Ocean Territory", ru: "Британская территория в Индийском океане" } },
  { iso2: "IQ", dialCode: "964", names: { ar: "العراق", tr: "Irak", en: "Iraq", ru: "Ирак" } },
  { iso2: "IR", dialCode: "98", names: { ar: "إيران", tr: "İran", en: "Iran", ru: "Иран" }, aliases: { tr: [], en: ["Islamic Republic of Iran"], ru: [] } },
  { iso2: "IS", dialCode: "354", names: { ar: "آيسلندا", tr: "İzlanda", en: "Iceland", ru: "Исландия" } },
  { iso2: "IT", dialCode: "39", names: { ar: "إيطاليا", tr: "İtalya", en: "Italy", ru: "Италия" } },
  { iso2: "JE", dialCode: "44", names: { ar: "جيرسي", tr: "Jersey", en: "Jersey", ru: "Джерси" } },
  { iso2: "JM", dialCode: "1876", names: { ar: "جامايكا", tr: "Jamaika", en: "Jamaica", ru: "Ямайка" } },
  { iso2: "JO", dialCode: "962", names: { ar: "الأردن", tr: "Ürdün", en: "Jordan", ru: "Иордания" } },
  { iso2: "JP", dialCode: "81", names: { ar: "اليابان", tr: "Japonya", en: "Japan", ru: "Япония" } },
  { iso2: "KE", dialCode: "254", names: { ar: "كينيا", tr: "Kenya", en: "Kenya", ru: "Кения" } },
  { iso2: "KG", dialCode: "996", names: { ar: "قيرغيزستان", tr: "Kırgızistan", en: "Kyrgyzstan", ru: "Киргизия" } },
  { iso2: "KH", dialCode: "855", names: { ar: "كمبوديا", tr: "Kamboçya", en: "Cambodia", ru: "Камбоджа" } },
  { iso2: "KI", dialCode: "686", names: { ar: "كيريباتي", tr: "Kiribati", en: "Kiribati", ru: "Кирибати" } },
  { iso2: "KM", dialCode: "269", names: { ar: "جزر القمر", tr: "Komorlar", en: "Comoros", ru: "Коморы" } },
  { iso2: "KN", dialCode: "1869", names: { ar: "سانت كيتس ونيفيس", tr: "Saint Kitts ve Nevis", en: "Saint Kitts and Nevis", ru: "Сент-Китс и Невис" } },
  { iso2: "KP", dialCode: "850", names: { ar: "كوريا الشمالية", tr: "Kuzey Kore", en: "North Korea", ru: "КНДР (Корейская Народно-Демократическая Республика)" } },
  { iso2: "KR", dialCode: "82", names: { ar: "كوريا الجنوبية", tr: "Güney Kore", en: "South Korea", ru: "Республика Корея" }, aliases: { tr: [], en: ["Korea, Republic of", "Republic of Korea"], ru: [] } },
  { iso2: "KW", dialCode: "965", names: { ar: "الكويت", tr: "Kuveyt", en: "Kuwait", ru: "Кувейт" } },
  { iso2: "KY", dialCode: "1345", names: { ar: "جزر كايمان", tr: "Cayman Adaları", en: "Cayman Islands", ru: "Острова Кайман" } },
  { iso2: "KZ", dialCode: "7", names: { ar: "كازاخستان", tr: "Kazakistan", en: "Kazakhstan", ru: "Казахстан" } },
  { iso2: "LA", dialCode: "856", names: { ar: "لاوس", tr: "Laos", en: "Lao People's Democratic Republic", ru: "Лаос" }, aliases: { tr: [], en: ["Laos"], ru: [] } },
  { iso2: "LB", dialCode: "961", names: { ar: "لبنان", tr: "Lübnan", en: "Lebanon", ru: "Ливан" } },
  { iso2: "LC", dialCode: "1758", names: { ar: "سانت لوسيا", tr: "Saint Lucia", en: "Saint Lucia", ru: "Сент-Люсия" } },
  { iso2: "LI", dialCode: "423", names: { ar: "ليختنشتاين", tr: "Liechtenstein", en: "Liechtenstein", ru: "Лихтенштейн" } },
  { iso2: "LK", dialCode: "94", names: { ar: "سريلانكا", tr: "Sri Lanka", en: "Sri Lanka", ru: "Шри-Ланка" } },
  { iso2: "LR", dialCode: "231", names: { ar: "ليبيريا", tr: "Liberya", en: "Liberia", ru: "Либерия" } },
  { iso2: "LS", dialCode: "266", names: { ar: "ليسوتو", tr: "Lesoto", en: "Lesotho", ru: "Лесото" } },
  { iso2: "LT", dialCode: "370", names: { ar: "ليتوانيا", tr: "Litvanya", en: "Lithuania", ru: "Литва" } },
  { iso2: "LU", dialCode: "352", names: { ar: "لوكسمبورغ", tr: "Lüksemburg", en: "Luxembourg", ru: "Люксембург" } },
  { iso2: "LV", dialCode: "371", names: { ar: "لاتفيا", tr: "Letonya", en: "Latvia", ru: "Латвия" } },
  { iso2: "LY", dialCode: "218", names: { ar: "ليبيا", tr: "Libya", en: "Libya", ru: "Ливия" } },
  { iso2: "MA", dialCode: "212", names: { ar: "المغرب", tr: "Fas", en: "Morocco", ru: "Марокко" } },
  { iso2: "MC", dialCode: "377", names: { ar: "موناكو", tr: "Monako", en: "Monaco", ru: "Монако" } },
  { iso2: "MD", dialCode: "373", names: { ar: "مولدوفا", tr: "Moldova", en: "Moldova, Republic of", ru: "Молдавия" }, aliases: { tr: [], en: ["Moldova"], ru: [] } },
  { iso2: "ME", dialCode: "382", names: { ar: "الجبل الأسود", tr: "Karadağ", en: "Montenegro", ru: "Черногория" } },
  { iso2: "MF", dialCode: "590", names: { ar: "سان مارتن", tr: "Saint Martin", en: "Saint Martin (French part)", ru: "Сен-Мартен" }, aliases: { tr: [], en: ["Saint Martin"], ru: [] } },
  { iso2: "MG", dialCode: "261", names: { ar: "مدغشقر", tr: "Madagaskar", en: "Madagascar", ru: "Мадагаскар" } },
  { iso2: "MH", dialCode: "692", names: { ar: "جزر مارشال", tr: "Marshall Adaları", en: "Marshall Islands", ru: "Маршалловы Острова" } },
  { iso2: "MK", dialCode: "389", names: { ar: "مقدونيا الشمالية", tr: "Kuzey Makedonya", en: "North Macedonia", ru: "Северная Македония" }, aliases: { tr: [], en: ["The Republic of North Macedonia"], ru: [] } },
  { iso2: "ML", dialCode: "223", names: { ar: "مالي", tr: "Mali", en: "Mali", ru: "Мали" } },
  { iso2: "MM", dialCode: "95", names: { ar: "ميانمار (بورما)", tr: "Myanmar (Burma)", en: "Myanmar", ru: "Мьянма" } },
  { iso2: "MN", dialCode: "976", names: { ar: "منغوليا", tr: "Moğolistan", en: "Mongolia", ru: "Монголия" } },
  { iso2: "MO", dialCode: "853", names: { ar: "منطقة ماكاو الإدارية الخاصة", tr: "Çin Makao ÖYB", en: "Macao", ru: "Макао" } },
  { iso2: "MP", dialCode: "1670", names: { ar: "جزر ماريانا الشمالية", tr: "Kuzey Mariana Adaları", en: "Northern Mariana Islands", ru: "Северные Марианские Острова" } },
  { iso2: "MQ", dialCode: "596", names: { ar: "جزر المارتينيك", tr: "Martinik", en: "Martinique", ru: "Мартиника" } },
  { iso2: "MR", dialCode: "222", names: { ar: "موريتانيا", tr: "Moritanya", en: "Mauritania", ru: "Мавритания" } },
  { iso2: "MS", dialCode: "1664", names: { ar: "مونتسرات", tr: "Montserrat", en: "Montserrat", ru: "Монтсеррат" } },
  { iso2: "MT", dialCode: "356", names: { ar: "مالطا", tr: "Malta", en: "Malta", ru: "Мальта" } },
  { iso2: "MU", dialCode: "230", names: { ar: "موريشيوس", tr: "Mauritius", en: "Mauritius", ru: "Маврикий" } },
  { iso2: "MV", dialCode: "960", names: { ar: "جزر المالديف", tr: "Maldivler", en: "Maldives", ru: "Мальдивы" } },
  { iso2: "MW", dialCode: "265", names: { ar: "ملاوي", tr: "Malavi", en: "Malawi", ru: "Малави" } },
  { iso2: "MX", dialCode: "52", names: { ar: "المكسيك", tr: "Meksika", en: "Mexico", ru: "Мексика" } },
  { iso2: "MY", dialCode: "60", names: { ar: "ماليزيا", tr: "Malezya", en: "Malaysia", ru: "Малайзия" } },
  { iso2: "MZ", dialCode: "258", names: { ar: "موزمبيق", tr: "Mozambik", en: "Mozambique", ru: "Мозамбик" } },
  { iso2: "NA", dialCode: "264", names: { ar: "ناميبيا", tr: "Namibya", en: "Namibia", ru: "Намибия" } },
  { iso2: "NC", dialCode: "687", names: { ar: "كاليدونيا الجديدة", tr: "Yeni Kaledonya", en: "New Caledonia", ru: "Новая Каледония" } },
  { iso2: "NE", dialCode: "227", names: { ar: "النيجر", tr: "Nijer", en: "Niger", ru: "Нигер" } },
  { iso2: "NF", dialCode: "672", names: { ar: "جزيرة نورفولك", tr: "Norfolk Adası", en: "Norfolk Island", ru: "Остров Норфолк" } },
  { iso2: "NG", dialCode: "234", names: { ar: "نيجيريا", tr: "Nijerya", en: "Nigeria", ru: "Нигерия" } },
  { iso2: "NI", dialCode: "505", names: { ar: "نيكاراغوا", tr: "Nikaragua", en: "Nicaragua", ru: "Никарагуа" } },
  { iso2: "NL", dialCode: "31", names: { ar: "هولندا", tr: "Hollanda", en: "Netherlands", ru: "Нидерланды" }, aliases: { tr: [], en: ["Netherlands (Kingdom of the)", "The Netherlands"], ru: [] } },
  { iso2: "NO", dialCode: "47", names: { ar: "النرويج", tr: "Norveç", en: "Norway", ru: "Норвегия" } },
  { iso2: "NP", dialCode: "977", names: { ar: "نيبال", tr: "Nepal", en: "Nepal", ru: "Непал" } },
  { iso2: "NR", dialCode: "674", names: { ar: "ناورو", tr: "Nauru", en: "Nauru", ru: "Науру" } },
  { iso2: "NU", dialCode: "683", names: { ar: "نيوي", tr: "Niue", en: "Niue", ru: "Ниуэ" } },
  { iso2: "NZ", dialCode: "64", names: { ar: "نيوزيلندا", tr: "Yeni Zelanda", en: "New Zealand", ru: "Новая Зеландия" } },
  { iso2: "OM", dialCode: "968", names: { ar: "عُمان", tr: "Umman", en: "Oman", ru: "Оман" } },
  { iso2: "PA", dialCode: "507", names: { ar: "بنما", tr: "Panama", en: "Panama", ru: "Панама" } },
  { iso2: "PE", dialCode: "51", names: { ar: "بيرو", tr: "Peru", en: "Peru", ru: "Перу" } },
  { iso2: "PF", dialCode: "689", names: { ar: "بولينيزيا الفرنسية", tr: "Fransız Polinezyası", en: "French Polynesia", ru: "Французская Полинезия" } },
  { iso2: "PG", dialCode: "675", names: { ar: "بابوا غينيا الجديدة", tr: "Papua Yeni Gine", en: "Papua New Guinea", ru: "Папуа — Новая Гвинея" } },
  { iso2: "PH", dialCode: "63", names: { ar: "الفلبين", tr: "Filipinler", en: "Philippines", ru: "Филиппины" } },
  { iso2: "PK", dialCode: "92", names: { ar: "باكستان", tr: "Pakistan", en: "Pakistan", ru: "Пакистан" } },
  { iso2: "PL", dialCode: "48", names: { ar: "بولندا", tr: "Polonya", en: "Poland", ru: "Польша" } },
  { iso2: "PM", dialCode: "508", names: { ar: "سان بيير ومكويلون", tr: "Saint Pierre ve Miquelon", en: "Saint Pierre and Miquelon", ru: "Сен-Пьер и Микелон" } },
  { iso2: "PN", dialCode: "64", names: { ar: "جزر بيتكيرن", tr: "Pitcairn Adaları", en: "Pitcairn", ru: "Острова Питкэрн" }, aliases: { tr: [], en: ["Pitcairn Islands"], ru: [] } },
  { iso2: "PR", dialCode: "1787", names: { ar: "بورتوريكو", tr: "Porto Riko", en: "Puerto Rico", ru: "Пуэрто-Рико" } },
  { iso2: "PS", dialCode: "970", names: { ar: "الأراضي الفلسطينية", tr: "Filistin", en: "Palestine", ru: "Палестина" }, aliases: { tr: ["Filistin Bölgeleri"], en: ["State of Palestine"], ru: ["Государство Палестина"] } },
  { iso2: "PT", dialCode: "351", names: { ar: "البرتغال", tr: "Portekiz", en: "Portugal", ru: "Португалия" } },
  { iso2: "PW", dialCode: "680", names: { ar: "بالاو", tr: "Palau", en: "Palau", ru: "Палау" } },
  { iso2: "PY", dialCode: "595", names: { ar: "باراغواي", tr: "Paraguay", en: "Paraguay", ru: "Парагвай" } },
  { iso2: "QA", dialCode: "974", names: { ar: "قطر", tr: "Katar", en: "Qatar", ru: "Катар" } },
  { iso2: "RE", dialCode: "262", names: { ar: "روينيون", tr: "Réunion", en: "Reunion", ru: "Реюньон" } },
  { iso2: "RO", dialCode: "40", names: { ar: "رومانيا", tr: "Romanya", en: "Romania", ru: "Румыния" } },
  { iso2: "RS", dialCode: "381", names: { ar: "صربيا", tr: "Sırbistan", en: "Serbia", ru: "Сербия" } },
  { iso2: "RU", dialCode: "7", names: { ar: "روسيا", tr: "Rusya", en: "Russia", ru: "Россия" }, aliases: { tr: [], en: ["Russian Federation"], ru: ["Российская Федерация"] } },
  { iso2: "RW", dialCode: "250", names: { ar: "رواندا", tr: "Ruanda", en: "Rwanda", ru: "Руанда" } },
  { iso2: "SA", dialCode: "966", names: { ar: "المملكة العربية السعودية", tr: "Suudi Arabistan", en: "Saudi Arabia", ru: "Саудовская Аравия" } },
  { iso2: "SB", dialCode: "677", names: { ar: "جزر سليمان", tr: "Solomon Adaları", en: "Solomon Islands", ru: "Соломоновы Острова" } },
  { iso2: "SC", dialCode: "248", names: { ar: "سيشل", tr: "Seyşeller", en: "Seychelles", ru: "Сейшельские Острова" } },
  { iso2: "SD", dialCode: "249", names: { ar: "السودان", tr: "Sudan", en: "Sudan", ru: "Судан" } },
  { iso2: "SE", dialCode: "46", names: { ar: "السويد", tr: "İsveç", en: "Sweden", ru: "Швеция" } },
  { iso2: "SG", dialCode: "65", names: { ar: "سنغافورة", tr: "Singapur", en: "Singapore", ru: "Сингапур" } },
  { iso2: "SH", dialCode: "290", names: { ar: "سانت هيلينا", tr: "Saint Helena", en: "Saint Helena", ru: "Острова Святой Елены, Вознесения и Тристан-да-Кунья" } },
  { iso2: "SI", dialCode: "386", names: { ar: "سلوفينيا", tr: "Slovenya", en: "Slovenia", ru: "Словения" } },
  { iso2: "SJ", dialCode: "4779", names: { ar: "سفالبارد وجان ماين", tr: "Svalbard ve Jan Mayen Adaları", en: "Svalbard and Jan Mayen", ru: "Шпицберген и Ян-Майен" } },
  { iso2: "SK", dialCode: "421", names: { ar: "سلوفاكيا", tr: "Slovakya", en: "Slovakia", ru: "Словакия" } },
  { iso2: "SL", dialCode: "232", names: { ar: "سيراليون", tr: "Sierra Leone", en: "Sierra Leone", ru: "Сьерра-Леоне" } },
  { iso2: "SM", dialCode: "378", names: { ar: "سان مارينو", tr: "San Marino", en: "San Marino", ru: "Сан-Марино" } },
  { iso2: "SN", dialCode: "221", names: { ar: "السنغال", tr: "Senegal", en: "Senegal", ru: "Сенегал" } },
  { iso2: "SO", dialCode: "252", names: { ar: "الصومال", tr: "Somali", en: "Somalia", ru: "Сомали" } },
  { iso2: "SR", dialCode: "597", names: { ar: "سورينام", tr: "Surinam", en: "Suriname", ru: "Суринам" } },
  { iso2: "SS", dialCode: "211", names: { ar: "جنوب السودان", tr: "Güney Sudan", en: "South Sudan", ru: "Южный Судан" } },
  { iso2: "ST", dialCode: "239", names: { ar: "ساو تومي وبرينسيبي", tr: "São Tomé ve Príncipe", en: "Sao Tome and Principe", ru: "Сан-Томе и Принсипи" } },
  { iso2: "SV", dialCode: "503", names: { ar: "السلفادور", tr: "El Salvador", en: "El Salvador", ru: "Сальвадор" } },
  { iso2: "SX", dialCode: "1721", names: { ar: "سانت مارتن", tr: "Sint Maarten", en: "Sint Maarten (Dutch part)", ru: "Синт-Мартен" }, aliases: { tr: [], en: ["Sint Maarten"], ru: [] } },
  { iso2: "SY", dialCode: "963", names: { ar: "سوريا", tr: "Suriye", en: "Syrian Arab Republic", ru: "Сирия" }, aliases: { tr: [], en: ["Syria"], ru: [] } },
  { iso2: "SZ", dialCode: "268", names: { ar: "إسواتيني", tr: "Esvatini", en: "Eswatini", ru: "Эсватини" }, aliases: { tr: ["Svaziland"], en: [], ru: [] } },
  { iso2: "TC", dialCode: "1649", names: { ar: "جزر توركس وكايكوس", tr: "Turks ve Caicos Adaları", en: "Turks and Caicos Islands", ru: "Теркс и Кайкос" } },
  { iso2: "TD", dialCode: "235", names: { ar: "تشاد", tr: "Çad", en: "Chad", ru: "Чад" } },
  { iso2: "TF", dialCode: "262", names: { ar: "الأقاليم الجنوبية الفرنسية", tr: "Fransız Güney Toprakları", en: "French Southern Territories", ru: "Французские Южные и Антарктические Территории" } },
  { iso2: "TG", dialCode: "228", names: { ar: "توغو", tr: "Togo", en: "Togo", ru: "Того" } },
  { iso2: "TH", dialCode: "66", names: { ar: "تايلاند", tr: "Tayland", en: "Thailand", ru: "Таиланд" } },
  { iso2: "TJ", dialCode: "992", names: { ar: "طاجيكستان", tr: "Tacikistan", en: "Tajikistan", ru: "Таджикистан" } },
  { iso2: "TK", dialCode: "690", names: { ar: "توكيلاو", tr: "Tokelau", en: "Tokelau", ru: "Токелау" } },
  { iso2: "TL", dialCode: "670", names: { ar: "تيمور - ليشتي", tr: "Timor-Leste", en: "Timor-Leste", ru: "Восточный Тимор" }, aliases: { tr: [], en: ["East Timor"], ru: [] } },
  { iso2: "TM", dialCode: "993", names: { ar: "تركمانستان", tr: "Türkmenistan", en: "Turkmenistan", ru: "Туркмения" } },
  { iso2: "TN", dialCode: "216", names: { ar: "تونس", tr: "Tunus", en: "Tunisia", ru: "Тунис" } },
  { iso2: "TO", dialCode: "676", names: { ar: "تونغا", tr: "Tonga", en: "Tonga", ru: "Тонга" } },
  { iso2: "TR", dialCode: "90", names: { ar: "تركيا", tr: "Türkiye", en: "Turkey", ru: "Турция" }, aliases: { tr: [], en: ["Türkiye"], ru: [] } },
  { iso2: "TT", dialCode: "1868", names: { ar: "ترينيداد وتوباغو", tr: "Trinidad ve Tobago", en: "Trinidad and Tobago", ru: "Тринидад и Тобаго" } },
  { iso2: "TV", dialCode: "688", names: { ar: "توفالو", tr: "Tuvalu", en: "Tuvalu", ru: "Тувалу" } },
  { iso2: "TW", dialCode: "886", names: { ar: "تايوان", tr: "Tayvan", en: "Taiwan", ru: "Тайвань" }, aliases: { tr: [], en: ["Taiwan, Province of China"], ru: ["Китайская Республика"] } },
  { iso2: "TZ", dialCode: "255", names: { ar: "تنزانيا", tr: "Tanzanya", en: "Tanzania", ru: "Танзания" }, aliases: { tr: [], en: ["United Republic of Tanzania"], ru: [] } },
  { iso2: "UA", dialCode: "380", names: { ar: "أوكرانيا", tr: "Ukrayna", en: "Ukraine", ru: "Украина" } },
  { iso2: "UG", dialCode: "256", names: { ar: "أوغندا", tr: "Uganda", en: "Uganda", ru: "Уганда" } },
  { iso2: "UM", dialCode: "1", names: { ar: "جزر الولايات المتحدة النائية", tr: "ABD Uzak Adaları", en: "United States Minor Outlying Islands", ru: "Внешние малые острова (США)" }, aliases: { tr: [], en: ["U.S. Minor Outlying Islands"], ru: [] } },
  { iso2: "US", dialCode: "1", names: { ar: "الولايات المتحدة", tr: "Amerika Birleşik Devletleri", en: "United States", ru: "США" }, aliases: { tr: ["A.B.D.", "ABD", "Amerika", "Birleşik Devletler"], en: ["U.S.", "U.S.A.", "US", "USA", "United States of America"], ru: [] } },
  { iso2: "UY", dialCode: "598", names: { ar: "أورغواي", tr: "Uruguay", en: "Uruguay", ru: "Уругвай" } },
  { iso2: "UZ", dialCode: "998", names: { ar: "أوزبكستان", tr: "Özbekistan", en: "Uzbekistan", ru: "Узбекистан" } },
  { iso2: "VA", dialCode: "379", names: { ar: "الفاتيكان", tr: "Vatikan", en: "Vatican City", ru: "Ватикан" }, aliases: { tr: [], en: ["Holy See (Vatican City State)"], ru: [] } },
  { iso2: "VC", dialCode: "1784", names: { ar: "سانت فنسنت وجزر غرينادين", tr: "Saint Vincent ve Grenadinler", en: "Saint Vincent and the Grenadines", ru: "Сент-Винсент и Гренадины" } },
  { iso2: "VE", dialCode: "58", names: { ar: "فنزويلا", tr: "Venezuela", en: "Venezuela", ru: "Венесуэла" } },
  { iso2: "VG", dialCode: "1284", names: { ar: "جزر فيرجن البريطانية", tr: "Britanya Virjin Adaları", en: "Virgin Islands, British", ru: "Виргинские Острова (Великобритания)" }, aliases: { tr: [], en: ["British Virgin Islands"], ru: [] } },
  { iso2: "VI", dialCode: "1340", names: { ar: "جزر فيرجن الأمريكية", tr: "ABD Virjin Adaları", en: "Virgin Islands, U.S.", ru: "Виргинские Острова (США)" }, aliases: { tr: [], en: ["U.S. Virgin Islands"], ru: [] } },
  { iso2: "VN", dialCode: "84", names: { ar: "فيتنام", tr: "Vietnam", en: "Vietnam", ru: "Вьетнам" } },
  { iso2: "VU", dialCode: "678", names: { ar: "فانواتو", tr: "Vanuatu", en: "Vanuatu", ru: "Вануату" } },
  { iso2: "WF", dialCode: "681", names: { ar: "جزر والس وفوتونا", tr: "Wallis ve Futuna Adaları", en: "Wallis and Futuna", ru: "Уоллис и Футуна" } },
  { iso2: "WS", dialCode: "685", names: { ar: "ساموا", tr: "Samoa", en: "Samoa", ru: "Самоа" } },
  { iso2: "XK", dialCode: "383", names: { ar: "كوسوفو", tr: "Kosova", en: "Kosovo", ru: "Косово" } },
  { iso2: "YE", dialCode: "967", names: { ar: "اليمن", tr: "Yemen", en: "Yemen", ru: "Йемен" } },
  { iso2: "YT", dialCode: "262", names: { ar: "مايوت", tr: "Mayotte", en: "Mayotte", ru: "Майотта" } },
  { iso2: "ZA", dialCode: "27", names: { ar: "جنوب أفريقيا", tr: "Güney Afrika", en: "South Africa", ru: "ЮАР" } },
  { iso2: "ZM", dialCode: "260", names: { ar: "زامبيا", tr: "Zambiya", en: "Zambia", ru: "Замбия" } },
  { iso2: "ZW", dialCode: "263", names: { ar: "زيمبابوي", tr: "Zimbabve", en: "Zimbabwe", ru: "Зимбабве" } },
];
